### ISSUE TITLE
Undocumented ErrorCode for ResponseTimeout when calling InvokeDeviceMethodAsync

### ISSUE THREAD

**Issue by MoaidHathot** [Azure/azure-iot-sdk-csharp#1139] opened 2019-11-25 08:59 UTC
When the device is exceeding the response-timeout, the server is getting a IotHubException with undocumented ErrorCode (504101). This error code is not found in [ErrorCode enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.common.exceptions.errorcode?view=azure-dotnet).
Microsoft Azure IoT Service Client SDK version 1.18.2
Microsoft Azure IoT Device Client SDK version 1.21.2

We were trying to find a way to identify response-timeouts in the server.

I have created two simple programs that simulate the issue, one as Device and one as a Server.

Device:

`

    async Task Main()
    {
        var connectionString = "";
        var deviceClient = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Mqtt);
        await deviceClient.SetMethodDefaultHandlerAsync(MessageHandler, null);

        Console.WriteLine("Press enter to quit.");
        Console.ReadLine();
        deviceClient.Dispose();
    } 
    async Task<MethodResponse> MessageHandler(MethodRequest methodRequest, object userContext)
    {
        await Task.Delay(TimeSpan.FromSeconds(10));
        return new MethodResponse(200);
    }
`

Server:

`

    async Task Main()
    {
	    var connectionString = $"";		
	    var deviceId = "device-01";
				
	    try
	    {
		    var service = ServiceClient.CreateFromConnectionString(connectionString);
		    var methodInvocation = new CloudToDeviceMethod("Test", TimeSpan.FromSeconds(6), TimeSpan.FromSeconds(5));
		
		    var response = await service.InvokeDeviceMethodAsync(deviceId, methodInvocation);
		
		    response.Dump();
	    }
	    catch (DeviceNotFoundException ex)
	   {
		    Console.WriteLine($"Failed to communicate with device. ErrorCode: {ex.Code}. Message: '{ex.Message}'. Exception: '{ex}'");
	     }
  	    catch (IotHubException ex)
	    {
		    Console.WriteLine($"Failed to communicate with IoTHub. ErrorCode: {ex.Code}. Message: '{ex.Message}'. Exception: '{ex}'");
	    }
    }
`

I'm getting the following Exception:

`Failed to communicate with IoTHub. ErrorCode: InvalidErrorCode. Message: '{"Message":"{\"errorCode\":504101,\"trackingId\":\"aad8070dbaad43808811392256eefa11-G:26-TimeStamp:11/25/2019 08:56:44-G:34-TimeStamp:11/25/2019 08:56:44\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{},\"timestampUtc\":\"2019-11-25T08:56:44.7442621Z\"}","ExceptionMessage":""}'. Exception: 'Microsoft.Azure.Devices.Common.Exceptions.IotHubException: {"Message":"{\"errorCode\":504101,\"trackingId\":\"aad8070dbaad43808811392256eefa11-G:26-TimeStamp:11/25/2019 08:56:44-G:34-TimeStamp:11/25/2019 08:56:44\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{},\"timestampUtc\":\"2019-11-25T08:56:44.7442621Z\"}","ExceptionMessage":""}
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T,T2](Uri requestUri, T entity, TimeSpan operationTimeout, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at UserQuery.Main() in C:\Users\moaid\AppData\Local\Temp\LINQPad6\_inbbetkg\ooxsiu\LINQPadQuery:line 15'`

**Comment by davilu** [comment] 2019-11-25 21:40
@MoaidHathot Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support  to create a support ticket to address this issue.

**Comment by abhipsaMisra** [comment] 2020-04-04 01:32
@MoaidHathot Were you able to get open a support ticket and get any additional informtion that you were looking for?

I am attaching some additional reference [here ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-504101-gatewaytimeout) for error code returned:

Error code: 504101 resolves to GatewayTimeout.
This is because the method invocation timeout set in your sample is 6secs; whereas the device client does not return the method handler for 10secs. This means that the service client method invocation request returned before it received any confirmation from the device if it completed successfully or not. This caused IoT Hub (and hence the service client SDK) to throw the exception.

I am closing this issue as this is the expected behavior from the SDK.

**Comment by az-iot-builder-01** [comment] 2020-04-04 01:32
@MoaidHathot, @davilu, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-04-04 01:32 UTC
Labels: IoTSDK, area-service
