### ISSUE TITLE
"Microsoft.Azure.Devices.Shared" not found issue in azure function

### ISSUE THREAD

**Issue by SummerSun** [Azure/azure-iot-sdk-csharp#129] opened 2017-07-10 05:40 UTC
Have an azure function, specify the depencies in project.json (I listed all the dependencies below):
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.Devices": "1.2.8",
        "NAudio": "1.7.3"
      }
    }
  }
}
```
Sometimes get error:

Exception while executing function: Functions.HttpTriggerDevKitTranslator
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.HttpTriggerDevKitTranslator ---> **System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35**' or one of its dependencies. The system cannot find the file specified.
   at **Microsoft.Azure.Devices.AmqpServiceClient..ctor(IotHubConnectionString iotHubConnectionString,Boolean useWebSocketOnly)**
   at async Submission#0.Run(HttpRequestMessage req,TraceWriter log) at  : 29
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 165
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.InvokeAsync[TReflected](Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,Object[] invokeParameters,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,IReadOnlyDictionary`2 parameters,TraceWriter traceWriter,ILogger logger,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception

Remove the dependency in project.json and re-add it back, issue solved.
Could anyone help with the investigation?

**Comment by sergaz-msft** [comment] 2017-07-10 13:46
Hi @SummerSun can you let me know what is the example\sample that you are following? Does this issue also occurs when you do the configuration of your function from the Azure Portal? Thanks.

**Comment by SummerSun** [comment] 2017-07-11 07:56
@sergaz-msft Hi, I didn't follow any sample. Actually, I just googled to know how to add nuget dependency in the project.json file.

What does do the configuration from the azure portal? I do update the project.json file in the portal "View Files".

**Comment by sergaz-msft** [comment] 2017-07-11 17:17
Hi @SummerSun . In my case I didn't add the dependencies on .json that is why I was asking what steps did you follow.

On my run.csx file I have something like:

#r "Microsoft.Azure.Devices.dll"
using Microsoft.Azure.Devices;
...

And then I add the dlls to the bin folder.

Share with us the steps you took (ideally from the Azure Documentation website). I need to reproduce the same as you "Adding-removing-adding again the dependency on project.json gets it work".

Thanks :)

**Comment by SummerSun** [comment] 2017-07-12 02:21
Hi @sergaz-msft  
Follow the steps in below link, add project.json file then add the nuget package, name & version.
Since it does repro every time, it's ok you put it low priority if you could not repro it.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages

**Comment by SummerSun** [comment] 2017-07-14 09:22
Besides, the way of adding the reference by # "Microsoft.Azure.Devices.dll" just does not work.
It is a nuget package, I don't think azure function knows where to find it.
2017-07-14T09:18:57.120 (2,1): error CS0006: Metadata file 'Microsoft.Azure.Devices' could not be found

**Comment by sergaz-msft** [comment] 2017-07-14 19:29
Hello @SummerSun our most recent nuget package should already be targeting .NetStandard 1.3 (it should have .NetFramework 4.6 compatibility), therefore it should work when used on Azure functions. I will go ahead and try to reproduce this on my Environment.

In order to use it like this:

**Comment by sergaz-msft** [comment] 2017-07-20 16:38
Hello @SummerSun . I couldn't reproduce your issue on my Azure Function. I created a new project.json file (without NAudio dependencie)
```json
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.Devices": "1.2.9"
      }
    }
  }
}
```

After that the file project.lock.json was automatically generated:
```json
{
  "version": 2,
  "targets": {
    ".NETFramework,Version=v4.6": {
      "Microsoft.AspNet.WebApi.Client/5.2.3": {
        "type": "package",
        "dependencies": {
          "Newtonsoft.Json": "6.0.4"
        },
        "frameworkAssemblies": [
          "System.Net.Http"
        ],
        "compile": {
          "lib/net45/System.Net.Http.Formatting.dll": {}
        },
        "runtime": {
          "lib/net45/System.Net.Http.Formatting.dll": {}
        }
      },
      "Microsoft.AspNet.WebApi.Core/5.2.3": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNet.WebApi.Client": "5.2.3"
        },
        "compile": {
          "lib/net45/System.Web.Http.dll": {}
        },
        "runtime": {
          "lib/net45/System.Web.Http.dll": {}
        }
      },
      "Microsoft.Azure.Amqp/2.0.6": {
        "type": "package",
        "compile": {
          "lib/net45/Microsoft.Azure.Amqp.dll": {}
        },
        "runtime": {
          "lib/net45/Microsoft.Azure.Amqp.dll": {}
        }
      },
      "Microsoft.Azure.Devices/1.2.9": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNet.WebApi.Client": "5.2.3",
          "Microsoft.AspNet.WebApi.Core": "5.2.3",
          "Microsoft.Azure.Amqp": "2.0.6",
          "Microsoft.Azure.Devices.Shared": "1.0.11",
          "PCLCrypto": "2.0.147"
        },
        "frameworkAssemblies": [
          "System",
          "System.Core",
          "System.Net.Http",
          "System.Runtime.Serialization"
        ],
        "compile": {
          "lib/net451/Microsoft.Azure.Devices.dll": {}
        },
        "runtime": {
          "lib/net451/Microsoft.Azure.Devices.dll": {}
        }
      },
      "Microsoft.Azure.Devices.Shared/1.0.11": {
        "type": "package",
        "dependencies": {
          "Newtonsoft.Json": "6.0.8"
        },
        "compile": {
          "lib/net45/Microsoft.Azure.Devices.Shared.dll": {}
        },
        "runtime": {
          "lib/net45/Microsoft.Azure.Devices.Shared.dll": {}
        }
      },
      "Newtonsoft.Json/6.0.8": {
        "type": "package",
        "compile": {
          "lib/net45/Newtonsoft.Json.dll": {}
        },
        "runtime": {
          "lib/net45/Newtonsoft.Json.dll": {}
        }
      },
      "PCLCrypto/2.0.147": {
        "type": "package",
        "dependencies": {
          "PInvoke.NCrypt": "0.3.2",
          "Validation": "2.2.8"
        },
        "compile": {
          "lib/net45/PCLCrypto.dll": {}
        },
        "runtime": {
          "lib/net45/PCLCrypto.dll": {}
        }
      },
      "PInvoke.BCrypt/0.3.2": {
        "type": "package",
        "dependencies": {
          "PInvoke.Kernel32": "0.3.2",
          "PInvoke.Windows.Core": "0.3.2"
        },
        "compile": {
          "lib/net40/PInvoke.BCrypt.dll": {}
        },
        "runtime": {
          "lib/net40/PInvoke.BCrypt.dll": {}
        }
      },
      "PInvoke.Kernel32/0.3.2": {
        "type": "package",
        "dependencies": {
          "PInvoke.Windows.Core": "0.3.2"
        },
        "compile": {
          "lib/net40/PInvoke.Kernel32.dll": {}
        },
        "runtime": {
          "lib/net40/PInvoke.Kernel32.dll": {}
        }
      },
      "PInvoke.NCrypt/0.3.2": {
        "type": "package",
        "dependencies": {
          "PInvoke.BCrypt": "0.3.2",
          "PInvoke.Windows.Core": "0.3.2"
        },
        "compile": {
          "lib/net40/PInvoke.NCrypt.dll": {}
        },
        "runtime": {
          "lib/net40/PInvoke.NCrypt.dll": {}
        }
      },
      "PInvoke.Windows.Core/0.3.2": {
        "type": "package",
        "compile": {
          "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.dll": {}
        },
        "runtime": {
          "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.dll": {}
        }
      },
      "Validation/2.2.8": {
        "type": "package",
        "compile": {
          "lib/dotnet/Validation.dll": {}
        },
        "runtime": {
          "lib/dotnet/Validation.dll": {}
        }
      }
    }
  },
  "libraries": {
    "Microsoft.AspNet.WebApi.Client/5.2.3": {
      "sha512": "3kiI8peSXbXHDDrRuo+QaX0iCEVRe0nvn2dBDRw656uPX32UalbBlSIDUDlJxu05eau4tnuhsikiUuugvvoUoQ==",
      "type": "package",
      "path": "microsoft.aspnet.webapi.client/5.2.3",
      "files": [
        "lib/net45/System.Net.Http.Formatting.dll",
        "lib/net45/System.Net.Http.Formatting.xml",
        "lib/portable-wp8+netcore45+net45+wp81+wpa81/System.Net.Http.Formatting.dll",
        "lib/portable-wp8+netcore45+net45+wp81+wpa81/System.Net.Http.Formatting.xml",
        "microsoft.aspnet.webapi.client.5.2.3.nupkg.sha512",
        "microsoft.aspnet.webapi.client.nuspec"
      ]
    },
    "Microsoft.AspNet.WebApi.Core/5.2.3": {
      "sha512": "o90QYlRV8VKR1S7+EcJw9w8WSyVFLl+IIzN8ILZ+n2t6rsc/KS8kBxRzA7wCFPRUHhebCfLqilBk39phvanx3g==",
      "type": "package",
      "path": "microsoft.aspnet.webapi.core/5.2.3",
      "files": [
        "Content/web.config.transform",
        "lib/net45/System.Web.Http.dll",
        "lib/net45/System.Web.Http.xml",
        "microsoft.aspnet.webapi.core.5.2.3.nupkg.sha512",
        "microsoft.aspnet.webapi.core.nuspec"
      ]
    },
    "Microsoft.Azure.Amqp/2.0.6": {
      "sha512": "2yoFmhmz87WL9tsCJ0RF/FZZIPxdtGPxCUJ9ERkQyyhWlHUKC4xWQSwDcy9jFpR3Ac+kSFpateIa1eUa0rfAVw==",
      "type": "package",
      "path": "microsoft.azure.amqp/2.0.6",
      "files": [
        "lib/monoandroid/Microsoft.Azure.Amqp.dll",
        "lib/net45/Microsoft.Azure.Amqp.XML",
        "lib/net45/Microsoft.Azure.Amqp.dll",
        "lib/netstandard1.3/Microsoft.Azure.Amqp.XML",
        "lib/netstandard1.3/Microsoft.Azure.Amqp.dll",
        "lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+UAP10/Microsoft.Azure.Amqp.dll",
        "lib/uap10.0/Microsoft.Azure.Amqp.dll",
        "lib/uap10.0/Microsoft.Azure.Amqp.pri",
        "microsoft.azure.amqp.2.0.6.nupkg.sha512",
        "microsoft.azure.amqp.nuspec"
      ]
    },
    "Microsoft.Azure.Devices/1.2.9": {
      "sha512": "Gvmys7GmPJXySKp3eUu14kbELFl6jOkQ/xxz/bSxSQ3OdYqCr4LdzV5bO6mJzqGGEtpJfCVVwoVQrB/wkBAGoQ==",
      "type": "package",
      "path": "microsoft.azure.devices/1.2.9",
      "files": [
        "lib/net451/Microsoft.Azure.Devices.XML",
        "lib/net451/Microsoft.Azure.Devices.dll",
        "lib/netstandard1.3/Microsoft.Azure.Devices.XML",
        "lib/netstandard1.3/Microsoft.Azure.Devices.dll",
        "lib/uap10.0/Microsoft.Azure.Devices.Uwp.XML",
        "lib/uap10.0/Microsoft.Azure.Devices.Uwp.dll",
        "lib/uap10.0/Microsoft.Azure.Devices.Uwp.pri",
        "microsoft.azure.devices.1.2.9.nupkg.sha512",
        "microsoft.azure.devices.nuspec",
        "thirdpartynotice.txt"
      ]
    },
    "Microsoft.Azure.Devices.Shared/1.0.11": {
      "sha512": "ZiRHywBpSQgtrQTVY8/RW4KPuMtII/7PUcMw96+gGloY1JOiL3VooVlOHIlFmAK2BS3FsiEmArvB1YZrIgRPig==",
      "type": "package",
      "path": "microsoft.azure.devices.shared/1.0.11",
      "files": [
        "lib/net45/Microsoft.Azure.Devices.Shared.dll",
        "lib/netstandard1.3/Microsoft.Azure.Devices.Shared.dll",
        "lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+UAP10/Microsoft.Azure.Devices.Shared.PCL.dll",
        "lib/uap10.0/Microsoft.Azure.Devices.Shared.UWP.dll",
        "lib/uap10.0/Microsoft.Azure.Devices.Shared.UWP.pri",
        "microsoft.azure.devices.shared.1.0.11.nupkg.sha512",
        "microsoft.azure.devices.shared.nuspec",
        "thirdpartynotice.txt"
      ]
    },
    "Newtonsoft.Json/6.0.8": {
      "sha512": "7ut47NDedTW19EbL0JpFDYUP62fcuz27hJrehCDNajdCS5NtqL+E39+7Um3OkNc2wl2ym7K8Ln5eNuLus6mVGQ==",
      "type": "package",
      "path": "newtonsoft.json/6.0.8",
      "files": [
        "lib/net20/Newtonsoft.Json.dll",
        "lib/net20/Newtonsoft.Json.xml",
        "lib/net35/Newtonsoft.Json.dll",
        "lib/net35/Newtonsoft.Json.xml",
        "lib/net40/Newtonsoft.Json.dll",
        "lib/net40/Newtonsoft.Json.xml",
        "lib/net45/Newtonsoft.Json.dll",
        "lib/net45/Newtonsoft.Json.xml",
        "lib/netcore45/Newtonsoft.Json.dll",
        "lib/netcore45/Newtonsoft.Json.xml",
        "lib/portable-net40+sl5+wp80+win8+wpa81/Newtonsoft.Json.dll",
        "lib/portable-net40+sl5+wp80+win8+wpa81/Newtonsoft.Json.xml",
        "lib/portable-net45+wp80+win8+wpa81+aspnetcore50/Newtonsoft.Json.dll",
        "lib/portable-net45+wp80+win8+wpa81+aspnetcore50/Newtonsoft.Json.xml",
        "newtonsoft.json.6.0.8.nupkg.sha512",
        "newtonsoft.json.nuspec",
        "tools/install.ps1"
      ]
    },
    "PCLCrypto/2.0.147": {
      "sha512": "OFNDBjhP+qPukqB8PiGbWDo70gHsEzSKupL47JisjYFQaGwlPPCnN8ah59QCzIvsg9IUr2AecGKXF3ONpyFL9g==",
      "type": "package",
      "path": "pclcrypto/2.0.147",
      "files": [
        "lib/MonoAndroid23/PCLCrypto.dll",
        "lib/MonoAndroid23/PCLCrypto.xml",
        "lib/MonoTouch10/PCLCrypto.dll",
        "lib/MonoTouch10/PCLCrypto.xml",
        "lib/net45/PCLCrypto.dll",
        "lib/net45/PCLCrypto.xml",
        "lib/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/PCLCrypto.dll",
        "lib/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/PCLCrypto.xml",
        "lib/portable-win81+wpa81/PCLCrypto.dll",
        "lib/portable-win81+wpa81/PCLCrypto.xml",
        "lib/wp80/PCLCrypto.dll",
        "lib/wp80/PCLCrypto.xml",
        "lib/xamarinios10/PCLCrypto.dll",
        "lib/xamarinios10/PCLCrypto.xml",
        "pclcrypto.2.0.147.nupkg.sha512",
        "pclcrypto.nuspec"
      ]
    },
    "PInvoke.BCrypt/0.3.2": {
      "sha512": "6nSjPx88F+dcQgxfbM/lkYhi/zQWxwBcGAS3de/Q7YmPr5QdLNv5ZMk2UEFpMQhlFNya4TdUy5i3HKA12uMa7Q==",
      "type": "package",
      "path": "pinvoke.bcrypt/0.3.2",
      "files": [
        "lib/net40/PInvoke.BCrypt.dll",
        "lib/net40/PInvoke.BCrypt.xml",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.BCrypt.dll",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.BCrypt.xml",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.BCrypt.dll",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.BCrypt.xml",
        "pinvoke.bcrypt.0.3.2.nupkg.sha512",
        "pinvoke.bcrypt.nuspec"
      ]
    },
    "PInvoke.Kernel32/0.3.2": {
      "sha512": "zkd5Vc5AQ9B489GMNlmd0wdKnRoLl1B/TnouwcjtaqWbDJ17TQSvBRnV7xjVEpBHQtL/248EaUTcDprJe9bZMA==",
      "type": "package",
      "path": "pinvoke.kernel32/0.3.2",
      "files": [
        "lib/net40/PInvoke.Kernel32.dll",
        "lib/net40/PInvoke.Kernel32.xml",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Kernel32.dll",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Kernel32.xml",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Kernel32.dll",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Kernel32.xml",
        "pinvoke.kernel32.0.3.2.nupkg.sha512",
        "pinvoke.kernel32.nuspec"
      ]
    },
    "PInvoke.NCrypt/0.3.2": {
      "sha512": "s7SIBXlr3qolZaM5mGEXG2sKBY4yFVHTWBlwhRC93le08Aj+n/IaFVnB9LBFv6mpCCivXdzad+9EX6HHds4PyQ==",
      "type": "package",
      "path": "pinvoke.ncrypt/0.3.2",
      "files": [
        "lib/net40/PInvoke.NCrypt.dll",
        "lib/net40/PInvoke.NCrypt.xml",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.NCrypt.dll",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.NCrypt.xml",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.NCrypt.dll",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.NCrypt.xml",
        "pinvoke.ncrypt.0.3.2.nupkg.sha512",
        "pinvoke.ncrypt.nuspec"
      ]
    },
    "PInvoke.Windows.Core/0.3.2": {
      "sha512": "cLG8L2mBqeM6mwKxYg34uZnW5A4cAqyWY4nh+ogxon6BOPLcuQ2QSK/b1IKduUIQg6mDgf06rZUVbuVVPi9+fg==",
      "type": "package",
      "path": "pinvoke.windows.core/0.3.2",
      "files": [
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.dll",
        "lib/portable-net40+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.xml",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.dll",
        "lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/PInvoke.Windows.Core.xml",
        "pinvoke.windows.core.0.3.2.nupkg.sha512",
        "pinvoke.windows.core.nuspec"
      ]
    },
    "Validation/2.2.8": {
      "sha512": "DMNc7JhPlgRwnR+NNb+ldoluObL+RBw96aMoiZae/Looa4vgaAnIysmle/bV2OKqDNW9oUBDckPyfa2+sX6JdA==",
      "type": "package",
      "path": "validation/2.2.8",
      "files": [
        "README.md",
        "lib/dotnet/Validation.dll",
        "lib/dotnet/Validation.xml",
        "lib/portable-net40+sl50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/Validation.dll",
        "lib/portable-net40+sl50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/Validation.xml",
        "lib/portable-net45+dnxcore50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/Validation.dll",
        "lib/portable-net45+dnxcore50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/Validation.xml",
        "tools/2013/RequiresNotNull.snippet",
        "tools/2013/RequiresNotNullOrEmpty.snippet",
        "tools/2015/RequiresNotNull.snippet",
        "tools/2015/RequiresNotNullOrEmpty.snippet",
        "tools/install_snippets.cmd",
        "tools/uninstall_snippets.cmd",
        "validation.2.2.8.nupkg.sha512",
        "validation.nuspec"
      ]
    }
  },
  "projectFileDependencyGroups": {
    "": [],
    ".NETFramework,Version=v4.6": [
      "Microsoft.Azure.Devices >= 1.2.9"
    ]
  },
  "tools": {},
  "projectFileToolGroups": {},
  "packageFolders": {
    "D:\\home\\data\\Functions\\packages\\nuget": {}
  }
}
```
And changed my run.csx with the following:
```csharp
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Devices;

const string connectionString = "<replace_with_iothub_connection_string>";
const string deviceID = "new_device";


static async Task SendMessage(TraceWriter log)
{
    var serviceClient = ServiceClient.CreateFromConnectionString(connectionString, Microsoft.Azure.Devices.TransportType.Amqp);
    var str = "Hello, Cloud!";
    var message = new Message(Encoding.ASCII.GetBytes(str));
    await serviceClient.SendAsync(deviceID, message);
    log.Info("C2D Message Sent");
}


public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request");

    try{
        await SendMessage(log);
        return req.CreateResponse(HttpStatusCode.OK, "C2D message sent");
    }
    catch (Exception exception)
    {
        return req.CreateResponse(HttpStatusCode.BadRequest, "Failed to send message: " + exception);
    }
}
```
All worked as expected and the message is sent to the device (C2D).
Let me know if you did something different, otherwise I will proceed and close this issue as solved.
Thanks!

**Comment by SummerSun** [comment] 2017-07-21 01:53
@sergaz-msft I said the issue did not repro every time. I have another colleague met this issue the other day. Anyway, you could treat it as low priority or just close it.

**Comment by sergaz-msft** [comment] 2017-07-21 08:19
Hello @SummerSun  can you reproduce the issue when including only the Microsoft.Azure.Devices dependency? I am suspecting that the import of Nuget packages are ordered top down and one can be replacing other's dependencies.

Thanks

**Comment by sergaz-msft** [comment] 2017-07-26 15:48
Hello @SummerSun I will go ahead and close the issue. Let us know if you need any other help.
Thank you

**Closed by sergaz-msft** 2017-07-26 15:48 UTC
Labels: CSS, investigation-required
