### ISSUE TITLE
Intermittent NullReferenceException in Microsoft.Azure.Amqp

### ISSUE THREAD

**Issue by ntrpnr** [Azure/azure-iot-sdk-csharp#1373] opened 2020-05-25 07:18 UTC
- **OS, version, SKU and CPU architecture used:** Windows 10 Enterprise 1909
- **Application's .NET Target Framework :** net472
- **Device:** Issue is present on any PC
- **SDK version used:** Microsoft.Azure.Amqp 2.4.2, Microsoft.Azure.Devices.Client 1.25.0

## Description of the issue:
_We don't know if this error is present because of an error in **our application**, in **Microsoft.Azure.Amqp** or in **Microsoft.Azure.Devices.Client**. Feel free to close / reroute this issue._

We have noticed a NullReferenceException in Microsoft.Azure.Amqp is being thrown after a while of "heavy" load. We send ~1500-2000 (1-50 simultaneous) messages using SendEventBatchAsync. The issue seems to be 100% reproducible in our application.

Right now we solve this by catching the _NullReferenceException_ and restarting the device client.

## Code sample exhibiting the issue:
`await this.deviceClient.SendEventBatchAsync(messages: messages, cancellationToken: this.sendMessageCts.Token);`

## Console log of the issue:
Partial stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Amqp.AmqpLink.SendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.AmqpLink.<>c.<Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.Delivery>.Invoke>b__67_0(AmqpLink thisPtr, Delivery paramDelivery, Int32 p1, Int32 p2, Int32 p3)
   at Microsoft.Azure.Amqp.AmqpLink.DoActionIfNotClosed[T1,T2,T3,T4](Func`6 action, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Azure.Amqp.AmqpLink.Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.Delivery>.Invoke(Delivery delivery)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWorkInternal(T work, Boolean fromList)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWork(T work)
   at Microsoft.Azure.Amqp.AmqpLink.StartSendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.AmqpLink.TrySendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.SendingAmqpLink.Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.AmqpMessage>.Invoke(AmqpMessage message)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWorkInternal(T work, Boolean fromList)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWork(T work)
   at Microsoft.Azure.Amqp.SendingAmqpLink.SendAsyncResult.Start()
   at Microsoft.Azure.Amqp.WorkCollection`3.StartWork(TKey key, TWork work)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.<SendAmqpMessageAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.<SendMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.<SendMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.<SendEventsAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.<SendEventAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendEventAsync>d__15.MoveNext()
```

AB#7295507

**Comment by abhipsaMisra** [comment] 2020-05-26 18:32
The stacktrace does seem to indicate this to be an issue with the amqp library.
Could you capture the SDK logs with a small sample that reproduces this issue: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

Our SDK logs have the log provider for the amqp logging enabled, so that should give you some additional context as well.

**Comment by abhipsaMisra** [comment] 2020-06-03 17:00
Are you still seeing this issue @ntrpnr ? Can you upload the SDK logs, with any personal information cleaned out.

**Comment by azabbasi** [comment] 2020-06-09 16:42
@ntrpnr we are eagerly waiting for the SDK logs to be able to address this issue.

**Comment by ntrpnr** [comment] 2020-06-09 18:30
Sorry for the delay - Currently under high workload and this is a little tricky to reproduce. Will try to get it.

**Comment by abhipsaMisra** [comment] 2020-06-19 21:00
@ntrpnr The stacktrace indicates that the error is originating from the AMQP library being used underneath. 
Once you do get a chance to reproduce this issue again, I would recommend opening an issue against [their library](https://github.com/Azure/azure-amqp), so that they can debug it further.

I am closing this issue, since there is no action item for the SDK team here.

**Comment by az-iot-builder-01** [comment] 2020-06-19 21:00
@abhipsaMisra, @azabbasi, @ntrpnr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-06-19 21:00 UTC
Labels: investigation-required
