### ISSUE TITLE
Cloud to Module message works directly from module to IoT Hub, but not through edgeHub

### ISSUE THREAD

**Issue by emilm** [Azure/azure-iot-sdk-csharp#1370] opened 2020-05-16 14:01 UTC
- **OS, version, SKU and CPU architecture used:** linux arm32v7hf , iot edge rev 9161dc8eb743c1e839cc7fec07ad3e7df085a42f

- **Application's .NET Target Framework :** core 3.1 
- **Device:** RPI3 
- **SDK version used:** Microsoft.Azure.Devices.Client 1.29-preview-004 

## Description of the issue:
Are my obsevations correct? Not sure if this is the right place to submit the issue, but here goes.

I use Microsoft.Azure.Devices.Client 1.29-preview-004.

Works connecting directly to IoT Hub module connection string, but if 
 IOTEDGE_GATEWAYHOSTNAME is specified, it connects through edgeHub and it doesn't seem to work.

## Code sample exhibiting the issue:

var client = ServiceClient.CreateFromConnectionString(_config["IotHubConnectionString"]);

...

await _client.SendAsync(deviceId, "myModule", message);

## Console log of the issue:
Nothing is received so no log :)

AB#7241616

**Comment by abhipsaMisra** [comment] 2020-05-18 16:46
@emilm 
Can you explain the scenario that you are trying to implement? From the sample code above, you are creating a service client instance, and using it to send cloud-to-device messages. I assume that the initialization of your module `myModule` client is the one that you are facing issues with?

If using the `CreateFromEnvironmentAsync` option for module client initialization, can you confirm that you have the required environmental variables set: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Edge/EdgeModuleClientFactory.cs#L79?. Also, do you see this behavior only over a particular protocol (amqp vs mqtt)?

**Comment by emilm** [comment] 2020-05-18 17:01
Hello and thank you! Someone will interact with my device. But it has to ask the server something. Therefore I need to implement a request / response pattern from module to cloud / IoT edge. So I need a "cloud to module" response.

So I create my moduleclient in java

`this.client = ModuleClient.createFromEnvironment(IotHubClientProtocol.AMQPS);`

env:
`HOSTNAME=myhost
IOTEDGE_MODULEID=mymodule
IOTEDGE_GATEWAYHOSTNAME=myhost
RuntimeLogLevel=Information
IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock
TERM=xterm
SHLVL=1
IOTEDGE_APIVERSION=2019-11-05
IOTEDGE_AUTHSCHEME=sasToken
IOTEDGE_MODULEGENERATIONID=<REDACTED>
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin
IOTEDGE_DEVICEID=<REDACTED>
IOTEDGE_IOTHUBHOSTNAME=<REDACTED>.azure-devices.net
_=/usr/bin/printenv
`
I tried both AMQP and MQTT on both sides.

**Comment by abhipsaMisra** [comment] 2020-05-18 18:21
Thanks for the information @emilm ; we'll  investigate this.

**Comment by timtay-microsoft** [comment] 2020-05-18 23:08
In the Java SDK, there is a check that makes a module client only subscribe to devicebound messages if it isn't connecting to an Edgehub. Is it possible the C# SDK does something similar?

**Comment by emilm** [comment] 2020-05-18 23:13
I use the Java library on the client side. Is there a way to log that the edgeHub receives a message to a module but fails to deliver it?
Thanks!

I switched to mqtt WS but no difference

**Comment by emilm** [comment] 2020-05-19 14:15
> In the Java SDK, there is a check that makes a module client only subscribe to devicebound messages if it isn't connecting to an Edgehub. Is it possible the C# SDK does something similar?

So mine does connect to edgehub. Should I try to drop GATEWAY_HOSTNAME and bypass edgeHub to make it work, or is this supposed to work with edgeHub?

**Comment by abhipsaMisra** [comment] 2020-05-19 17:30
So @emilm , are you using the C# client library to send the cloud to device message from the service, but the java client library to receive the messages on a module client instance?

**Comment by emilm** [comment] 2020-05-19 17:32
> So @emilm , are you using the C# client library to send the cloud to device message from the service, but the java client library to receive the messages on a module client instance?

Correct! I suspect there's something with edgeHub

**Comment by abhipsaMisra** [comment] 2020-05-19 17:37
@timtay-microsoft You did mention that the java client subscribes to devicebound messages only if it isn't connecting to an Edgehub. Do you have additional context on why that is? 
It might also be relevant here to differentiate between device bound messages and events, when talking about device client message subscription vs edge module event subscription.

**Comment by timtay-microsoft** [comment] 2020-05-19 17:39
I'm not entirely sure that edgehub supports routing cloud to device messages to modules. I'd bring this question to @varunpuranik 

If it does, then the Java SDK just needs to subscribe to the devicebound messages topic regardless of if it is connecting to IoT Hub or Edgehub

**Comment by timtay-microsoft** [comment] 2020-05-20 17:22
I have confirmed offline that edgehub does _not_ support cloud to device messages to modules. So this issue is by design. As such, I'm closing this issue. Feel free to bring up this as a feature request in the edgehub github repo, though

**Comment by az-iot-builder-01** [comment] 2020-05-20 17:23
@abhipsaMisra, @emilm, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by timtay-microsoft** 2020-05-20 17:22 UTC
Labels: area-edge, investigation-required
