### ISSUE TITLE
File upload - Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#1141] opened 2019-11-25 13:55 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION>Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> .NET Core 3.0
- **Device:** <DEVICETYPE> Desktop 
- **SDK version used:** <VERSION> 1.29.0-preview002
- **Authentication:** CA signed certificates 

## Description of the issue:
When using CA signed certificates for authentication I am not able to upload files even though I can connect to IoTHub. This happens in situation when I don't have registered all branch certificates in IoTHub. 

If leaf certificate has 3 branch certificates in hierarchy and I have registered only the first two in IoTHub (marked with blue). I can connect to IoTHub and perform:
- sending device to cloud messages
- reading desired properties
- updating reported properties
- direct method invocation handling

but I cannot upload files. 

Based on stack trace it looks like something is wrong with token that IoTHub returns to DeviceClient.

On the other hand when I register all branch certificates or just immediate branch one (marked with yellow) file upload starts to work.

**Why IoTHub and Azure storage service don't have consistent authentication behavior?**

![image](https://user-images.githubusercontent.com/6298686/69544456-0b72c680-0f90-11ea-8d71-9171d844b4c0.png)

## Console log of the issue:
Tracking ID is removed from log.
```
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":""}
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.UploadToBlobAsync(String blobName, Stream source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

**Comment by davilu** [comment] 2019-11-25 19:40
@Perun85 Thanks to report this issue. My understanding is storage service is separated with IoT Hub services. I'll forward this issue to service team to give you more details.

**Comment by davilu** [comment] 2019-11-25 21:40
@Perun85 Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support  to create a support ticket to address this issue.

**Comment by Perun85** [comment] 2019-11-26 06:57
@davilu  Thank you. I will do that.

**Comment by abhipsaMisra** [comment] 2020-04-04 00:36
Closing this issue since the customer confirmed that they will create a support ticket to address this issue from the service side.

**Comment by az-iot-builder-01** [comment] 2020-04-04 00:36
@davilu, @Perun85, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-04-04 00:36 UTC
Labels: IoTSDK, area-service
