### ISSUE TITLE
UploadToBlobAsync throws StorageException: "Server failed to authenticate the request"

### ISSUE THREAD

**Issue by atuzovic** [Azure/azure-iot-sdk-csharp#103] opened 2017-05-08 14:26 UTC
I am trying to upload image from UWP app via Azure IoT Hub, however I keep getting the same error over and over again.

Code that I am using is tested on regular C# Console App with .NET 4.6.2 and files are uploaded to Blob Storage without any issues.

Here is my project.json file:
```
{
  "dependencies": {
    "Microsoft.Azure.Devices.Client": "1.2.10",
    "WindowsAzure.Storage": "8.1.1",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.3"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

Exception is of type **Microsoft.WindowsAzure.Storage.StorageException** with error message:
**Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.**

Code is as follows:

```
DeviceAuthenticationWithRegistrySymmetricKey key = new deviceAuthenticationWithRegistrySymmetricKey(deviceId, deviceKey);

deviceClient = DeviceClient.Create(iotHubUri, key, TransportType.Mqtt);

await deviceClient.UploadToBlobAsync(fileName, stream);
```

**iotHubUri** contains host name of IoT Hub in format HOST.azure-devices.net
**deviceId** is device identifier under which device was registered with IoT Hub
**deviceKey** is device identifier received during device registration with IoT Hub

I am using Visual Studio 2015 with Update 3.

Am I missing something?

**Comment by enesuysal** [comment] 2017-05-08 15:53
Have you tried it with "WindowsAzure.Storage": "7.0.0" ?

**Comment by atuzovic** [comment] 2017-05-08 16:19
@enesuysal Yes, tried it right now again, same thing.

**Comment by atuzovic** [comment] 2017-05-08 17:18
Ok, I have managed to solve this on my own but I've grown couple of gray hairs in the process.

UploadToBlobAsync will work on UWP only if you specify  TransportType.Http1 (HTTPS). It does not work with AMQP or MQTT.

When it comes to regular .NET 4.6.2 console apps, it works well with all protocols.

Can someone please update official documentation for this - it is really frustrating to waste time guessing why is something not working.

**Comment by atuzovic** [comment] 2017-05-08 17:30
Ok, I've managed to isolate what is the issue, although the message is entirely misleading.

If I attempt to upload file named "snapshot.jpg", it works well.
If I however attempt to upload file named "snapshot (2).jpg" error above is raised.

Direct uploads of file "snapshot (2).jpg" to Storage works without any issues - it is only when IoT Hub is used to proxy SAS that this error occurs. 

Could it be that this extension to file name interferes with how is request formed to Storage by IoT Hub SDK?

**Comment by sergaz-msft** [comment] 2017-05-09 16:52
Hello @atuzovic can you confirm that you **can't** upload a file named with spaces both on the UWP and C# Sdk samples?

**Comment by sergaz-msft** [comment] 2017-05-12 10:24
Hello @atuzovic we identified the root cause of this issue and will deploy a fix. The SDK is encoding spaces with "+" and Azure Storage is expecting "%20". Thanks a lot for your contribution :)!

**Comment by atuzovic** [comment] 2017-05-12 12:17
Thank you for your prompt response! :)

**Comment by arunkaithayil** [comment] 2017-05-15 18:43
@atuzovic  We have checked in the fix for this issue . Commit - 863f6b01f3a083ef485bfa543ddf40675f00b8c7. Next SDK nuget release will have these fixes .

**Closed** 2017-05-15 22:18 UTC
Labels: bug
