### ISSUE TITLE
DeviceClient Dispose method doesn't tear down the underlying TCP/IP connection using AMQP

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-iot-sdk-csharp#832] opened 2019-03-12 18:21 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10
- **Application's .NET Target Framework :** <NETVERSION> 
.NET Core App 2.1
- **Device:** <DEVICETYPE> 
Desktop PC
- **SDK version used:** <VERSION> 
1.19.0

## Description of the issue:
DeviceClient Dispose method doesn't tear down the underlying TCP/IP connection using AMQP. As a result TCP/IP connection to outbound AMQP port **5671** can accumulate over period of time leading to port exhaustion. 

## Code sample exhibiting the issue:
Send 5 message in a loop for a device client object. Call it in **using  C# statement block**.

for (int i = 0; i < 5; i++)
   {
       using (DeviceClient mydeviceClient = DeviceClient.CreateFromConnectionString("HostName=MyHub.azure-devices.net;DeviceId=mydevice;SharedAccessKey=****", TransportType.Amqp_Tcp_Only))
                {

                    temperature = rnd.Next(20, 35);
                    humidity = rnd.Next(60, 80);
                    dataBuffer = string.Format("{{\"deviceId\":\"{0}\",\"messageId\":{1},\"temperature\":{2},\"humidity\":{3}}}", deviceId, i, temperature, humidity);
                    Message eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                    eventMessage.Properties.Add("temperatureAlert", (temperature > TEMPERATURE_THRESHOLD) ? "true" : "false");
                    Console.WriteLine("\t{0}> Sending message: {1}, Data: [{2}]", DateTime.Now.ToLocalTime(), i, dataBuffer);

                    try
                    {
                        mydeviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChanges);
                   //     await mydeviceClient.OpenAsync();
                        await mydeviceClient.SendEventAsync(eventMessage).ConfigureAwait(false);
                        //await mydeviceClient.CloseAsync();
                     //   mydeviceClient.Dispose();
                        Thread.Sleep(1000);
                    }

                    catch (Exception ex)
                    {
                        await mydeviceClient.CloseAsync();
                    }
                }
         }

## Expected Result
5 message should be sent to IoT Hub.  All 5 TCP/IP connection to outbound port 5671 are torn down

## Actual  Result
5 message are sent to IoT Hub. But TCP/IP connection to outbound port 5671 is not torn down on Dispose. This leads to 5 Established TCP/IP in use connection even though DeviceClient object is already disposed. 

## Key Points
1.) Looks like a **regression** for AMQP. Issue doesn't happen on older version of SDK **1.6.2**.
2.) It **doesn't** happen for MQTT. So it is specific to AMQP connection.

**Comment by anhashia** [comment] 2019-03-13 21:02
Similar to https://github.com/Azure/azure-iot-sdk-csharp/issues/832

**Comment by jenoola** [comment] 2019-04-10 00:59
@anhashia the issue is fixed in new release 1.20.0

**Comment by az-iot-builder-01** [comment] 2019-04-10 00:59
@jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-04-10 00:59 UTC
Labels: amqp-redesign-fixes, bug, fix-checked-in

**Comment by anhashia** [comment] 2019-04-15 17:40
@jenoola : Fixed in **1.20.0**. Thanks !
