### ISSUE TITLE
[Bug Report] Unexpected character '=' in 'ReadValue' state.

### ISSUE THREAD

**Issue by Uladzimir-Lashkevich** [Azure/azure-iot-sdk-csharp#3052] opened 2023-01-05 16:18 UTC
# Context

- **OS, version, SKU and CPU architecture used:**  Alpine Linux
- **Application's .NET Target Framework :**  .NET 6
- **Device:**  'Device Simulator' built on top of Microsoft.Azure.Devices.Client
- **SDK version used:** Microsoft.Azure.Devices.Client 1.41.3, Microsoft.Azure.Devices 1.38.2

## Description of the issue
Hello, guys!
Recently, we started to face with exception during reading of commands from IoTHub on one of our environments (on others it is working fine). It would be great if you could guide us and provide insights on why it might be raised and how it can be avoided. Seems like this place is expected in attached code path. 
Exception is thrown from this place in SDK - https://github.com/Azure/azure-iot-sdk-csharp/blob/main/iothub/device/src/Common/UrlEncodedDictionarySerializer.cs#L231

## Code sample exhibiting the issue
We cannot reproduce it on our own, only observe in logs for some Devices.

## Console log of the issue
```
System.FormatException - Unexpected character '=' in 'ReadValue' state.
at Microsoft.Azure.Devices.Client.Common.UrlEncodedDictionarySerializer.Tokenizer.GetTokens()+MoveNext()
   at Microsoft.Azure.Devices.Client.Common.UrlEncodedDictionarySerializer.Deserialize()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.PopulateMessagePropertiesFromPacket(Message message, PublishPacket publish)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.AcceptMessageAsync(IChannelHandlerContext context, PublishPacket publish)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SubscribeAsync(IChannelHandlerContext context, SubscribePacket packetPassed)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ProcessConnectAckAsync(IChannelHandlerContext context, ConnAckPacket packet)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ProcessMessageAsync(IChannelHandlerContext context, Packet packet)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SubscribeAsync(IChannelHandlerContext context, SubscribePacket packetPassed)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass20_0.<<ReceiveAsync>b__0>d.MoveNext()
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[T](Func`1 taskFunc, ShouldRetry shouldRetry, Func`2 isTransient, Action`3 onRetrying, Boolean fastFirstRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync(TimeSpan timeout)
```

**Comment by schoims** [comment] 2023-01-10 18:47
Hello, thank you for reaching out to us. We apologize for the technical difficulties you're experiencing.

I have looked into the issue you reported, but I was unable to replicate the error. In order to better assist you, could you provide more details of your use case? How do you send a cloud-to-device message? Based on the error message, it appears that an unexpected character ('=') was found while the app was attempting to read the value of a property in the URL-encoded string upon receiving a message from the cloud. 

Thank you.

**Comment by AndreiStselmashenkaEPAM** [comment] 2023-01-11 17:35
Hello @schoims 
This issue was reproduced for devices that were registered in IoT Hub when it was throttling. We register batch of devices on IoT Hub S1. For some registration IoT send an error that was expected, but there were devices that were registered but when we enabled simulators they started produce '=' error. To resolve problem with this list of devices I unregistered this devices and registered again, after this action error stopped to reproduce. Initial batch size was ~50k devices and ~300 of them did not work correctly after initial registration. Looks like problem is related to IoT Hub to. Possible it send some error message that does not parsed correctly.

I've review our code base and can confirm that we do not send '=' as a property.

Thank you.

CC: @Uladzimir-Lashkevich

**Comment by schoims** [comment] 2023-01-13 18:34
Thank you for providing more context. It appears that an issue with URL encoding has occurred while the IoT hub was under throttling. We are investigating the issue. 

Thank you.

**Comment by schoims** [comment] 2023-01-13 22:25
Could you confirm if a direct method you are invoking includes special characters such as '=&/'?

**Comment by schoims** [comment] 2023-01-14 00:37
We apologize for the inconvenience, but there is a limited quota for new device connections. Higher of 100 connections/sec or 12 connections/sec/unit is the quota for S1 tier (https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#operation-throttles). For the DPS (Device Provisioning Service) has 1000 device registrations/per unit/min/service (https://learn.microsoft.com/en-us/azure/iot-dps/about-iot-dps#quotas-and-limits). To mitigate this issue, you can increase the number of units or ensures the usage do not exceed the quota. Feel free to let us know if you have any other questions.

Thank you.

**Comment by schoims** [comment] 2023-01-31 01:26
Hi @AndreiStselmashenkaEPAM

Could you share the steps/script/code that you used to provision 50k devices when you encountered this error? If I could take a look at the code, I would be able to better assist in resolving this issue. 

Thank you.

**Comment by tmahmood-microsoft** [comment] 2023-03-23 20:35
Hi @AndreiStselmashenkaEPAM are you still facing the issue otherwise I can close this.

**Comment by tmahmood-microsoft** [comment] 2023-03-29 17:13
Closing due to inactivity. Feel free to reopen this for further assistance.

**Closed by tmahmood-microsoft** 2023-03-29 17:13 UTC
Labels: bug, IoTSDK
