### ISSUE TITLE
MQTT Websocket DeviceClient setup with HTTP Proxy relies on local DNS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1063] opened 2019-09-16 02:43 UTC
- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04 
- **Application's .NET Target Framework :** netcoreapp 2.1
- **Device:** Laptop
- **SDK version used:** 1.21.1

## Description of the issue:
I assume, when connecting behind HTTP proxy, the local DNS server should have no impact on the DeviceClient (?). I tried running MessageSample [below link] inside a docker container as below. In step 2, please note the _--dns_ flag with invalid IP.

1. dotnet publish -c Release -o /tmp/out 
2. docker run --rm -it --dns=128.0.0.1 -v /tmp/out:/app microsoft/dotnet:2.1-runtime-stretch-slim /bin/bash 
3.   cd /app
4.   export https_proxy=PROXY_IP:PROXY_PORT
5.   dotnet MessageSample.dll

Below are observations.

1. The sample works perfectly using AMQP_WS under the same invalidated DNS server.  The issue is only for MQTT_WS protocol. 
2. The same program works perfectly with MQTT_WS if the DNS server is not wrong (not using wrong DNS with --dns=128.0.0.1 )

## Code sample exhibiting the issue:
https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/MessageSample

## Console log of the issue:
> Device sending 5 messages to IoTHub...
> Sending message: 0, Data: [{"messageId":0,"temperature":30,"humidity":79}]

> Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Resource temporarily unavailable
>    at System.Net.Dns.InternalGetHostByName(String hostName)
>    at System.Net.Dns.ResolveCallback(Object context)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
>    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
>    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
>    at Microsoft.Azure.Devices.Client.Samples.MessageSample.SendEvent() in /home/roots/src/try/dns/MessageSample.cs:line 36
>    at Microsoft.Azure.Devices.Client.Samples.MessageSample.RunSampleAsync() in /home/roots/src/try/dns/MessageSample.cs:line 26
>    at Microsoft.Azure.Devices.Client.Samples.Program.Main(String[] args) in /home/roots/src/try/dns/Program.cs:line 45

**Comment by CIPop** [comment] 2019-09-17 17:30
Thanks for reporting @kiranpradeep!
The issue is likely that regardless if the Proxy is configured or not, the `MqttTransportHandler` will perform a DNS lookup. We should only do that if a proxy isn't configured.
/cc @abhipsaMisra

**Comment by timtay-microsoft** [comment] 2020-04-13 18:15
This does look like a bug on our side. We don't need to do a DNS lookup when a proxy is configured. We'll fix the SDK to not do that

**Comment by abhipsaMisra** [comment] 2020-06-11 01:07
This fix has been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-05-06
Closing this issue.

**Comment by az-iot-builder-01** [comment] 2020-06-11 01:07
@kiranpradeep, @CIPop, @timtay-microsoft, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-06-11 01:07 UTC
Labels: IoTSDK, bug, fix-checked-in
