### ISSUE TITLE
Cannot import system module information with RegistryManager.ImportDevicesAsync

### ISSUE THREAD

**Issue by yukhgcsh** [Azure/azure-iot-sdk-csharp#1146] opened 2019-12-03 15:58 UTC
- **OS, version, SKU and CPU architecture used:** Windows 10 Laptop x64 
- **Application's .NET Target Framework :** netcoreapp2.1 and netcoreapp3.0(both) 
- **Device:** Laptop 
- **SDK version used:**
    * Microsoft.Azure.Devices v1.18.2
    * WindowsAzure.Storage v9.3.3

## Description of the issue:

I try to copy IoT Hub device information(including module information) to another one using `RegistryManager.ExportDevicesAsync` and `RegistryManager.ImportDevicesAsync`.(with reference to <https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt>)  
Method `RegistryManager.ExportDevicesAsync` can export module information.
```txt
{"id":"device","eTag":"ODcwMDE5Njk1","status":"enabled","statusReason":"","authentication":null,"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":true}}
{"id":"device","moduleId":"$edgeAgent","eTag":"ODcwMDE5Njk1","status":"enabled","authentication":null,"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":false}}
{"id":"device","moduleId":"$edgeHub","eTag":"ODcwMDE5Njk1","status":"enabled","authentication":null,"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":false}}
{"id":"device","moduleId":"customModule","eTag":"ODcwMDE5Njk1","status":"enabled","authentication":null,"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":false}}
```

But, method `RegistryManager.ImportDevicesAsync` can not import system module(edgeAgent and edgeHub) information. Device information and custom module information are imported successfully. When execute `RegistryManager.ImportDevicesAsync`, a blob named **importErrors** is created in Blob Storage. The contents of importErrors are as follows:
```txt
{"errorCode":400012,"errorStatus":"The module identifier $edgeAgent is invalid."}
{"errorCode":400012,"errorStatus":"The module identifier $edgeHub is invalid."}
```  

It seems that validation of module ID failed when importing to IoTHub. This is because `$` cannot be used when creating a module.  
Is it a specification that `RegistryManager.ImportDevicesAsync` cannot import system module information?  
Please tell me how to move all device information(including system module information) to another IoT Hub.

## Code sample exhibiting the issue:

```charp
class Program
{
    private const string SourceIoTHub = "IoT Hub connection string to export.";
    private const string DestinationIoTHub = "IoT Hub connection string to import.";
    private const string StorageConnectionString = "Storage account connection string to store export file.";

    static async Task Main()
    {
        var account = CloudStorageAccount.Parse(StorageConnectionString);
        var client = account.CreateCloudBlobClient();
        var container = client.GetContainerReference("container");
        var uriBuilder = new UriBuilder(container.Uri)
        {
            Query = container.GetSharedAccessSignature(
                new SharedAccessBlobPolicy
                {
					Permissions = SharedAccessBlobPermissions.Read | SharedAccessBlobPermissions.Delete | SharedAccessBlobPermissions.Write,
                    SharedAccessStartTime = DateTime.UtcNow.AddMinutes(-1),
                    SharedAccessExpiryTime = DateTime.UtcNow.AddHours(1)
                }
            )
        };

        using (var sourceManager = RegistryManager.CreateFromConnectionString(SourceIoTHub))
        {
            var jobProperty = await sourceManager.ExportDevicesAsync(uriBuilder.ToString(), false, CancellationToken.None).ConfigureAwait(false);
            while (jobProperty.Status == JobStatus.Enqueued
                || jobProperty.Status == JobStatus.Queued
                || jobProperty.Status == JobStatus.Running
                || jobProperty.Status == JobStatus.Scheduled)
            {
                jobProperty = await sourceManager.GetJobAsync(jobProperty.JobId).ConfigureAwait(false);
                await Task.Delay(3000).ConfigureAwait(false);
            }
        }

        using (var destinationManager = RegistryManager.CreateFromConnectionString(DestinationIoTHub))
        {
            var jobProperty = await destinationManager.ImportDevicesAsync(uriBuilder.ToString(), uriBuilder.ToString(), CancellationToken.None).ConfigureAwait(false);
            while (jobProperty.Status == JobStatus.Enqueued
                || jobProperty.Status == JobStatus.Queued
                || jobProperty.Status == JobStatus.Running
                || jobProperty.Status == JobStatus.Scheduled)
            {
                jobProperty = await destinationManager.GetJobAsync(jobProperty.JobId).ConfigureAwait(false);
                await Task.Delay(3000).ConfigureAwait(false);
            }
        }
    }
}
```

**Comment by davilu** [comment] 2019-12-05 03:16
@yukhgcsh Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue.

**Comment by yukhgcsh** [comment] 2019-12-06 02:48
@davilu Thank you. I will do that.

**Comment by abhipsaMisra** [comment] 2020-04-06 16:37
Closing this issue since the customer confirmed that they will create a support ticket to address this issue from the service side.

**Comment by az-iot-builder-01** [comment] 2020-04-06 16:37
@davilu, @yukhgcsh, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-04-06 16:37 UTC
Labels: IoTSDK, area-service
