### ISSUE TITLE
GetTwinAsync() not returning any values except for Properties

### ISSUE THREAD

**Issue by sebader** [Azure/azure-iot-sdk-csharp#418] opened 2018-03-22 09:20 UTC
Hi,
as I already posted on [Stackoverflow](https://stackoverflow.com/questions/49407045/device-twin-not-fully-returned-with-gettwinasync/), I think there is a bug in the .NET Device Client SDK when using the DeviceClient.GetTwinAsync() method:
GetTwinAsync() only returns the Properties field (both Desired and Reported). Any other fields such as DeviceId or Tags are always NULL.

OS: Windows 10 and Windows 2016 tested
Runtime: netcoreapp2.0
Nuget package version: Tested both, 1.7.0 and 1.17.0-preview-001

`var twin = await _deviceClient.GetTwinAsync();`

**Comment by CIPop** [comment] 2018-03-22 22:21
Thanks @seb-dataworks ! 
@zolvarga PTAL.

**Comment by shantanu1singh** [comment] 2018-05-03 20:51
I'm facing the same problem. Using the 1.7.0 package. The device twin has non-null values for properties in IoTHub but the call to GetTwinAsync() returns null for all properties. I tried using both the MQTT and AMQP protocols. I am using certificate (self-signed) based auth to create the device client.

Has this issue been triaged yet?

**Comment by seb-dataworks** [comment] 2018-05-03 20:58
It has been identified as works-as-designed. Look here: https://stackoverflow.com/a/49443889/1537195

**Comment by shantanu1singh** [comment] 2018-05-03 23:05
Thanks for the confirmation @seb-dataworks. I'll look at using the service SDK instead.

**Comment by zolvarga** [comment] 2018-05-29 20:18
Closing as it is by design

**Closed by zolvarga** 2018-05-29 20:18 UTC
Labels: investigation-required
