### ISSUE TITLE
The different message of  DeviceNotFoundException

### ISSUE THREAD

**Issue by meomeo0110** [Azure/azure-iot-sdk-csharp#317] opened 2018-01-03 03:05 UTC
Hi all;

When using the Direct Method, I met the DeviceNotFoundException with different message:

1. Message: Timed out waiting for device to connect
2. Message: NotFound
3. Message: Device unavailable

Can you tell me whether the root cause of these messages same? If not, what is possible root cause?
I searched but I cannot find the document.. 
Sorry for my bad English

OS: Window
Version: Microsoft.Azure.Devices-1.3.0

Thanks,

**Comment by jasmineymlo** [comment] 2018-01-05 18:18
These error messages are populated from the service.  I am checking with the service side folks and will report back when I get the answer.  Thanks.

**Comment by jasmineymlo** [comment] 2018-01-08 21:12
@meomeo0110,  

Message: Timed out waiting for device to connect
==> device is not connected during the specified timeout while method request arrives at the service.
Message: NotFound
==> device is not registered
Message: Device unavailable
==> device initiates disconnect

Thanks.

**Comment by CIPop** [comment] 2018-01-10 00:56
@jasmineymlo @yzhong94 who would know more about these error codes and where should they be documented? (I wasn't able to find the direct method REST documentation.)
Once that is documented, we could add a reference to the messages here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.exceptions.devicenotfoundexception?view=azure-dotnet

**Comment by CIPop** [comment] 2018-01-10 01:44
The REST docs are here: https://docs.microsoft.com/en-us/rest/api/iothub/devicetwinapi/invokedevicemethod

**Comment by yzhong94** [comment] 2018-09-14 19:18
@jlian Should we incorporate this into your troubleshooting doc?  DeviceNotFoundException with different error messages.

**Comment by jlian** [comment] 2018-09-14 19:32
Sure, but I don't know what the likely root cause is? [Here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.exceptions.devicenotfoundexception?view=azure-dotnet) it says 

> The exception that is thrown when an attempt to communicate with a device fails because the given device identifier cannot be found.

So that seems pretty clear cut. But what leads to this happening? @meomeo0110 can you check that you're using direct methods with a device that is registered with IoT Hub?

**Comment by abhipsaMisra** [comment] 2020-04-14 23:13
Should be added as a part of #1185

**Comment by jlian** [comment] 2020-04-14 23:26
By the way, we now have proper docs for error codes emitted by IoT Hub service 

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-404001-devicenotfound

**Comment by abhipsaMisra** [comment] 2020-04-14 23:33
This is great; I'll close this issue then!

**Comment by az-iot-builder-01** [comment] 2020-04-14 23:33
@meomeo0110, @CIPop, @jlian, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-04-14 23:33 UTC
Labels: IoTSDK, area-documentation, enhancement
