### ISSUE TITLE
Timed out trying to create FaultTolerantAmqpObject`1

### ISSUE THREAD

**Issue by traghunathan** [Azure/azure-iot-sdk-csharp#337] opened 2018-01-17 06:30 UTC
- **OS and version used:** <Windows Server 2016> 

- **SDK version used:** <1.6.1> 

# Description of the issue:
Our tool is establishing 2K connections to the Azure IoT. Every 10 minutes once tool sends a message to Azure IoT,where message size is 37B. For random devices, tool receives exception - "Timed out trying to create FaultTolerantAmqpObject`1"

# Code sample exhibiting the issue:

![image](https://user-images.githubusercontent.com/3650020/35028780-c26762ac-fb7d-11e7-98dc-95b0bb31eb2d.png)

# Console log of the issue:

![image](https://user-images.githubusercontent.com/3650020/35028676-3fd34e50-fb7d-11e7-92ce-80826587c7ed.png)

**Comment by CIPop** [comment] 2018-01-19 22:32
Thanks for reporting @traghunathan . 
We need to investigate this further but I think this could be caused by network timeout. We might not be wrapping up the error correctly.

**Comment by ryanzjohnson** [comment] 2018-01-31 21:17
According to [this](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#operation-throttles) you may be hitting a throttling issue on device connection or on device to cloud message sends.

**Comment by craylward** [comment] 2018-03-29 14:48
Hitting this exception when using ServiceClient in .NET Core 2.0 project running on macOS compiled with VS for Mac. Works fine on Windows 7 with VS 2017. 

macOS Sierra (10.12.6)
.NET Core 2.1.101

``System.AggregateException: "One or more errors occurred. (Timed out trying to create FaultTolerantAmqpObject`1)" ---> System.Exception {System.TimeoutException}: "Timed out trying to create FaultTolerantAmqpObject`1"
  at at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__29.MoveNext()
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at System.Threading.Tasks.Task.Wait()\n   at SendC2DMessages.Program.Main(String[] args) in /Users/CharlesA/Azure/Samples/iot-hub-c2d-repro/SendC2DMessages/Program.cs:20
``

[iot-hub-c2d-repro.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1860600/iot-hub-c2d-repro.zip)

**Comment by aderderian** [comment] 2018-09-27 12:14
I am experiencing this issue on .NET 4.7.1 Azure WebJobs (2.2.0). This error occurs once in a 4-5hr period and then my web job can't recover sending messages to the hub until a restart. Is there a way to trace this back to the Event Hub error logs and see if I am hitting a limit?

**Comment by aderderian** [comment] 2019-01-11 03:19
@tiwaripradeep123 I solved this by batch sending messages.

**Comment by prmathur-microsoft** [comment] 2019-01-18 00:12
We have had several changes in SDK since you last posted this message. Please try our latest SDK which has a bunch of fixes around this scenario. And also if you need a workaround please follow what @aderderian  suggested in the comment above. Closing this for now. Feel free to reopen if you still see issues using our 1.19.0 SDK.

**Comment by az-iot-builder-01** [comment] 2019-08-03 00:04
@traghunathan, @CIPop, @craylward, @aderderian, @tiwaripradeep123, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by az-iot-builder-01** 2019-08-03 00:04 UTC
Labels: investigation-required
