### ISSUE TITLE
[QUERY] How to properly acknowledge IoT hub messages

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#3438] opened 2024-03-05 13:58 UTC
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#42405](https://github.com/Azure/azure-sdk-for-net/issues/42405).

### Library name and version

Microsoft.Azure.Devices 1.39.1

## Project overview
In my current project I need to control embedded devices (running the [Azure SDK for C](https://registry.platformio.org/libraries/azure/Azure%20SDK%20for%20C) V1.1.6 on an ESP32, using MQTT) via Azure IoT hub. 
So far I managed to get the Device to Cloud (D2C) and Cloud to Device (C2D) functionality working without issues.

The current communication flow for D2C messages is as follows and works great.

- The device sends a message to the IoT hub via MQTT.
- IoT hub writes directly to a CosmosDB container.
- An Azure function has a CosmosDBTrigger on this container.
- The function decodes the body and stores there result in a different container. (This is done to base64 decode the Body of the message)

The current communication flow for C2D messages is as follows and is giving some issues.

- The front-end writes to a CosmosDB container
- An Azure function has a CosmosDBTrigger on this container.
- The function prepares the message and transmits it to IoT hub.
- IoT hub sends the message to the device via MQTT.

Finally, there is a timed Azure function to parse all the feedback from the IoT hub. The feedback is than used to update the container that contained the original command.
This is a timed function since Azure functions doe not allow the "normal" `while(true)` method due to a maximum runtime of 5 minutes. This method is inspired by [this article](https://medium.com/@florian.ried/how-to-handle-azure-iot-hub-c2d-message-feedback-with-an-azure-function-4b5c4016479d). 

### Program.cs
In the `program.cs` of the Azure functions I registered the IoT hub client as follows
```c#
//Get the connectionstring for the iotHubServiceClient and create an instance
var iotHubConnectionString = Environment.GetEnvironmentVariable("IotHubConnectionString", EnvironmentVariableTarget.Process);
var iotHubServiceClient = ServiceClient.CreateFromConnectionString(iotHubConnectionString);

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
       //Other code
        
        //Add the IotHub Serviceclient
        services.AddSingleton(iotHubServiceClient);
    })
    .Build();
```
### When it started
Before setting the `Ack` to `DeliveryAcknowledgement.Full` I didn't notice this issue (and as far as I can tell it wasn't there).

### Timed function code
The timed function had got the following code
```c#
//Get the feedbackReceiver
var feedbackReceiver = _iotHubServiceClient.GetFeedbackReceiver();

//Create a cancellationToken with a timeout of 1 minute
var timeoutCancellationTokenSource = new CancellationTokenSource(new TimeSpan(0, 1, 0));

//Start waiting for new messages
var message = await feedbackReceiver.ReceiveAsync(timeoutCancellationTokenSource.Token);
_logger.LogInformation("Got {count} status messages from IoT hub", message?.Records.Count() ?? 0);

//Did we get anything
if (message == null)
    //No, abort here
    return;

//Update the statuscode in the database
//[...]

//Complete all the received messages
var cancellationTokenSource = new CancellationTokenSource();
await feedbackReceiver.CompleteAsync(message, cancellationTokenSource.Token);
```

## The issue
The function that sends the message to the IoT hub has the following code.
``` c#
 var message = new Message(Encoding.ASCII.GetBytes(JsonSerializer.Serialize(commands)))
 {
     Ack = DeliveryAcknowledgement.Full,
     MessageId = command.Id,
 };

 await _iotHubServiceClient.SendAsync(deviceId, message);
```
 
So, when the front-end now inserts a new document into the command container the message is correctly transmitted to the device (via MQTT). It seems that the command get's "stuck" somewhere in transmission. My device keeps on receiving duplicate MQTT messages that have been received already.

My timed function also had this issue. It keeps on getting the acknowledgements for the same message over and over.

I would really like to have full acknowledgement sine this is the only way for the operators to get (delayed) feedback.

### Environment

Hosting platform: Azure function app, .NET 8 (LTS), isolated worker model, windows. Runtime version 4.30.0.22097
Microsoft Visual Studio Professional 2022 (64-bit) Version 17.9.2

**Comment by the-programmer** [comment] 2024-03-05 14:03
Thanks for the transfer @jsquire.

I did some more testing and if I disable the timed function the retry seems to be gone. Somehow it seems that requesting the status causes the MQTT messages to be re-transmitted.

**Comment by timtay-microsoft** [comment] 2024-03-11 18:32
Can you share a code snippet of the device-side code that handles receiving the cloud-to-device message?

I believe acknowledging a received cloud-to-device message with the C SDK should be as simple as [this](https://github.com/Azure/azure-iot-sdk-c/blob/e0c0c2c3c14c6ddb0a52ef416fe1dcfd4404c867/iothub_client/samples/iothub_ll_c2d_sample/iothub_ll_c2d_sample.c#L86). If you are already doing this, then 

> My device keeps on receiving duplicate MQTT messages that have been received already.

I don't believe the message acknowledgement full flag is related to this behavior. However, are you seeing the message feedback being received by your service client in the Azure Function? And if so, are you seeing the same feedback message over and over as well?

**Comment by timtay-microsoft** [comment] 2024-03-12 17:06
> Note that I can't find any samples of what the QoS of the IoT hub packets actually are

Cloud to device messages like these should be QoS 1, FYI

Since you are receiving feedback messages, I believe it is safe to assume that your acknowledgement logic on the ESP32 MQTT client side is correct.

Do you see this same repeated delivery of duplicate messages when you set the DeliveryAcknowledgement to PositiveOnly, NegativeOnly, or None?

**Comment by the-programmer** [comment] 2024-03-13 08:23
Today I found what went wrong. It was a bug in the code, not in IoT hub.

The issue was that I mis-understood the `CosmosDBTrigger`. It not only triggers when a record is created (what I assumed) but also when a record is updated.

So when my timed function fired it generated an update into the monitored container. This update, caused the `CosmosDBTrigger` to fire (again) and send out a **new** IoT hub message (that was still linked to the old database entry).

This was the cause of the loop. By checking the updated element the trigger still fires but no messages are generated.

This issue can be closed. Thanks for the help anyway.

**Comment by timtay-microsoft** [comment] 2024-03-13 18:36
Gotcha. Glad to hear the issue was found. I'll close this thread, then.

**Closed by timtay-microsoft** 2024-03-13 18:36 UTC
Labels: question
