### ISSUE TITLE
JobResponse has no error details

### ISSUE THREAD

**Issue by VitaliiBushylo** [Azure/azure-iot-sdk-csharp#2941] opened 2022-11-08 12:51 UTC
Hello,
I'm using `JobClient` to track a job status. In some cases I see that `JobResponse` has the Status Unknown with no other meaningful info inside except of `JobId`.
![image](https://user-images.githubusercontent.com/27290203/200566814-997b9760-9192-49c4-b60a-678a244f053f.png)

However using the Azure CLI I see the error details for the same job id.
![image](https://user-images.githubusercontent.com/27290203/200567416-ce8852cd-efc2-4ea9-a9c6-985468165816.png)

My question is how to retrieve the error details (similar to Azure CLI) from `JobResponse`?

Thank you!

**Comment by tmahmood-microsoft** [comment] 2022-12-19 20:53
Hi @VitaliiBushylo thank you for bringing this to our attention. The issue is related to a bug in the `[Jobs API](https://learn.microsoft.com/en-us/rest/api/iothub/service/jobs/get-scheduled-job#jobresponse)`
I have brought this to the specific team's attention. However, this is a breaking change for other customers so hopefully it will be fixed in their next release.

Please let me know if you have any more questions or concerns.

**Comment by VitaliiBushylo** [comment] 2022-12-20 14:17
Hi @tmahmood-microsoft thank you for the clarification.
Looking forward for new release!

**Closed** 2022-12-20 14:18 UTC
Labels: question, IoTSDK
