### ISSUE TITLE
Device job query by status of `Completed` or `Cancelled' will fail with InternalServerError

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-csharp#257] opened 2017-12-01 08:22 UTC
If the the Device Job query include status value with uppercase string of `Completed` and `Canceled`, it will fail and throw `Microsoft.Azure.Devices.Common.Exceptions.ServerErrorException`:
e.g.
```
var conn = "...";
var queryString = "select * from devices.jobs where devices.jobs.status = 'Completed'";   // failed
//var queryString = "select * from devices.jobs where devices.jobs.status = 'completed'";   // passed
//var queryString = "select * from devices.jobs where devices.jobs.status = 'Canceled'";   // failed
//var queryString = "select * from devices.jobs where devices.jobs.status = 'canceled'";   // passed
Query query = RegistryManager.CreateFromConnectionString(conn).CreateQuery(queryString);
await query.GetNextAsDeviceJobAsync()
```
The other values works: `Pending`  or `pending`, `Scheduled` or `scheduled`, `Running` or `running`, `Failed` or `failed`.

BTW, the query string also failed in IotHub blade on Azure portal.

**Comment by CIPop** [comment] 2017-12-07 20:33
@zhang-hua According to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-query-language only the property names are case insensitive. There isn't anything specifying that values (such as `completed` or `canceled`) should be case insensitive.

You may need to use `UPPER()` or `LOWER()` if case insensitive searches are required.

Closing as by design since this failed in the Azure Portal as well.
/cc: @tameraw

**Closed by CIPop** 2017-12-07 20:33 UTC

**Comment by zhang-hua** [comment] 2017-12-08 02:03
@CIPop thanks for your feedback!
