### ISSUE TITLE
ModuleClient with MQTT TCP does not re-connect if the connection is dropped by the server

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#558] opened 2018-07-20 21:40 UTC
OS: Ubuntu 16.04, x64
.Net Core 2.1
Device: Azure VM
SDK Version: 1.17.0

## Description of the issue:
When a module uses the ModuleClient with MQTT Tcp connection to connect to the EdgeHub, the server (EdgeHub) drops the connection when it needs a new token. The expectation is that the ModuleClient will re-open this connection to the server and continue the operation. 

However, every so often, the ModuleClient will never re-open the connection to the EdgeHub, which leaves a stranded module which doesn't do anything. This happens more frequently when the Module is only Receiving messages. 
The ModuleClient does not even throw any exceptions, it simply loses the connection to the EdgeHub and stands still, not doing anything. 

Repro steps - 
- Create a module that uses the ModuleClient to connect to EdgeHub over MQTT and set the callback to receive messages. 
- Deploy the module to an Edge device, such that it receives messages from some other module/device.
- For some time the module receives successfully. But after a few token refresh cycles (2-3 hours or so), it stops receiving messages.

**Comment by CIPop** [comment] 2018-07-30 23:09
Thanks @varunpuranik  for reporting this!
We'll need to set up a long running test/repro for properly testing token refresh over amqp and mqtt.

**Comment by pavele** [comment] 2018-08-03 09:41
This should be considered as a blocker since this is already in GA. Not having long running tests for iot "solution" is nothing but ridiculous.

**Comment by CIPop** [comment] 2018-08-03 21:30
I was able to repro this using the MQTT fault injection tests which appear to have been disabled for a while (meaning that this is probably not working for DeviceClient to IoT Hub either).
@varunpuranik Would restarting the ModuleClient from time to time be a viable workaround for MQTT until we fix the bug?

**Comment by varunpuranik** [comment] 2018-08-04 23:59
@CIPop If the module died and was restarted automatically by EdgeAgent, this might have been acceptable. Unfortunately, this is not the case. The Module simply hangs after disconnecting, doing nothing. A user needs to notice that this has happened, and then restart the module. I doubt if that will be acceptable to many customers.

**Comment by jason-e-gross** [comment] 2018-08-05 01:25
I'd say absolutely not.  Isn't that the point of the agent, and the settings in the portal - to restart modules based on those settings (healthy, etc).   The point of the edge hub to keep the channels open and alive.

If we have to watch the health of our module apps, and babysit the pipeline to the hub - why edge at all, then?

________________________________

**Comment by CIPop** [comment] 2018-08-06 21:55
I've started investigating and found that most of the tests for MQTT and AMQP recovery have been disabled a long time ago. After re-enabling them I do see they are failing to reconnect after various types of faults.
The good part is that we have a consistent repro, without Edge being involved. The bad part is that we don't know when the behavior got broken (or if it ever worked well). I'll update this thread and the AMQP equivalent once I have some idea why this is failing.

**Comment by myagley** [comment] 2018-08-10 17:31
We believe this issue has been fixed in DotNetty here: https://github.com/Azure/DotNetty/pull/413

We need to cut a new release of DotNetty and update the SDK.

**Comment by myagley** [comment] 2018-08-18 03:01
Version 1.18.0 of the SDK has been released to nuget.org. Please give it a try.

**Comment by varunpuranik** [comment] 2018-08-20 21:00
This works now with SDK version 1.18.0. Closing this issue.

**Comment by az-iot-builder-01** [comment] 2018-08-20 21:00
@pavele, @jason-e-gross, @myagley, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by CIPop** [comment] 2018-08-23 03:29
Reopening as we still have TODO items in our E2E tests that need to be investigated.

**Comment by CIPop** [comment] 2018-08-27 23:31
So far, the tests that were disabled were failing because of issues on the service-side fault injection support. 
The tests try to send the fault injection request message but never receive a PUBACK (the `delayInSec` parameter is ignored and the connection is reset immediately). This caused the tests to enter an infinite loop (probably the reason they were disabled in the first place).

I'm working on fixing all test flavors but so far all connections seem to recover without any SDK changes.

**Comment by CIPop** [comment] 2018-10-15 18:11
I was able to re-enable all Telemetry send/receive fault recovery tests in our CI system but not the Command and Twin.
Since I'm seeing some random failures when these are enabled, I expect that to be the case for Edge. We are still investigating these with highest priority and we've also decided to block further PRs until we get all our E2E fault injection tests enabled to ensure no further regressions.

**Comment by sebader** [comment] 2018-12-05 11:54
is there any update on this? I have a customer stating they are running into this - and it sounds here like it is still expected to happen on Edge

**Comment by slimbrd** [comment] 2018-12-06 15:36
My team is also being blocked by this issue.  Updates are appreciated.

**Comment by sebader** [comment] 2019-01-10 11:51
@CIPop should this issue now be fully fixed with the referenced PR - and Microsoft.Azure.Devices.Client 1.19.0?

**Comment by prmathur-microsoft** [comment] 2019-01-10 20:43
Can you give it a try and let us know if you still see issues.

**Comment by sebader** [comment] 2019-01-10 21:02
I've already updated and am testing this. I just wanted to check if this is actually something that should have been fully solved - since the PR mentions that more fixes/changes are to come.

**Comment by prmathur-microsoft** [comment] 2019-01-18 00:17
Our current release addresses a huge set of fixes. But yes, we still have few more coming soon on the AMQP. We are working on redesigning AMQP to address lot of issues on that front as well.

In the meantime, if you can let us know if our 1.19.0 release resolved your issues or if you still see problem ?

**Comment by vinagesh** [comment] 2020-12-07 20:21
I tried this and cannot repro it anymore. Closing due to inactivity. Please reopen if you see any issues.

**Closed by vinagesh** 2020-12-07 20:21 UTC
Labels: IoTSDK, area-edge, bug, investigation-required
