### ISSUE TITLE
Multiple parallel connections to IoT Hub for single device Id

### ISSUE THREAD

**Issue by hathind-ms** [Azure/azure-iot-sdk-csharp#699] opened 2018-11-07 06:09 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

While testing Device Simulation with large number of devices (> 200K), we noticed that devices are creating multiple parallel connections to IoT Hub. We have verified that these multiple connection requests do not originate from simulation client. It seems like SDK is generating these parallel requests. These requests cause additional load on Hub resulting in CPU spikes.

Protocol: AMQP 

For more details contact IoT Device Simulation Team.

**Comment by trbenning** [comment] 2019-02-05 23:33
We're seeing this from the device side of things fairly often. While our device app is running, we use `netstat -ano | grep 5671`, and we can usually see multiple connections despite having only one DeviceClient instantiated.

It doesn't happen every time, so I'm still working on creating a code snippet that reliably reproduces the behavior. One scenario where it does happen every time is when we attempt to connect a device id that has not yet been registered. In those cases, we dispose of the created `DeviceClient`, and call a registration API. When we reconnect after registration with a new instance of `DeviceClient`, we always have at least 2 connections open in the `ESTABLISHED` state.

This code demonstrates that behavior:
```csharp
async Task Main()
{
    var cert = new X509Certificate2(CertPath);
    using(var deviceClient = DeviceClient.Create(HubHost, new DeviceAuthenticationWithX509Certificate("NOT-REGISTERED", cert)))
    {
        try
        {
            await deviceClient.OpenAsync();
            Console.WriteLine("Device Client Opened.");
        }
        catch(Exception ex)
        {
            Console.WriteLine($"Failed to open Device Client: {ex.Message}");
            await deviceClient.CloseAsync();
        }
    }

    // Run 'netstat -ano | grep 5671' during this wait. 
    // The connection created during DeviceClient.OpenAsync never leaves the "ESTABLISHED" state
    await Task.Delay(TimeSpan.FromSeconds(30));
}
```

**Comment by prmathur-microsoft** [comment] 2019-02-06 06:43
Which version of SDK are you using. Can you retry above scenario with 1.19.0?

**Comment by trbenning** [comment] 2019-02-06 15:05
That scenario was done with 1.19.0

**Comment by prmathur-microsoft** [comment] 2019-02-08 19:29
We are very close to having a new release of C# SDK which should address CPU usage concerns. Post that release we expect this issue to be resolved. Targeting to release it end of feb.

**Comment by anhashia** [comment] 2019-04-15 18:02
Fixed in  latest release **1.20.0**. Unable to reproduce it on 1.20.0.

**Comment by jenoola** [comment] 2019-04-15 18:09
Closing per @anhashia comment

**Comment by az-iot-builder-01** [comment] 2019-04-15 18:09
@hathind-ms, @trbenning, @prmathur-microsoft, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by jenoola** 2019-04-15 18:09 UTC
Labels: bug, fix-checked-in
