### ISSUE TITLE
RegistryManager RemoveModuleAsync not removing modules from edge device

### ISSUE THREAD

**Issue by saikovvuri** [Azure/azure-iot-sdk-csharp#923] opened 2019-04-25 05:53 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10 Enterprise
- **Application's .NET Target Framework :** <NETVERSION> 
netcoreapp2.2
- **Device:** <DEVICETYPE> 
Laptop
- **SDK version used:** <VERSION> 
Microsoft.Azure.Devices (1.17.3)
## Description of the issue:

We have a custom module running on an edge device.  We are trying to use the IOT Hub Service SDK to remove the module but not successful. No exceptions are being thrown. 
## Code sample exhibiting the issue:

RegistryManager registryManager =
     RegistryManager.CreateFromConnectionString(connectionString);

            try
            {
                var existingModule = await registryManager.GetModuleAsync(deviceID, moduleID).ConfigureAwait(false);
                var module = new Module(deviceID, moduleID);
                module.ETag = existingModule.ETag;

                await registryManager.RemoveModuleAsync(module);
            }

**Comment by saikovvuri** [comment] 2019-04-28 11:29
I also tried using the REST API and same behavior
DELETE https://{{hubname}}.azure-devices.net/devices/{{deviceId}}/modules/{{moduleId}}?api-version=2018-06-30

GOT a 204 

However I still see the custom module listed on the portal as well running on the edge device

Question is that if removing module using either the SDK or REST API not the same things as deleting the module from [Set Modules] and applying an updated deployment

**Comment by prmathur-microsoft** [comment] 2019-05-10 22:50
@varunpuranik  - Any suggestions from edge side?

**Comment by varunpuranik** [comment] 2019-06-18 19:09
@saikovvuri - This is by design. 
If you have the Edge runtime installed on an edge device, then the identities of the modules deployed to that device are expected to be owned by the Edge runtime. The edge runtime will create/update the identity when the module is deployed, and remove it when the module is removed from the deployment. To identify the module identities managed by the edge runtime, the module object has a property ManagedBy which is set to "IotEdge". 

So, what is happening in this case, is that soon after you delete the identity of the module, the EdgeAgent creates it again (possibly after the module fails)

Also, please note - deleting a module identity does not delete the module from the deployment. The only way to do that is to do another deployment (SetModules from the portal), and remove that module form the deployment. 

If you are trying to create/delete identities of modules _which are not in the deployment_, then the edge runtime will not interfere with the operation and you should be able to create/delete them as you please.

**Comment by prmathur-microsoft** [comment] 2019-07-10 20:29
Closing as per the comment from Varun above. Feel free to reopen if you have further issues.

**Comment by az-iot-builder-01** [comment] 2019-07-10 20:29
@saikovvuri, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-07-10 20:29 UTC
Labels: investigation-required
