### ISSUE TITLE
C# SDK File Upload with x509 Cert Fails

### ISSUE THREAD

**Issue by adamkjonesmesh** [Azure/azure-iot-sdk-csharp#541] opened 2018-07-02 17:00 UTC
I am trying to upload a file to IoT hub using x.509 certs but am receiving an exception every time. The exception is "Object reference not set to the instance of an object". The inner exception is below:

StackTrace [string]:" at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Devices.Client.IAuthorizationProvider.GetPasswordAsync()\r\n at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func3 modifyRequestMessageAsync, Func2 isSuccessful, Func3 processResponseMessageAsync, IDictionary2 errorMappingOverrides, CancellationToken cancellationToken)\r\n at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary2 errorMappingOverrides, IDictionary2 customHeaders, CancellationToken cancellationToken)\r\n at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.UploadToBlobAsync(String blobName, Stream source)"

I am using Microsoft.Azure.Devices.Client 1.7.2.  Is file uploading using x.509 still not supported?

**Comment by KasperHoldum** [comment] 2018-07-04 12:57
I experience the same issue. It was pointed out earlier in #259 and closed for some reason.

**Comment by CIPop** [comment] 2018-07-11 01:11
Closing as duplicate of #259.

**Closed by CIPop** 2018-07-11 01:11 UTC
Labels: bug
