### ISSUE TITLE
On which operation is the RetryPolicy used? 

### ISSUE THREAD

**Issue by msjonathan** [Azure/azure-iot-sdk-csharp#2257] opened 2021-12-09 09:05 UTC
Hej, 
Currently we are load testing IoTHub DeviceTwin updates with the .Net SDK - 30.000K simulated devices. 

In the docs https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.setretrypolicy?view=azure-dotnet it's stated that there is a default Retry policy on the DeviceClient on operation retries - a backoffone. 
The term Operation Retries is a bit confusing for me. 

Our tests seems to point us that the retry policy is not used for the "_UpdateReportedPropertiesAsync_" method - is it correct to assume this retry policy is only used for the connection between Device and IoTHub. 

And If we would like to handle the Http status code 429 that we need to handle the retry ourself? 

Thanks

Jonathan

**Comment by azabbasi** [comment] 2021-12-13 19:34
@msjonathan 

The retry policy is also used for exception handling and the default retry policy on the device client will retry on transient errors. 429 is also considered a transient error and so the device client will retry the operation on 429 status code.

It may be worth mentioning that non of the device twin operations are supported on HTTP protocol, you have to either use MQTT or AMQP for them.

You mention that your test point to the fact that UpdateReportedPropertiesAsync doesn't use a retry policy, can you elaborate a bit further? we can certainly look into that.

**Comment by msjonathan** [comment] 2021-12-14 12:12
Hej @azabbasi 

Partial code - the DeviceClient is  communicating over MQTTT, we generate 10.000 clients as a test. 

```
 var client = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Mqtt, new ClientOptions() {  });
 await client.OpenAsync(); 
```
Without setting is explicit - we expect the ExponentialBackoff 
```
 await clientCustom.Client.UpdateReportedPropertiesAsync(reportedProperties);`
```

Even when we set it explicit 

```
 client.SetRetryPolicy(new ExponentialBackoff(2, TimeSpan.FromSeconds(420), TimeSpan.FromSeconds(1800), TimeSpan.FromSeconds(60)));
 await clientCustom.Client.UpdateReportedPropertiesAsync(reportedProperties);`
```

In both cases we have the exact same outcome once the http status code 429 is returned, the client stops and does not do a retry. e.g. in the Azure metrics we see than 10.000 Device Twin updates from device and not a single retry (failed and succes metrics). Therefor we think this RetryPolicy is not used for the _UpdateReportedPropertiesAsync_ method

**Comment by azabbasi** [comment] 2021-12-20 17:39
@msjonathan 
While we are looking into this, it would be abundantly helpful if you could capture the SDK logs and send them our way. 
https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs

**Comment by azabbasi** [comment] 2022-01-11 00:40
@msjonathan
Hello, 
Unfortunately, we have not yet been able to reproduce your issue on our side. It would be really helpful if you could provide the following information for us:
* The SDK logs as requested previously
* The exception stack trace
* Whether or not you get the same result if you change your protocol to AMQP

Please let us know.
Thank you

**Comment by azabbasi** [comment] 2022-01-31 18:00
Closing the issue since it has been over 3 weeks since we got a response, feel free to reopen the issue if you are still blocked on this.

**Closed by azabbasi** 2022-01-31 18:00 UTC
Labels: question, IoTSDK

**Comment by brycewang-microsoft** [comment] 2022-08-04 17:21
FYI, we just [released ](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-07-26)the latest device client package in **v1.41.1** to include the fix.
