### ISSUE TITLE
Retry logic behavior changed when network is down - it causes regression in edgeHub

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1079] opened 2019-10-02 19:35 UTC
EdgeHub implements its own logic to detect network failures. It issues a
client.UpdateReportedPropertiesAsync(new TwinCollection()) call, and if it timeouts then adjusts its internal state for disconnected network.

Investigating a reported bug by a client it turned out that the call above does not timeout anymore. It appears that the following change removed the timeout logic, which used to cancel the ongoing operation after 4 minutes (configurable)

https://github.com/Azure/azure-iot-sdk-csharp/commit/042ad252baf7f2919beb0e789c87ecfc9a7c7e02#diff-dda2d39be2b8400586351da31fdbb71b

**Comment by CIPop** [comment] 2019-10-04 21:55
This is caused by our stack retrying if any subscription has been made. 
During internal retry (RetryDelegatingHandler) we grab the `_handlerLock` which is preventing any operations from changing DeviceClient internal state.

The fix for this would be to pass down the cancellation token within the `_handlerLock.WaitAsync()` and test that there are no corner cases where this could create state transition problems.

/cc @davilu @prmathur-microsoft

**Comment by CIPop** [comment] 2019-10-04 21:56
Temporary workaround, not elegant, would be to implement your own timeout and dispose the client after that elapsed.
Disposing / CloseAsync should terminate all pending operations.

**Comment by davilu** [comment] 2019-12-18 05:05
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment] 2019-12-18 05:05
@CIPop, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-18 05:05 UTC
Labels: bug, fix-checked-in
