### ISSUE TITLE
MethodRequest.ResponseTimeout value never passed to called device method.

### ISSUE THREAD

**Issue by lanatmwan** [Azure/azure-iot-sdk-csharp#1161] opened 2019-12-18 00:47 UTC
From the service client, you can define a specific response timeout when you call a device method:

`
var method  = new CloudToDeviceMethod("OnMyAsync", responseTimeout, connectTimeout);
var result      = await serviceClient.InvokeDeviceMethodAsync(deviceId, method, cancellationToken).ConfigureAwait(false);
`

AFAIK, the timeout is triggered appropriately if  "OnMyAsync" takes too long but I'd like my function to be able to be able to cleanly cancel any async tasks it started by using a cancellation token with a slightly shorter timeout than what the MethodRequest had, similar too:

`
private static async Task<MethodResponse> OnEnablePlugins(MethodRequest methodRequest, object userContext)
{
    var timeout = methodRequest.ResponseTimeout - TimeSpan.FromMilliseconds(50); 
    using var tokenSource = new CancellationTokenSource(timeout);
    await Call1Async(cancellationToken: tokenSource.Token).ConfigureAwait(false);
    await Call2Async(cancellationToken: tokenSource.Token).ConfigureAwait(false);
}
` 

Unfortunately, methodRequest.ResponseTimeout is always null though so you don't get the opportunity to do any cleanup.

This is with Microsoft.Azure.Devices.Client 1.20.1

**Comment by davilu** [comment] 2019-12-18 05:02
@lanatmwan Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Neither `connectionTimeout` nor  `responseTimeout` is not passed to device side. They are used by service internally to figure out how long to wait for device to connect and device to response. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue.

**Comment by timtay-microsoft** [comment] 2020-04-14 20:02
Closing this issue because it is by design that the Response timeout and connection timeout are used by the service, but aren't given to the device

**Comment by az-iot-builder-01** [comment] 2020-04-14 20:02
@lanatmwan, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-04-14 20:02 UTC
Labels: IoTSDK, area-service
