### ISSUE TITLE
DotNetty version conflict between Microsoft.Azure.Devices.Client.NetStandard.csproj and Microsoft.Azure.Devices.Client.nuspec

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#282] opened 2017-12-11 21:43 UTC
Microsoft.Azure.Devices.Client.nuspec references DotNetty version 0.4.6
<dependency id="DotNetty.Codecs.Mqtt" version="0.4.6" />
<dependency id="DotNetty.Handlers" version="0.4.6" />

Where as Microsoft.Azure.Devices.Client.NetStandard.csproj references Dotnetty version 0.4.7
<PackageReference Include="DotNetty.Codecs.Mqtt" Version="0.4.7" />
<PackageReference Include="DotNetty.Handlers" Version="0.4.7" />

Because of this, if I build a nuget package using the nuspec file, it doesn't work correctly (it complains that Dotnetty version 0.4.7 not found).

**Comment by CIPop** [comment] 2017-12-12 23:13
Thanks @varunpuranik for reporting. This is a duplicate of #275.

**Closed by CIPop** 2017-12-12 23:13 UTC
Labels: bug
