### ISSUE TITLE
[Bug Report] - DeviceClient - GetFileUploadSasUriAsync - ArgumentException/BadRequest error (and not listed error code)

### ISSUE THREAD

**Issue by jonmikeli** [Azure/azure-iot-sdk-csharp#2936] opened 2022-11-05 19:57 UTC
# Context

- **OS, version, SKU and CPU architecture used:** <VERSION> MAUI, Android, Pixel 5
- **Application's .NET Target Framework :** <NETVERSION> .NET 6 (MAUI)
- **Device:** <DEVICETYPE> Android API v31
- **SDK version used:** <VERSION> 
Microsoft.Azure.Device.Client (1.41.2)

## Description of the issue
GetFileUploadSasUriAsync() raises a System.ArgumentException (BadRequest exception at message level).
No InnerException or any other information available.
The error code is not listed among the listed errors in the documentation:
https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes

## Code sample exhibiting the issue
var fileUploadSasUriRequest = new FileUploadSasUriRequest
{
       BlobName = targetFileName
};

FileUploadSasUriResponse sasUri = await _deviceClient.GetFileUploadSasUriAsync(fileUploadSasUriRequest);

## Exception
Exception:
{"Message":"{\"errorCode\":400022,\"trackingId\":\"f4bea9b88be24e55ba05e2a3a54cd838-G:0-TimeStamp:11/05/2022 19:50:10\",\"message\":\"BadRequest\",\"timestampUtc\":\"2022-11-05T19:50:10.6226826Z\"}","ExceptionMessage":""}

Stack trace:
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__19`2[[Microsoft.Azure.Devices.Client.Transport.FileUploadSasUriRequest, Microsoft.Azure.Devices.Client, Version=1.41.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.Azure.Devices.Client.Transport.FileUploadSasUriResponse, Microsoft.Azure.Devices.Client, Version=1.41.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.GetFileUploadSasUriAsync(FileUploadSasUriRequest request, CancellationToken cancellationToken)
   at IoT.Device.Mobile.Services.DeviceSimulatorService.<FileUploadAsync>d__21`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in D:\...

**Comment by drwill-ms** [comment] 2022-11-07 19:05
Hi @jonmikeli 

That is a terrible error message. I'm sorry that happened. I will check with our service team to get that error message improved.

That said, I look at the logs (because you included the trackingId) and found something that I hope is helpful.

> ErrorCode: InvalidStorageEndpointProperty
> Message: Storage endpoint property ContainerName is invalid
> Timestamp: 11/05/2022 19:50:10
> Tracking ID: f4bea9b88be24e55ba05e2a3a54cd838-G:0-TimeStamp:11/05/2022 19:50:10

Does that help? What is the name of your storage container that is configured on the hub for file upload operations?

Regards,
David

**Comment by jonmikeli** [comment] 2022-11-07 23:13
Hi @drwill-ms ,

Thank you for your answer and your help.
It helped me quite a lot. Actually, the issue did not come from the storage container settings but your message allowed me to put me in the right direction (in the end, I was using a bad DPS and the devices were provisioned at the wrong IoT Hubs, with no file upload feature).

Is there a public way to use the tracking ID as you did?

Kind regards,

**Comment by drwill-ms** [comment] 2022-11-08 00:38
Well, I'm glad you figured out the root cause, even if it wasn't what we thought it might be.

The tracking Id is specifically for when working with MS support or the service teams, so they can quickly get to the right service logs. They are not available publicly.

Is it okay if we close this issue then?

**Closed** 2022-11-08 06:48 UTC
Labels: bug, IoTSDK
