### ISSUE TITLE
AMQP multiplexing causes significant delay restoring brokent network connection

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1166] opened 2019-12-31 23:43 UTC
If AMQP connection pooling is on, then when the network goes off, then later comes back, apparently lower layers still want to use and old "dead" connection even when a new is opened (with OpenAsync()). It keeps happening until the normal TCP timeout finally signals that the TCP connection is dead (this is ~15 minutes on Linux - that is when the library comes back with an exception). 
The effect is that when the connection goes down for ~5 minutes (long enough for IoT Hub to drop the connection from the other side) and comes back, the client needs to wait ~15 until it can open a new connection. This delays  edgeHub ability to connect back. 
If multiplexing is turned off, then this is not an issue: if the client opens a connection after the network comes back, it would work immediately.

**Comment by ancaantochi** [comment] 2020-01-24 21:49
The issue is caused by the old connection being reused even if it is broken. To avoid this issue I make sure that all clients are disposed before trying to open a new connection. If OpenAsync fails it still needs to call Dispose to make sure it gets cleaned.

**Comment by davilu** [comment] 2020-02-13 22:20
There were two causes for this issue: 

If AMQP connection pooling is on
1. Device client need to be disposed once it's no longer used. Otherwise the shared AMQP connection won't be cleaned up.
2. Introduced device side `AMQP` heartbeat to detect connection lost.

Close since fixed in release 1.22.0.

**Comment by az-iot-builder-01** [comment] 2020-02-13 22:20
@ancaantochi, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-02-13 22:20 UTC
Labels: area-edge, fix-checked-in
