### ISSUE TITLE
Microsoft.azure.devices.client supported by Mono project

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-sdk-csharp#80] opened 2017-04-05 13:32 UTC
Is Microsoft.azure.devices.client supported by Mono project?

**Comment by tameraw** [comment] 2017-04-05 17:05
@mtheolog - Not as of yet. Work is in progress to provide that support.

**Comment by tameraw** [comment] 2017-06-12 04:02
@mtheolog - Please try out our latest release.

**Comment by trbenning** [comment] 2017-06-12 16:26
I've been using [this code](https://gist.github.com/trbenning/736bbeb92aa63603a0593960a65fcfb6) to test mono support, and it's still not working with the 1.2.12 release. I don't get any errors. The messages just don't show up in IoT Hub.

**Comment by tameraw** [comment] 2017-10-18 17:18
Try with NetStandard1.3 from our Nuget package on mono using our latest version. Are you using Xamarin? Or Mono on Linux? And is it possible for you to move to .NetCore?

**Comment by CIPop** [comment] 2017-10-19 21:58
We're tracking multiple issues caused by the PCL libraries. The decision was to remove the PCL binary from our next release.
As a workaround, please try adding a new netstandard1.3 (or 2.0) library to your project and reference it from the Mono application. Using the SDK within this library should work.
We also recommend, if your platform allows, switching to [.Net Core ](https://www.microsoft.com/net/download/core) instead of Mono.

Tentatively closing this as a duplicate of #138 .

**Closed by CIPop** 2017-10-19 21:58 UTC
Labels: enhancement, question
