### ISSUE TITLE
Client Throws Uncatchable Null Reference Exception in UWP Application

### ISSUE THREAD

**Issue by nrgonzalez777** [Azure/azure-iot-sdk-csharp#75] opened 2017-03-22 21:32 UTC
Hello,

I have a project in which I am using the C# Azure IoT SDK (v 1.2.5) in a Win 10 IoT UWP application to send messages to an IoT hub via the AMQP protocol. I basically start a long-running task that creates a client, pops messages off of a queue,  and sends those messages up to my hub. In the case of connection issues, the task is supposed to intermittently close the current client and try to open a new one until connection has been re-established. This loop runs indefinitely.

Unfortunately I'm running into an issue where the SDK will throw an uncatchable null reference exception that crashes my application. This occurs when trying to establish a new client connection after detecting a connection loss . I've gathered the following pieces of information about this error:

1. This only occurs in UWP applications. A normal C# console app does not have the same problem.
2. This only occurs when using the AMQP protocol. If the protocol is switched to HTTP1 the issue no longer occurs.

In order to showcase the problem I've included a zip file with two projects: a .NET 4.5.2 console app and a UWP 10 app. Both of these apps run a version of my long-running task and a way to send messages to a hub (the credentials of which you would have to set). If you build and run these applications, these are the results you should see:

Console Application:

1. Upon launch, application starts up IoT hub task.
2. Type a string into the console and press enter. You should see a console write saying the send was successful.
3. Turn off the internet on your computer (I usually just disable the ethernet connection).
4. Send another message using the console.
5. If you debug the task loop, you should see the thread await on the SendEventsBatchAsync call and not return until the internet connection has successfully been restored. The app does not crash.

UWP Application:

1. Upon launch, application starts up IoT hub task.
2. Type a string into the text box and press enter. You should see a Debug statement in your output window saying the send was successful.
3. Turn off the internet on your computer.
4. Send another message using the text box.
5. In your output, you should see the following exception log: "Exception thrown when calling SendEventBatchAsync: Microsoft.Azure.Devices.Client.Exceptions.IotHubClientTransientException: Transient error occured, please retry. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled."
6. Depending on how long it takes for the uncaught exception to get thrown, you may see logs output when the task attempts to recreate the client while there is still no internet connectivity: "Error creating device client: {0} --> System.InvalidOperationException: A method was called at an unexpected time. (Excep_FromHResult 0x8000000E)"
7. Eventually (usually within 1 minute) the application will crash due to an exception that is not catchable by the try/catch blocks. Visual Studio should present the error like this:
![image](https://cloud.githubusercontent.com/assets/955534/24221508/8452c022-0f1c-11e7-8c79-1e88e804c22b.png)

8. If you run this sample using the HTTP protocol, the crash will not occur.

Let me know if you need any clarification or other assistance.

[DeviceClientCrashTests.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/862890/DeviceClientCrashTests.zip)

**Comment by ScottRoutley** [comment] 2017-03-27 05:05
Reading this issue makes me believe that I may be battling the same or a very similar issue of an "Uncatchable Excpetion"

I have not been able to isolate the problem as clearly as @nrgonzalez777, however my app crashes with no exception in my logs.  The timing of the crash seemingly to be random. (which could be explained by network issues.)
I have observed  my app crash 5 minutes into a run, or last as long as 4 days before crashing.   

I can deploy this to 4 different Raspberry Pi's and i'll get 4 totally different crash times.


Based on @nrgonzalez777 observation that the root cause is a network problem I ran the following test.

1) Started my application
2) Disconnected the CAT5 network connection
3) Noticed that it was able to recover using WiFi, I logged into the web client and disconnected the OS from wifi
4) Waited about 3 minutes
5) Re-connected the CAT5 and checked my logs.
6) Sure as shit, the app crashed with no exception. 

I have attached a copy of the log in this post in hopes that it might help out in some way.   I did add some comments to the log to assist in the interpretation of the problem.

[Log_2017_03_27.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/871514/Log_2017_03_27.txt)

**Comment by arturl** [comment] 2017-03-27 22:00
This is a bug in Microsoft.Azure.Amqp library that was fixed late last year. Please update Microsoft.Azure.Amqp package in your project to 2.0.4 to solve the problem. 

I'll open a separate bug to include the latest Microsoft.Azure.Amqp in the C# Azure IoT SDK.

@nrgonzalez777 and @ScottRoutley, let me know if this solves your problem. I'll keep the issue open until then.

**Comment by nrgonzalez777** [comment] 2017-03-28 00:45
@arturl I updated the test UWP application to the new library and that stopped the issue. I will test this on a Pi later in the week to confirm the fix on that platform.

**Comment by arturl** [comment] 2017-03-28 00:47
Thanks @nrgonzalez777. Closing now. Please reactivate if your Pi shows the problem.

**Closed by arturl** 2017-03-28 00:47 UTC
Labels: investigation-required
