### ISSUE TITLE
Device Twin lastActivityTime is always DateTime default value when using RegistryManager

### ISSUE THREAD

**Issue by michaellindberg** [Azure/azure-iot-sdk-csharp#1536] opened 2020-08-25 09:20 UTC
# Context

- **OS** macOs Catalina 10.15.6
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices version 1.22.0 and 1.27.1-preview-002

## Description of the issue
When using **RegistryManager CreateQuery** the returned device twin(s) always has the lastActivityTime set to DateTime default value "0001-01-01T00:00:00Z". 
The lastActivityTime is set correctly in the Device Twin on IoT Hub. 
Using the Query explorer in Azure IoT Hub also returns lastActivityTime = "0001-01-01T00:00:00Z". 

## Code sample exhibiting the issue
 ```csharp
using System;
using Microsoft.Azure.Devices;
using Newtonsoft.Json;

namespace RegistryManagerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            RegistryManager registryManager = RegistryManager.CreateFromConnectionString("<connection string>");

            var query = registryManager.CreateQuery("SELECT * FROM devices");
            var result = query.GetNextAsTwinAsync().Result;

            Console.WriteLine(JsonConvert.SerializeObject(result));
        }
    }
}
```

**Comment by abhipsaMisra** [comment] 2020-08-25 16:13
I am unable to reproduce this issue at my end. For a device twin, I am able to see the twin data being retrieved correctly:

```json
{
  "deviceId": "xdevice1",
  "etag": "AAAAAAAAAAE=",
  "deviceEtag": "Mjg1NjkzMTU0",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00Z",
  "connectionState": "Disconnected",
  **"lastActivityTime": "2020-06-01T21:40:17.1844931Z",**
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "selfSigned",
  "x509Thumbprint": {
    "primaryThumbprint": "<sign>",
    "secondaryThumbprint": "<sign>"
  },
  "version": 2,
  "properties": {
    "desired": {
      "$metadata": {
        "$lastUpdated": "2020-06-01T21:40:13.6119031Z"
      },
      "$version": 1
    },
    "reported": {
      "$metadata": {
        "$lastUpdated": "2020-06-01T21:40:13.6119031Z"
      },
      "$version": 1
    }
  },
  "capabilities": {
    "iotEdge": false
  }
}
```
![image](https://user-images.githubusercontent.com/22563986/91199332-9a914400-e6b2-11ea-8605-4689e2a572ea.png)

Could you share the twin data that you get from the portal vs what is retrieved by the SDK. (make sure that any confidential data is not posted on public channel - device keys, hub name etc.)
If you would like to share the data privately, you can create a [support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by michaellindberg** [comment] 2020-08-25 20:12
Hi @abhipsaMisra,

Thank you for your reply.

I can see the correct lastActivityTime when looking at the Device Twin directly in IoT Hub, but unfortunately not when using the RegistryManager (It doesn't work for me in the IoT Hub Query Explorer either)

The IoT Hub is an S1 running in region westeurope.

The images below are:
1. Device Twin viewed in IoT Hub
2. Device query in IoT Hub Query Explorer
3. Result from RegistryManager with query SELECT  * FROM devices

<img width="565" alt="DeviceTwin_IoTHub" src="https://user-images.githubusercontent.com/32341085/91222602-b252e180-e71f-11ea-9809-d14544cc59cf.png">


<img width="565" alt="IoTHub_QueryExplorer" src="https://user-images.githubusercontent.com/32341085/91222630-bf6fd080-e71f-11ea-8005-d13550dd4691.png">


<img width="1364" alt="Screenshot 2020-08-25 at 21 48 27" src="https://user-images.githubusercontent.com/32341085/91222651-c860a200-e71f-11ea-90c9-9afa23416663.png">

**Comment by abhipsaMisra** [comment] 2020-08-26 17:35
The registry manager query and query explorer on Azure portal will both connect to the same service endpoint. With the activity time being returned as default value via the query explorer as well, this indicates that an incorrect value is being sent over by the service.
Please open a support request [here](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request), so that the service team can investigate this issue.

Since this is not a bug with the sdk, I am closing this issue.
Feel free to reopen this issue if you still see inconsistencies between the value returned by the service, and that returned by the sdk.

**Comment by az-iot-builder-01** [comment] 2020-08-26 17:36
@abhipsaMisra, @michaellindberg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-08-26 17:35 UTC
Labels: IoTSDK, bug
