### ISSUE TITLE
Random UnauthorizedExceptions after upgrading from 1.0.21 to 1.6.1

### ISSUE THREAD

**Issue by robertsimmons** [Azure/azure-iot-sdk-csharp#349] opened 2018-01-24 18:14 UTC
- **OS and version used:** Azure WebJobs 

- **SDK version used:** 1.6.1 

# Description of the issue:
We have services in Azure that run as emulated devices running 24/7. After upgrading our packages from 1.0.21 to 1.6.1, we randomly get UnauthorizedExceptions. Of our about 20 devices, 1 to 3 will throw this exception at the same time. After about a minute it reconnects. We've been using this version for about 2 weeks, and it'll happen every 1 to 3 days.

# Code sample exhibiting the issue:
It happens on this line:

var message = await _client.ReceiveAsync();

which is called in a threaded while loop:

In our Start method:
_receiveThread = new Thread(ReceiveLoop);
_receiveThread.Start();

private async void ReceiveLoop()
{
	while (_receiveThread != null)
	{
		try
		{
			var message = await _client.ReceiveAsync();

			if (message == null)
			{
				Logger.Debug("Received a null message.");
				continue;
			}

			var body = message.GetBodyStream()?.ReadToEnd();

			Logger.Debug($"Received message {message.MessageId}: {body}");

			Receive(body.FromJson<Dictionary<Guid,string>>());

			await _client.CompleteAsync(message);
		}
		catch (Exception ex)
		{
			Logger.Error(ex, "Error while receiving/processing message.");
		}
	}
}

# Console log of the issue:
Here's two sets of log messages from our device manager. They went offline together and as you can see came back online within a minute. There are tracking ids for both.

"ef46324d1ea749bc92ab813e77fd30f3","INFO","2018-01-24 05:47:41.5406","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""time"":""2018-01-24T05:47:35.019457Z"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Error"",""statusCode"":401,""statusDescription"":""Unauthorized"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"bdaf7e0bac274159b14c82baecbe9ceb","WARN","2018-01-24 05:47:41.9937","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device connection event received for device with invalid ID : {""durationMs"":0,""authType"":null,""protocol"":""Amqp"",""time"":""2018-01-24T05:47:35.019457+00:00"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Error"",""statusCode"":401,""statusType"":0,""statusDescription"":""Unauthorized"",""deviceId"":null}",""
"69d71b38e4624a0783bb7941b2158493","INFO","2018-01-24 05:47:41.9937","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""time"":""2018-01-24T05:47:34.4412987Z"",""operationName"":""deviceDisconnect"",""category"":""Connections"",""level"":""Information"",""deviceId"":""5ec9a911-5b44-486b-ab7d-765f9bc79cf5"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"3ea3cd89a79d46ce9fe4d40e6ae30713","INFO","2018-01-24 05:47:42.5407","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device 5ec9a911-5b44-486b-ab7d-765f9bc79cf5 has gone disconnected from the hub and will be marked as offline soon.",""
"c4e1f0c9fe214d86be56aca0ddeec864","INFO","2018-01-24 05:47:42.5407","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""time"":""2018-01-24T05:47:35.2225145Z"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Error"",""statusCode"":401,""statusDescription"":""Unauthorized"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"51825d6486ec432f81a9bf80160705b5","WARN","2018-01-24 05:47:42.5407","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device connection event received for device with invalid ID : {""durationMs"":0,""authType"":null,""protocol"":""Amqp"",""time"":""2018-01-24T05:47:35.2225145+00:00"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Error"",""statusCode"":401,""statusType"":0,""statusDescription"":""Unauthorized"",""deviceId"":null}",""
"d00ca2a2ee28412f876b0174cee5cb18","INFO","2018-01-24 05:47:42.5407","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""time"":""2018-01-24T05:47:34.4412987Z"",""operationName"":""deviceDisconnect"",""category"":""Connections"",""level"":""Information"",""deviceId"":""d4db7a33-d3e2-4d00-a53b-4facb715a9d7"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"e1d615a3541d44098bd1158a0b0df941","INFO","2018-01-24 05:47:42.5719","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device d4db7a33-d3e2-4d00-a53b-4facb715a9d7 has gone disconnected from the hub and will be marked as offline soon.",""
"9202b268e00942ceabe6e7125bdc3ba9","INFO","2018-01-24 05:48:54.1625","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""authType"":""{\""scope\"":\""device\"",\""type\"":\""sas\"",\""issuer\"":\""iothub\"",\""acceptingIpFilterRule\"":null}"",""time"":""2018-01-24T05:48:48.4168462Z"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Information"",""deviceId"":""d4db7a33-d3e2-4d00-a53b-4facb715a9d7"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"28942a0724224b36a517f3609cf0a4f4","INFO","2018-01-24 05:48:54.1625","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device d4db7a33-d3e2-4d00-a53b-4facb715a9d7 has reconnected before it was marked as offline.",""
"6f77ae01ed11439484aab71813a3a6c4","INFO","2018-01-24 05:48:54.5844","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Received message: {""protocol"":""Amqp"",""authType"":""{\""scope\"":\""device\"",\""type\"":\""sas\"",\""issuer\"":\""iothub\"",\""acceptingIpFilterRule\"":null}"",""time"":""2018-01-24T05:48:50.4970136Z"",""operationName"":""deviceConnect"",""category"":""Connections"",""level"":""Information"",""deviceId"":""5ec9a911-5b44-486b-ab7d-765f9bc79cf5"",""ipAddress"":""52.XXX.XXX.XXX""}",""
"ef22dddcd95e4d8a857ac83b5090d22d","INFO","2018-01-24 05:48:54.5844","MurataCloud.Services.DeviceManagement.DeviceMonitoring.HubOperationsEventHubProcessor","Device 5ec9a911-5b44-486b-ab7d-765f9bc79cf5 has reconnected before it was marked as offline.",""

**Comment by jasmineymlo** [comment] 2018-01-27 01:11
@robertsimmons Thanks for filing this issue.  Looks like this is related to #263 where token refresher is not renewing on-time before token expiry  thus leads to random UnauthorizedExceptions. @varunpuranik is currently looking into it.  Thanks.

**Comment by CIPop** [comment] 2018-02-01 21:39
Closing as duplicate of #319. This is being addressed by #357.

**Closed by CIPop** 2018-02-01 21:39 UTC
Labels: bug
