### ISSUE TITLE
Recently Azure Function involved Azure.Devices 1.4.1 got error, "Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.0.0.0" 

### ISSUE THREAD

**Issue by IanLin419** [Azure/azure-iot-sdk-csharp#281] opened 2017-12-11 09:53 UTC
- **OS and version used:** 
--> Azure Functions
- **SDK version used:** 
--> Microsoft.Azure.Devices": "1.4.1

# Description of the issue:
The function app use Microsoft.Azure.Devices 1.4.1 failed. There is no problem from Sept until 22 Nov.

Scenario:
   The service conduct C# on Azure Functions by httptrigger and attempt connect to Azure Iot Hub then.

Error message:
    "Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

# Code sample exhibiting the issue:
Attempt to make similar environment.
1. Create Project.json with the following content:
    {
    "frameworks": {
        "net46":{
            "dependencies": {
                "Microsoft.Azure.Devices": "1.4.1"
                }
            }
        }
    }
    
2. implement piece of connection function in code field through ServiceClient class with Iot Hub connectionsting. There is same problem reproduced.

***Note Functions auto-generated Project.lock.json. The version of Azure.Amqp is 2.0.6 however the error message need lower version Microsoft.Azure.Amqp 2.0.0.0.
     
     "Microsoft.Azure.Amqp/2.0.6": {
        "type": "package",
        "compile": {
          "lib/net45/Microsoft.Azure.Amqp.dll": {}
        },
        "runtime": {
          "lib/net45/Microsoft.Azure.Amqp.dll": {}
        }
      },
      "Microsoft.Azure.Devices/1.4.1": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNet.WebApi.Client": "5.2.3",
          "Microsoft.AspNet.WebApi.Core": "5.2.3",
          "Microsoft.Azure.Amqp": "2.0.6",
          "Microsoft.Azure.Devices.Shared": "1.1.1",
          "PCLCrypto": "2.0.147"
        },
        "frameworkAssemblies": [
          "System",
          "System.Core",
          "System.Net.Http",
          "System.Runtime.Serialization"
        ],
        "compile": {
          "lib/net451/Microsoft.Azure.Devices.dll": {}
        },
        "runtime": {
          "lib/net451/Microsoft.Azure.Devices.dll": {}
        }
      }   
 

Code sample:

    ServiceClient serviceClient = null;
    var connectionString = <Azure Iot Hub ConnectionString>;
    try
    {
        serviceClinet = ServiceClient.CreateFromConnectionString(connectionString);
    }
    catch (Exception e)
    {
        log.Info($"Exception thrown: {e.Message}");
    }

# Console log of the issue:
"Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

**Comment by CIPop** [comment] 2017-12-19 21:16
Thanks for reporting @IanLin419 !

The assembly version and the NuGet versions are usually not the same. I'll take a look at this issue. I believe it's caused by nuspec running out of sync.

**Comment by CIPop** [comment] 2017-12-22 09:36
@IanLin419 please try again with our [latest release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2017-12-21). I have upgraded the AMQP reference to the latest version of their NuGet package.

**Comment by CIPop** [comment] 2018-01-09 02:49
Tentatively closing this. @IanLin419 please reopen if this still repros with the latest release.

**Closed by CIPop** 2018-01-09 02:49 UTC

**Comment by IanLin419** [comment] 2018-01-10 03:36
Hello CIPop,
Thanks for your advice. The problem was resolved.
