### ISSUE TITLE
Azure IoTHub - SAS token not expiring

### ISSUE THREAD

**Issue by PoonkuzhaliVasudevan** [Azure/azure-iot-sdk-csharp#564] opened 2018-07-26 06:00 UTC
Package version: **Microsoft.Azure.Devices.Client 1.17.0**

I have created a device client in the following way

**_deviceClient = DeviceClient.Create(s_iotHubUri, new DeviceAuthenticationWithToken(deviceId, sasToken), Microsoft.Azure.Devices.Client.TransportType.Amqp);_**

I use the deviceClient to send messages using deviceClient.SendEventAsync(message). The SAS expiry is set to be 5 mins(for example) but the SAS is not expiring at all and the messages are being sent using the device client. I expect an exception like 'SAS has expired'. But messages are being sent normally. But if i stop the communication and try to create a client using the same SAS, i get SAS expired exception but why does this not happen while sending messages to device?

Please help with this issue.

**Comment by CIPop** [comment] 2018-08-01 02:56
/cc: @simonporter 

This is related to #565. My understanding is that the service will account for potential clock skew and ignore a time delta of a few minutes if the device is already connected. Please try running longer (~10 minutes). The expected behavior is described in #565: the application should get `UnauthorizedException`.

Closing for now - please reopen if you are not seeing this behavior.

**Closed by CIPop** 2018-08-01 02:56 UTC
Labels: area-service

**Comment by PoonkuzhaliVasudevan** [comment] 2018-08-06 06:32
@CIPop The SAS is expiring 10 minutes after the expiry time, using MQTT protocol. But is there anything we can do about this extra 10 minutes?

**Comment by CIPop** [comment] 2018-08-06 21:47
@PoonkuzhaliVasudevan - I believe that is by design to account for clock skew and is not configurable.
Could you share more (either publicly here, or privately via a service request) on why you would need this to be exact?
