### ISSUE TITLE
[feature request] PnP APIs: ClientPropertyCollection.Add* methods should be simplified and consolidated

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#2098] opened 2021-07-13 01:38 UTC
### **Issue**
Currently we have these methods:
•         ClientPropertyCollection.Add(System.Collections.Generic.IDictionary<string, object>) 
•         ClientPropertyCollection.AddComponentProperties(string, System.Collections.Generic.IDictionary<string, object>)
•         ClientPropertyCollection.AddComponentProperty(string, string, object)
•         ClientPropertyCollection.AddOrUpdate(System.Collections.Generic.IDictionary<string, object>)
•         ClientPropertyCollection.AddOrUpdateComponentProperties(string, System.Collections.Generic.IDictionary<string, object>)
•         ClientPropertyCollection.AddOrUpdateComponentProperty(string, string, object)
•         ClientPropertyCollection.AddOrUpdateRootProperty(string, object)
•         ClientPropertyCollection.AddRootProperty(string, object)

Having different methods for 'Root' vs 'Component' is unnecessary and inconsistent with other APIs. Also we seem to be missing 'Root" for some of them here.

### **Proposal**
We could have only two methods with the appropriate overloads to specify component vs root, and single vs multiple properties:
•         ClientPropertyCollection.Add(System.Collections.Generic.IDictionary<string, object>) + 3 overloads
•         ClientPropertyCollection.AddOrUpdate(System.Collections.Generic.IDictionary<string, object>) + 3 overloads

(or even reduce to a single AddOrUpdate method + 3 overloads - why need 'Add' when we have 'AddOrUpdate'?)

**Comment by abhipsaMisra** [comment] 2021-07-15 23:07
There are two proposals mentioned here, and I'll go through them sequentially.
1. > Having different methods for 'Root' vs 'Component' is unnecessary and inconsistent with other APIs. Also we seem to be missing 'Root" for some of them here.

Interpreting the intended operation from the ClientPropertyCollection.Add(params...) API overloads works in all scenarios other than this:
`ClientPropertyCollection.Add(string, System.Collections.Generic.IDictionary<string, object>)`

This could be:
(1) Add a root-level property with a value of type map
(2) Add a collection of component-level properties to the specified component.

For this reason, we need to differentiate if `ClientPropertyCollection.Add(string, System.Collections.Generic.IDictionary<string, object>)` is being called on a root-level property or a component-level property.

This could have been achieved in two ways:
(1) Add a boolean flag indicating if this is a component-level operation
(2) Separate out the root-level and component-level operations into different methods altogether.

We chose option (2) over (1) because (1) would create APIs where we both provide a component name as a param and also supply a flag indicating that this is a component-level operation.

We do have some APIs that neither mention "Root" or "Component", I'll clean those up.

2. >why need 'Add' when we have 'AddOrUpdate'

The `Add` and `AddOrUpdate` APIs differentiate the intended behavior when you try to add a pre-existing key to the property collection. This being a `preview` API, we didn't want to take a dependency on a single behavior outright (always overwrite the value or always reject duplicate keys with an exception), but rather wanted to provide the flexibility to the user. If we receive feedback that is excessive and not required, we are open to reducing the API surface with a single documented behavior.

**Comment by abhipsaMisra** [comment] 2021-11-17 16:13
The Add* methods have been consolidated and the update has been released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-10-8.

**Closed by abhipsaMisra** 2021-11-17 16:13 UTC
Labels: enhancement, fix-checked-in, IoTSDK
