### ISSUE TITLE
MethodHandler is eating app code exceptions

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#617] opened 2018-09-10 20:23 UTC
- **OS, version, SKU and CPU architecture used:** Windows 10 Enterprise 1803 
- **Application's .NET Target Framework :** Microsoft.NETCore.UniversalWindowsPlatform 6.1.7, UWP 17134 
- **Device:** Laptop 
- **SDK version used:** 1.18.0 

## Description of the issue:

MethodHandler (and MethodDefaultHandler etc.) is eating app code exceptions, making it very hard for developers to find app code issues in those callbacks:

1) even when running with debugger attached, VS won't break on my exception because it is handled in the SDK code (unless I enable breaking on all handled exceptions which adds a ton of noise)

2) my app doesn't crash on my exception, so I won't get any crash logs in appcenter/devcenter/watson that would notify me of this issue

## Code sample exhibiting the issue:

1) Call DeviceClient.SetMethodHandlerAsync("foo", MethodHandler, null);
2) Trigger the foo method

Expected: app crashes
Actual: exception is swallowed by platform

```
        private async Task<MethodResponse> MethodHandler(MethodRequest request, object userContext)
        {
            throw new InvalidOperationException("fake app bug");
        }
```

**Comment by CIPop** [comment] 2018-09-10 21:06
/cc @varunpuranik @tameraw 

@wickste this is a design-level bug. I completely agree that should never happen. In fact, mixing callbacks and async/await caused a lot of other issues and we are thinking of removing this model for future versions of the SDK.
As workaround, my recommendation is to use a TaskCompletion source within the callbacks and implement proper async/await patterns in the application's logic. (E.g. use a Task[] and WaitAny, ensuring that all task completions are made on a single thread, etc) Using this pattern will not depend on the handlers and so work-around the exception issue.

Closing at this point as won't fix: by design.

**Closed by CIPop** 2018-09-10 21:06 UTC
Labels: question
