### ISSUE TITLE
[Bug Report] PnP APIs: ModuleClient.UpdateClientPropertiesAsync doesn’t work in edge module 

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#2095] opened 2021-07-12 23:10 UTC
# Context
Microsoft.Azure.Devices.Client 1.38.0-preview-001

## Description of the issue
ModuleClient.UpdateClientPropertiesAsync throws when being called from an IoT-Edge module. It works correctly when being called from a regular module (i.e. not IoT-Edge module)

## Code sample exhibiting the issue
ModuleClient.UpdateClientPropertiesAsync()

## Console log of the issue
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '$version' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Azure.Devices.Client.ReadOnlyDictionary45`2.System.Collections.Generic.IDictionary<TKey,TValue>.get_Item(TKey key)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendPropertyPatchAsync(ClientPropertyCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<SendPropertyPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendPropertyPatchAsync(ClientPropertyCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateClientPropertiesAsync(ClientPropertyCollection clientProperties, CancellationToken cancellationToken)
   at EdgeModulePrev.Program.Setup() in /src/EdgeModulePrev/Program.cs:line 38
   at EdgeModulePrev.Program.Main(String[] args) in /src/EdgeModulePrev/Program.cs:line 145
   at EdgeModulePrev.Program.<Main>(String[] args)
```

**Comment by abhipsaMisra** [comment] 2021-07-20 19:30
@ancaantochi , @varunpuranik  - For an reported property update operation from a module client, does IoT edge return the version of the update twin as a part of the response?

**Comment by abhipsaMisra** [comment] 2021-07-21 21:53
The Edge team confirmed offline that since a reported property update patch isn't applied immediately, an updated version is not returned. 
#2115 adds checks to ensure that we verify the presence of "version" before attempting to retrieve it, which should fix this issue. I've also added doc comments calling out the behavior with IoT Edge.

**Comment by abhipsaMisra** [comment] 2021-11-17 16:12
This bug has been fixed and an updated description has been added to the doc comments. This has been released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-10-8.

**Closed by abhipsaMisra** 2021-11-17 16:12 UTC
Labels: bug, fix-checked-in, IoTSDK
