### ISSUE TITLE
Wrong exception parameters for DeviceNotFoundException and DeviceAlreadyExistsException for IoT Hub service clients

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#599] opened 2018-08-27 19:49 UTC
Shared code in `\common\src\service\ExceptionHandlingHelper.cs` calls into several exception types which have `deviceId` as first parameter, not `message`:
- [ ] DeviceNotFoundException
- [ ] DeviceAlreadyExistsException

This results in confusing messages. For example the following is thrown when a Method is called for a disconnected device (spaces added for clarity):

```
Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: 
Device 

{"Message":"{\"errorCode\":404103,\"trackingId\":\"cda96d6c6e65450d8ded4cea239f7401-G:4-TimeStamp:08/27/2018 07:55:43\",\
"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:00\"},\"timestampUtc\":\"2018-08-27T07:55:43.0356528Z\"}","ExceptionMessage":""} 

not registered
```

**Comment by RyanLilla** [comment] 2018-10-06 17:01
@CIPop I am interested in taking on this issue if it is still available! As I am new to exception handling in this context,  is there somewhere/someone I could refer to for assistance?

I see that for the method definition where `message` is a parameter, there is a second parameter of type `Exception innerException` that would need to be used within ExceptionHandlingHelper.cs, correct? Or are we saying that `deviceId` shouldn't be the single parameter at all within these methods, but should be `message` instead?

**Comment by CIPop** [comment] 2018-10-15 19:14
@RyanLilla go for it! Really appreciate the contributions!

**Comment by mprigge** [comment] 2019-08-06 17:00
This issue bit me, so I'd be interested to fix it. Seems like the easiest way to fix it without breaking a bunch of things that are using the `public DeviceNotFoundException(string deviceId)` constructor would be to add a `(Exception)null` parameter to the calls in `\common\src\service\ExceptionHandlingHelper.cs` so that they hit the `public DeviceNotFoundException(string message, Exception innerException)` constructor instead. Other portions of the codebase already use that workaround and so that's easy enough to implement. I need to read the contribution guidelines, but I'll try to do that soon.

I did want to ask one other thing, however (maybe a noob question for you, @CIPop ). It may make sense from the context of the upstream REST service that a device literally not existing and a device not being online at the moment might both be "not found". However, from a consumer of this SDK's perspective, those circumstances would typically be handled wildly different ways (permanent failure in one case, perhaps a retry in another). 

Would it make sense to implement a new exception type (or inner exception type) and do the work necessary within the SDK to differentiate between the device actually not being found and a direct method execution timeout occurring? Or is the expectation that the SDK user would be responsible for deserializing the exception message JSON themselves to determine which circumstance they are in? I am not familiar enough with the inner workings of this project to know whether the exception messages provided by the REST API are stable enough to start matching more discrete SDK exceptions up to them or whether that's not done within the SDK by design.

Sorry for the somewhat off-topic question on what is otherwise a very easily addressable issue! 😄

**Comment by CIPop** [comment] 2019-08-06 21:21
> I did want to ask one other thing, however (maybe a noob question for you, @CIPop ). It may make sense from the context of the upstream REST service that a device literally not existing and a device not being online at the moment might both be "not found". However, from a consumer of this SDK's perspective, those circumstances would typically be handled wildly different ways (permanent failure in one case, perhaps a retry in another).

@mprigge that's not a noob question at all: we can't add new exceptions because we'll break existing applications if they would ever do binding redirects to a new version of the SDK nuget. (They won't expect the new exception type and crash.)

I do agree that the two failure modes warrant two separate exceptions and so the second option you present (different InnerException) could be a solution. Another idea would be to mark the IsTransient (only for the `DeviceNotFoundException` from the ServiceClient namespace) as true for the case where the device was registered but it's not online at the moment.

As always, we appreciate your contribution! @mprigge feel free to submit a PR!

**Comment by vinagesh** [comment] 2020-06-12 21:58
Issue if fixed. This will be part of the next release.

**Comment by abhipsaMisra** [comment] 2020-07-10 03:05
This has been fixed as of Microsoft.Azure.Devices v1.22.0

**Comment by az-iot-builder-01** [comment] 2020-07-10 03:05
@CIPop, @mprigge, @vinagesh, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-07-10 03:05 UTC
Labels: IoTSDK, bug, fix-checked-in, good first issue, help wanted
