### ISSUE TITLE
IoTEdge Device shows offline in Service SDK

### ISSUE THREAD

**Issue by MPapst** [Azure/azure-iot-sdk-csharp#567] opened 2018-07-26 18:36 UTC
See Azure/iotedge#80

I am using the `RegistryManager` from the `Microsoft.Azure.Devices` Package to get informations about the running IoT Edge Devices.
This works very well except the device status. This one is always disconnected (even if the portal shows connected).

I am not sure if this is a SDK issue or an iotedge issue.

## Expected Behavior
`Device` instance requested by `RegistryManager` shows actual Connection State.

## Current Behavior
Shows always Disconnected

## Steps to Reproduce
```C#
RegistryManager mgr = RegistryManager.CreateFromConnectionString("");
var dev = await mgr.GetDeviceAsync("IoTEdge-0002");
Console.WriteLine(dev.ConnectionState);
```
### Device (Host) Operating System
Windows 10

### Container Operating System
Windows

#### iotedged
1.0
#### Edge Agent
1.0
#### Edge Hub
1.0
#### Docker
18.03.1-ce

**Comment by CIPop** [comment] 2018-08-01 01:28
@srivanie PTAL

**Comment by CIPop** [comment] 2018-08-01 02:27
Thanks for reporting @MPapst! I'm able to repro this.

@srivanie I'm able to repro this with a device that shows as OK. In RegistryManager it shows as Disconnected:
![image](https://user-images.githubusercontent.com/8635911/43497590-c562053e-94f7-11e8-8597-efeb3d8263a6.png)

` h-pi3                                              : Disconnected : Last seen: 1/1/0001 12:00:00 AM`

**Comment by CIPop** [comment] 2018-08-30 18:41
@MPapst My current understanding is that Edge is not using the DeviceClient at all: only modules are used and so there is no report on when the device connected last.
@varunpuranik, @myagley - this is indeed adding confusion but this is by design of the SDK side if DeviceClient is never connecting.

Closing as "by design" from the SDK side.

**Comment by az-iot-builder-01** [comment] 2018-08-30 18:41
@MPapst, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2018-08-30 18:41 UTC
Labels: area-service, question

**Comment by MPapst** [comment] 2018-09-04 09:45
@CIPop this is really confusing, it should be at last added to the documentation.
Please note that the Azure Portal shows the connection state based on twin properties, see Azure/iotedge#80
