### ISSUE TITLE
[Bug Report] UnauthorizedException: CONNECT failed: RefusedServerUnavailable

### ISSUE THREAD

**Issue by and-rewsmith** [Azure/azure-iot-sdk-csharp#1485] opened 2020-07-24 00:20 UTC
# Context
I am a member of the iotedge team and was investigating this issue:
https://github.com/Azure/iotedge/issues/3265

Context copied from original issue:
Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Raspbian Stretch
Architecture [e.g. amd64, arm32, arm64]: arm32
Container OS [e.g. Linux containers, Windows containers]: Linux containers

Your requested context:
- **OS, version, SKU and CPU architecture used:** <VERSION> (Raspbian Stretch arm32)
- **Application's .NET Target Framework :** netcoreapp3.1 
- **Device:** Unknown
- **SDK version used:** 1.23.2  

## Description of the issue

When using a device client with mqtt protocol, we get the following exception from inside EdgeHub (more context in linked issue):
```
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedServerUnavailable
```

No one from our team has seen this before. I think that this might not be an SDK issue, but thought it would be good to raise the issue here to check if you have any insight.

If you haven't seen this issue before either and think it is not an SDK bug, could you raise it in the appropriate IoTHub channel so we can percolate the issue to its source?

## Code sample exhibiting the issue
See original issue

## Console log of the issue
See original issue

**Comment by abhipsaMisra** [comment] 2020-07-27 19:02
@and-rewsmith Could you explain a bit about the scenario that is failing from the SDK? From the original issue there seems to be some issue with certificate chaining, and the intermediate certificate information not being relayed to the hub; but with all the edge terminology, I might be understanding it incorrectly.

Could you please explain where you see the failure happening?

**Comment by and-rewsmith** [comment] 2020-07-30 00:38
The cert issues aren't directly relevant. We create device client's inside edgehub for various reasons. The issue is that we have never seen this exception before, which seems like it indicates some service issue. I am opening the issue here to confirm that it indicates a service issue (and if not then an SDK bug).

**Comment by florianbader** [comment] 2020-08-12 13:12
Hey @abhipsaMisra and @and-rewsmith, any news on the issue?

**Comment by abhipsaMisra** [comment] 2020-08-12 18:12
@and-rewsmith Could you please explain where you see the failure happening?
Are you able to repro this issue consistently when you try to connect an x509 based module to edge hub via iot hub?

**Comment by and-rewsmith** [comment] 2020-08-12 21:38
This failure occurs when edgehub attempts to open its upstream connection to iothub on behalf of the module. In the original issue, we saw this failing consistently for mqtt, however when switching to amqp everything worked fine.

In our code it happens here:
https://github.com/Azure/iotedge/blob/release/1.0.9/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs#L55

**Comment by abhipsaMisra** [comment] 2020-08-12 22:09
Thanks for the info @and-rewsmith . 
So it opens when you call `OpenAsycn()` on the module client?

Can you share the info on how you create the client instance? Also, can you share the SDK logs generated in this scenario?
Steps to capture logs: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by and-rewsmith** [comment] 2020-08-13 19:56
Yes, it looks like from the logs in the original issue that the error happens on OpenAsync(). I cannot reproduce this on my side.

Here is the place where the module client is created:
https://github.com/Azure/iotedge/blob/release/1.0.9/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ClientProvider.cs#L33

Note that when the transport settings switched to amqp everything started working. This is why I believe it is a bug and opened the issue here. Do you think this is a service side issue?

**Comment by abhipsaMisra** [comment] 2020-08-13 20:08
I am still not clear on the scenario here; the original bug issue reports this occurring when using x509 certificates for authentication, but the code that you've linked above points to a connection string (sas token) based authentication. 
We cannot analyze the issue without the below information:

- How is the client instance initialized - auth mechanism used, transport type used, any specific transport settings used (connection pooling, client certificates, connection timeouts specified, etc).
- A small sample snippet that reproduces this issue - how is the client initialized, what operation is called on the client, etc. - 

The exception listed in this issue title signifies that service responded to the client's connect packet with a return code of `ConnectReturnCode.RefusedServerUnavailable`, which the device client v1.23.2 will treat as a non-retryable exception. (This has since been marked as a transient retryable exception).

To root cause this issue, we will need the above requested information to ensure that the client usage is as expected. If yes, then this would need to be investigated by the service team to figure out why they sent a response code of `ConnectReturnCode.RefusedServerUnavailable` -> if your module connects to an edge hub, have you confirmed that the edge hub instance was up and running?

**Comment by and-rewsmith** [comment] 2020-08-13 20:56
Sorry for the confusion about the scenario. I should have further clarified the edge related terminology. 

The original issue says that the customer is attempting to initialize edge with with x509 certificates. There are two sets of certificates that are specified:
1. The device ca cert and trust bundle which is used to sign the edgehub server certificate
2. The dps certificates used to initialize the edge device identity 

This failure occurs when edgehub attempts to open its upstream connection to iothub on behalf of the module. The stack in the original issue _is_ from EdgeHub so it is online (copied below for convenience):
```
<4> 2020-07-22 07:46:54.319 +00:00 [WRN] - Error creating cloud connection for client edgedevice1/module1
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedServerUnavailable
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 141
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 55
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass30_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 145
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 173
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 61
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 126
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateNewCloudProxyAsync(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 102
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.Create(IIdentity identity, Action`2 connectionStatusChangedHandler, ITransportSettings[] transportSettings, IMessageConverterProvider messageConverterProvider, IClientProvider clientProvider, ICloudListener cloudListener, ITokenProvider tokenProvider, TimeSpan idleTimeout, Boolean closeOnIdleTimeout, TimeSpan operationTimeout, String productInfo) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 91
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.<>c__DisplayClass17_1.<<Connect>b__2>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IIdentity identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 135
```

I agree that we should get this information you mentioned so we know how EdgeHub creates the module client. I tried to repro the issue in order to get more concrete information, but was unable.

That being said, when you switch the protocol to amqp, the only difference in the module client creation is the transport type. That is why I was thinking this is a service side issue. If there is already a known service side issue we can save some time investigating. 

@florianbader If you switch the upstream protocol to mqtt does it still fail? You have outlined how your setup which does not repro for me. Do you have other edge devices connected using the same setup that currently work?

**Comment by abhipsaMisra** [comment] 2020-08-13 21:15
Thanks for the detailed explanation @and-rewsmith , this does help.
> This failure occurs when edgehub attempts to open its upstream connection to iothub on behalf of the module.

You've mentioned that this failure only occurs when the upstream protocol is mqtt, but it works as expected over amqp. **Is this issue reproducible 100% over mqtt?** `ConnectReturnCode.RefusedServerUnavailable` looks like a transient error to me, which would indicate there was something going on at the service end which caused them to reject the connect packet with this error code; but I would not expect this to happen 100% of the time. 
Have you reached out to IoT Hub service team to see if the endpoint you were connecting to was healthy for the duration of your experiment?

**Comment by abhipsaMisra** [comment] 2020-08-13 21:16
Also, have you checked if the behavior changes if you use sas tokens for authentication, instead of x509 certificates?

**Comment by and-rewsmith** [comment] 2020-08-13 21:43
Some further clarification:

I think the certificates mentioned are only for initializing edge. If so, they are not involved with the upstream connection that edgehub is making on behalf of the module and edgehub will use sas. @florianbader You said this was a dummy module so I assumed the simplest setup. Can you confirm that you are not using certs when creating your ModuleClient?

**Comment by florianbader** [comment] 2020-08-14 09:57
I tried it again today with MQTT and it worked. Maybe it was indeed the endpoint that was unhealthy? The initial experiment was over several days (2020-07-21 - 2020-07-23) though which seems strange. @and-rewsmith do you know if there were and service degradation for DPS or IoT Hub during that time? I'm not sure if we should switch back to MQTT because it was a one time issue or it's a MQTT issue that occurs regularly.

**Comment by abhipsaMisra** [comment] 2020-08-14 16:35
Do you have a long haul setup that replicates your test scenario? If yes, you can leave that running for a while (over MQTT), and monitor if you see any disconnects. 
If you do, please share the timestamps where you see this issue occur, and someone from the [service team](https://github.com/Azure/azure-iot-sdk-csharp#need-support) should be able to help you debug this.

Also, the mapping of `ConnectReturnCode.RefusedServerUnavailable` to a retryable exception is available in [`master`](https://github.com/Azure/azure-iot-sdk-csharp/pull/1510), but hasn't been released as of today. If you take a dependency on this code, it will treat `ConnectReturnCode.RefusedServerUnavailable` as a transient exception, and the device sdk will reattempt to establish connection.
However, this will not resolve the issue if something other than service availability is causing service to return an error code of `ConnectReturnCode.RefusedServerUnavailable`.

**Comment by and-rewsmith** [comment] 2020-08-14 16:41
I looked and didn't see any known service degradation with this error.

**Comment by abhipsaMisra** [comment] 2020-08-19 16:53
Can we set up a repro in an environment and see if we hit this issue again? Without any service logs it will not be possible to root cause this issue.
Also, if possible, could you take a dependency on the sourcecode in `master`? It contains a fix that will no longer mark `ConnectReturnCode.RefusedServerUnavailable` as non-retryable.

**Comment by abhipsaMisra** [comment] 2020-09-04 17:12
Closing because of lack of activity, feel free to reopen this if you still see issues.

**Comment by az-iot-builder-01** [comment] 2020-09-04 17:12
@abhipsaMisra, @and-rewsmith, @florianbader, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-09-04 17:12 UTC
Labels: area-service, bug

**Comment by jbthefish** [comment] 2021-01-21 10:20
Hi *,

I can reproduce this issue. I just have to switch the protocol from AMQP to MQTT via env vars the communication stops.

In the egdeHub:
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: CONNECT failed: RefusedServerUnavailable

In the edgeAgent:

<6> 2021-01-21 11:18:38.182 +00:00 [INF] - Unable to update EdgeAgent module as the EdgeAgent module identity could not be obtained
<6> 2021-01-21 11:18:38.182 +00:00 [INF] - Unable to process module edgeAgent add or update as the module identity could not be obtained

@az-iot-builder-01 : Please reopen this issue

Thanks,
JB

**Comment by ailn** [comment] 2021-02-17 18:23
It's been fixed recently on service side. Please check if you can reproduce it.
