### ISSUE TITLE
CONNECT failed: RefusedNotAuthorized C#

### ISSUE THREAD

**Issue by CRACKbomber** [Azure/azure-iot-sdk-csharp#63] opened 2017-03-01 16:14 UTC
{Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.

When I try to set method handlers I get the above inner exception.
[csharpcode.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/811292/csharpcode.txt)

**Comment by jasmineymlo** [comment] 2017-03-01 19:51
looks like the cert that you are using is not valid?  It's authorization exception.

**Comment by CRACKbomber** [comment] 2017-03-01 20:53
It is a valid cert. It is our root dc cert.

**Comment by rajeevmv** [comment] 2017-03-02 01:29
Can you try adding a **_receiveAsync_** call in your code after the following line ?
  _client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Mqtt);
   **_client.ReceiveAsync(TimeSpan.FromSeconds(2)).Wait();**

**Comment by CRACKbomber** [comment] 2017-03-02 12:18
Same thing, {"CONNECT failed: RefusedNotAuthorized"}

**Comment by rajeevmv** [comment] 2017-03-02 18:16
I have created a simple console app which uses X.509 certs and device methods. It works on my IoT Hub. Can you plug in the constant values at the top and try it out on your IoT hub and X.509 device?

[X509-Mqtt-Methods.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/814683/X509-Mqtt-Methods.zip)

**Comment by CRACKbomber** [comment] 2017-03-07 14:09
Nope, same issue.

**Comment by rajeevmv** [comment] 2017-03-08 00:56
From the service-side logs, it appears that the service is not receiving the client certificate. 

Can you try changing the transport protocol to MQTT over Websocket like this:
   __client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Mqtt_WebSocket_Only);_

You could also try using another protocol like Amqp or Http:
___client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Amqp);_
___client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Http1);_

This will help us narrow down the issue that you are facing. Also, let us know which version of Windows the client is running on.

**Comment by CRACKbomber** [comment] 2017-03-08 12:08
![image](https://cloud.githubusercontent.com/assets/1568512/23703455/0b9d0e48-03ce-11e7-9f2e-79d9ffad4e42.png)
Here is my windows info.

**Comment by CRACKbomber** [comment] 2017-03-08 12:18
_client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Mqtt_WebSocket_Only);
Same unauthorized message

__client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Amqp);
Message = "The method or operation is not implemented."

__client = DeviceClient.Create("pc-iothub01.azure-devices.net", certAuth, TransportType.Http1);
It seems to work but when I try to invoke a method from a service client it gives 
Message = "Device {\"Message\":\"ErrorCode:DeviceNotOnline;Timed out waiting for device to connect.\",\"ExceptionMessage\":\"Tracking ID:14d6bb5f477048198af4840d9279d68f-G:2-TimeStamp:03/08/2017 12:17:57\"} not registered"

**Comment by tameraw** [comment] 2017-03-08 19:27
@CRACKbomber - Can you please provide which version of the SDK your are using? Thanks.

**Comment by CRACKbomber** [comment] 2017-03-08 19:51
Microsoft.Azure.Devices.Client 1.2.4
Microsoft.Azure.Devices.Shared 1.0.7
Microsoft.Azure.Amqp 2.0.4

**Comment by rajeevmv** [comment] 2017-03-08 20:17
@CRACKbomber - Can you try using a self-signed cert - https://technet.microsoft.com/itpro/powershell/windows/pki/new-selfsignedcertificate ?

**Comment by CRACKbomber** [comment] 2017-03-08 20:18
@rajeevmv I have

**Comment by rajeevmv** [comment] 2017-03-08 23:33
@CRACKbomber ,

Can you share a self-signed cert that fails for you here? Please note that this should be a throwaway cert that you do not plan to use for any other purpose. I can try to use that cert using the sample I posted above and check if it works for me.

**Comment by CRACKbomber** [comment] 2017-03-09 12:45
There is no private key in my cert.
[pc-iothub01.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/830837/pc-iothub01.zip)

**Comment by rajeevmv** [comment] 2017-03-09 16:48
I will need a pfx file (which contains the private key)  along with a password to read the file. (FYI: https://security.stackexchange.com/questions/29425/difference-between-pfx-and-cert-certificates). This is because the client will need the private key in order to successfully complete the TLS handshake with the service.

**Comment by rajeevmv** [comment] 2017-03-09 18:10
This appears to be the root cause of the issue that you are facing. You will need to provide .pfx file as input to the device client. The .pfx file should contain the private key of the cert generated. This private key will not be transmitted over the wire. But, it will be used to prove to the server that it is indeed the owner of the cert.

**Comment by tameraw** [comment] 2017-03-13 18:28
@CRACKbomber - Closing issue. Please let us know if still having problems.

**Closed by tameraw** 2017-03-13 18:28 UTC
Labels: help wanted

**Comment by awong1900** [comment] 2017-05-25 08:56
@rajeevmv Can you tell me how o make .pfx file. Any step by step helper link? I have same issue now.

**Comment by rajeevmv** [comment] 2017-05-25 17:56
Take a look at this link: http://windowsitpro.com/blog/creating-self-signed-certificates-powershell
