### ISSUE TITLE
InvalidOperationException thrown when SendEventBatchAsync is called on the DeviceClient.

### ISSUE THREAD

**Issue by namalu** [Azure/azure-iot-sdk-csharp#1061] opened 2019-09-13 16:53 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION>  macOS Mojave 10.14.6 x64
- **Application's .NET Target Framework :** <NETVERSION>  xamarin
- **Device:** <DEVICETYPE>  iPhone & Android Phones
- **SDK version used:** <VERSION>  1.21.1

## Description of the issue:

InvalidOperationException thrown when SendEventBatchAsync is called on the DeviceClient.

It appears that on line 79 of the AmqpIoTSendingLink class, DataBody is null on the AmqpMessage. This is because on line 58 of the AmqpIoTMessageConverter class the AmqpMessage is initialized with a Stream. The BodyStream property should be used instead of DataBody.

## Code sample exhibiting the issue:

```C#
var message = new Message(Encoding.ASCII.GetBytes(jsonString));
_queue.Enqueue(message);

if (_queue.Count >= 30)
{
    var messages = _queue.ToArray();
    try
    {
        await _deviceClient.SendEventBatchAsync(messages);
    }
    catch (Exception e)
    {
        // Exception thrown here 
        System.Diagnostics.Debug.WriteLine(e);
    }
}
```

## Console log of the issue:

System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Microsoft.Azure.Amqp.AmqpMessage.get_DataBody () [0x00000] in <9cea9f83a18d449284cb86dea42f9d95>:0 
  at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.SendMessagesAsync (System.Collections.Generic.IEnumerable`1[T] messages, System.TimeSpan timeout) [0x00067] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendMessagesAsync (System.Collections.Generic.IEnumerable`1[T] messages, System.TimeSpan timeout) [0x0011b] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendEventsAsync (System.Collections.Generic.IEnumerable`1[T] messages, System.TimeSpan timeout) [0x0009f] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync (System.Collections.Generic.IEnumerable`1[T] messages, System.Threading.CancellationToken cancellationToken) [0x000ae] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler+<>c__DisplayClass22_0.<ExecuteWithErrorHandlingAsync>b__0 () [0x00071] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T] (System.Func`1[TResult] asyncOperation) [0x0014c] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler+<>c__DisplayClass15_0.<SendEventAsync>b__0 () [0x00135] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync (System.Collections.Generic.IEnumerable`1[T] messages, System.Threading.CancellationToken cancellationToken) [0x00101] in <8ffa96f34a5347a3a51154700c91224d>:0 
  at Microsoft.Azure.Devices.Client.InternalClient.SendEventBatchAsync (System.Collections.Generic.IEnumerable`1[T] messages) [0x00092] in <8ffa96f34a5347a3a51154700c91224d>:0

**Comment by CIPop** [comment] 2019-09-13 22:29
Thanks for reporting @namalu ! We are aware of several Xamarin issues with our SDKs and we are tracking part of a larger project.
I do remember we have had fixes in our latest release (today): please try again and let us know .

**Comment by ntrpnr** [comment] 2019-09-17 19:10
I have the same issue on .NET Standard 2.0 and AMQP TCP Only.

We had to fallback to foreach SendEventAsync.

**Comment by jbmadscience** [comment] 2019-09-25 21:22
I am also seeing this on .NET Standard 2.0 and AMQP TCP. This isn't Xamarin specific, I think.

My codebase is fairly large, so it would not be easy to provide the whole thing. However I'd be glad to provide code snippets. I can also perform experiments/answer questions as needed.

**Comment by jbmadscience** [comment] 2019-09-25 22:27
Confirmed that ntrpnr's workaround works in my code as well! Just do a foreach SendEventAsync.

**Comment by OliverNET** [comment] 2019-10-24 13:43
Same issue here with an ASP.NET Core 3 app.

Works with Microsoft.Azure.Devices.Client with Version 1.20.3
Fails with all newer nuget packages.

As far as i understand, the issue with fallback to foreach & SendEventAsync() is that you get charged/throttled differently.

E.g. 10 messages with 200 bytes each:
SendEventAsync() => 10 messages charged
SendEventBatchAsync() => 1 message charged

**Comment by namalu** [comment] 2019-10-24 15:14
> Thanks for reporting @namalu ! We are aware of several Xamarin issues with our SDKs and we are tracking part of a larger project.
> I do remember we have had fixes in our latest release (today): please try again and let us know .

Definitely not Xamarin specific.and this issue still persists in the latest Nuget.

**Comment by timtay-microsoft** [comment] 2019-11-14 19:10
@namalu if you are willing to provide a PR for this issue, I'd be happy to merge it in for you.

**Comment by ntrpnr** [comment] 2019-11-18 12:14
Any update on this issue? SendEventBatchAsync was working in a recent version and is present in the official documentation but does not simply work, at least not over AMQP.

As previously noted, this is **not** limited to Xamarin.

**Comment by Peter-B-** [comment] 2019-11-21 18:05
I took a look into that problem today. I am a bit confused on how it should work, but the issue is the following:

Starting from line 75 of ```AmqpIoTSendingLink.SendMessagesAsync``` there is the following statement:
```
using (AmqpMessage amqpMessage = AmqpIoTMessageConverter.MessageToAmqpMessage(message))
{
    var data = new Data()
    {
        Value = amqpMessage.DataBody
    };
    messageList.Add(data);
}
```
```MessageToAmqpMessage(message)``` returns a ```AmqpBodyStreamMessage``` object which does not implement ```DataBody```. It would implement a ```BodyStream``` property instead. 

I do not understand the implication of this or what the correct fix might be, but maybe this can help you to locate the issue.

I tried to write a unit test for this scenario, but it feels like ```AmqpIoTSendingLink``` might require some refactoring first.

**Comment by schungx** [comment] 2019-11-22 10:49
I can't understand why such a core feature can be broken without anybody in Microsoft's QC department spotting this BEFORE the release got out?

**Comment by davilu** [comment] 2019-12-18 05:05
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment] 2019-12-18 05:06
@CIPop, @ntrpnr, @jbmadscience, @OliverNET, @namalu, @Peter-B-, @schungx, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-18 05:05 UTC
Labels: bug, fix-checked-in

**Comment by OliverNET** [comment] 2019-12-18 08:48
Thank you for fixing this bug.
It's working now 👍

**Comment by Bjarkes** [comment] 2020-01-13 09:43
Will this fix be merged into the preview branch any time soon? As we are using the DeviceStream preview feature we are forced to use only the 1.29.0-preview-* versions, which does not include the fix yet.

**Comment by prmathur-microsoft** [comment] 2020-01-23 01:17
Preview branch is updated once every month. It should be  apart of next preview release.
