### ISSUE TITLE
ServiceClient.SendAsync(...) throws NullReferenceException on second try.

### ISSUE THREAD

**Issue by PanClifton** [Azure/azure-iot-sdk-csharp#1113] opened 2019-11-12 08:02 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10 Desktop x64,
- **Application's .NET Target Framework :** <NETVERSION> 
netcoreapp2.2
- **SDK version used:** <VERSION> 
Microsoft.Azure.Devices v1.18.1

## Description of the issue:
I am working on retry policies on IoTHub ServiceClient and i noticed some 'strange' behavior of ServiceClient.SendAsync(...) method. 
Consider scenario when there is **no internet connection** and message is to be send to IoTHub using ServiceClient.SendAsync(...) method. 
On the first try there following exception is thrown

**Exception 1**
```System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)\r\n   at Microsoft.Azure.Devices.AmqpServiceClient.SendAsync(String deviceId, Message message, Nullable`1 timeout)\r\n   at ```

when trying to send message for the second time exception below is thrown:

**Exception 2**
```System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Azure.Devices.AmqpServiceClient.SendAsync(String deviceId, Message message, Nullable`1 timeout)\r\n   at  ```

After System.NullReferenceException is thrown sending message is not possible. In order to send new message new instance of the ServicClient needs to be created.

I also noticed that same situation occurs for Microsoft.Azure.Devices.FeedbackReceiver and methods
FeedbackReceiver.ReceiveAsync(...), FeedbackReceiver.CompleteAsync(...) and FeedbackReceiver.AbandonAsync(...)

Could you kindly advise is this is expected behavior?

## Code sample exhibiting the issue:

**Service Proxy Code:**

```
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;
using Microsoft.Azure.Devices;

namespace Communication.IoTHub
{
    [ExcludeFromCodeCoverage]
    public class IotHubServiceClientProxy : IIotHubServiceClientProxy
    {
        private readonly ServiceClient _serviceClient;
        private readonly IIotHubConfiguration _configuration;

        public IotHubServiceClientProxy(IIotHubConfiguration configuration)
        {
            _serviceClient = ServiceClient.CreateFromConnectionString(
                configuration.OwnerConnectionString,
                configuration.TransportType);

            _configuration = configuration;
        }

        public Task SendAsync(string deviceId, Message message)
        {
            return _serviceClient.SendAsync(deviceId, message, _configuration.MessagingOperationTimeout); 
        }
    }
}

```
**Test Code**
```
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Devices;
using Moq;
using NUnit.Framework;

namespace Core.IntegrationTests.IoTHub
{
    public class IotHubServiceClientProxy_Tests
    {
        private readonly string _ioTHuvConnectionString = "";
        private readonly string _device = "my-test-device";

        [Test, Explicit]
        public async Task SendAsync_WhenCalled_ShouldNotThrow()
        {
            var iotHubConfigurationMock = new Mock<IIotHubConfiguration>();
            iotHubConfigurationMock.SetupGet(x => x.OwnerConnectionString).Returns(_ioTHuvConnectionString);
            iotHubConfigurationMock.SetupGet(x => x.TransportType).Returns(TransportType.Amqp_WebSocket_Only);

            var sut = new IotHubServiceClientProxy(iotHubConfigurationMock.Object);

            var deviceCreatedMessage = new Message(Encoding.ASCII.GetBytes("body"));

            for (int i = 0; i < 3; i++)
            {
                try
                {
                    await sut.SendAsync(_device, deviceCreatedMessage).ConfigureAwait(false);
                }
                catch (Exception e)
                {
                     //first try - Exception 1 is thrown
                     //Second try - Exception 2 is thrown
                    Console.WriteLine(e);
                }
            }
        }
    }
}

```

**Comment by timtay-microsoft** [comment] 2019-11-13 00:20
Is the nullReferenceException tied to the service client itself? Or is it the message? I can't tell from the truncated stacktrace you provided

**Comment by PanClifton** [comment] 2019-11-13 08:22
its from the service client itself

**Comment by timtay-microsoft** [comment] 2019-11-13 20:23
So the service client is null after the first failure? That doesn't sound like expected behavior. We'll spend some time investigating this

**Comment by timtay-microsoft** [comment] 2019-11-14 00:24
Actually, it appears this is by design. Similar to our Device client, when the service client encounters an exception, it disposes the underlying amqp objects. Attempting to open the service client again won't help, so you have to create a new service client in cases like this

**Comment by PanClifton** [comment] 2019-11-14 09:10
ok, thank you very much.

**Comment by timtay-microsoft** [comment] 2019-11-14 19:40
Okay, I'll close this issue then

**Comment by az-iot-builder-01** [comment] 2019-11-14 19:40
@PanClifton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-11-14 19:40 UTC
Labels: question
