### ISSUE TITLE
Possibility to quickly check for c2d messages

### ISSUE THREAD

**Issue by mfalkvidd** [Azure/azure-iot-sdk-csharp#1041] opened 2019-08-28 19:43 UTC
I was instructed by Alberto Vega (Azure) Microsoft employee in https://social.msdn.microsoft.com/Forums/en-US/73be02e4-d858-4024-af1d-a1b97a69473d/how-to-compile-c-sdk-for-net-461?forum=azureiothub to open an issue here.

It is stated that:
> Not expect cancellation to happen in under a minute for any operation.
> Use CancellationToken to cancel operations.

This makes it impossible to handle c2d messages for IoT protocols like NB-IoT, LoRaWAN and Sigfox.

In both LoRaWAN and Sigfox, the device sends a message to the cloud, indicating that it is ready to receive a c2d message (called downlink message in Sigfox and LoRaWAN lingo). The cloud infrastructure then has a deadline of about 1 second to check if there are any c2d messages, and transmit them. This deadline is designed to be short, so the device can shut off as soon as possible to conserve battery.

For NB-IoT, there is no standard for the deadline, but due to the high current draw of the NB-IoT modem, a few seconds response time is desirable.

When using the IoT Hub C# SDK, it is (by design?) impossible to check for c2d messages in under 60 seconds because the only way to know that there are no queued messages is to wait until a timeout occurs, and that timeout is at least 60 seconds.

Is IoT Hub the wrong service for this type of devices? If not, how should c2d messages be handled? If we shouldn't use IoT Hub, can we get a recommendation of what else should be used?

Mabe ReceiveAsync could be modified to return null immediately if there are no more queued c2d messages?

**Comment by bikamani** [comment] 2019-08-29 18:55
@mfalkvidd We will investigate this further and get back to you.

Thanks

**Comment by mfalkvidd** [comment] 2019-08-29 19:00
Great! Let me know if I can do anything to help.

**Comment by mfalkvidd** [comment] 2019-09-03 10:04
Another use case that is hard to solve today (to my knowledge):

In a device management web application, I want to be able to list all c2d messages that are queued for a specific device. Currently, the only way to get that list seems to be to wait for the 60 second timeout.

**Comment by mfalkvidd** [comment] 2019-09-04 13:34
I'll be happy to assist on a Skype call or similar if you want to discuss possible solutions or need additional input.

**Comment by prmathur-microsoft** [comment] 2019-09-09 22:37
Would this PR [2](https://github.com/Azure/azure-iot-sdk-csharp/pull/100) resolve your problem?

**Comment by mfalkvidd** [comment] 2019-09-10 06:58
@prmathur-microsoft that PR does not seem related, and is 2 years old. Did you reference the wrong PR?

**Comment by prmathur-microsoft** [comment] 2019-09-10 18:39
Yes looks like I linked the incorrect PR. [`[Here ]`](https://github.com/Azure/azure-iot-sdk-csharp/pull/1002)is the correct PR.

**Comment by mfalkvidd** [comment] 2019-09-10 19:49
Well, yes. That's why I started [the question on the azure iot hub forum](https://social.msdn.microsoft.com/Forums/en-US/73be02e4-d858-4024-af1d-a1b97a69473d/how-to-compile-c-sdk-for-net-461?forum=azureiothub ) with
"I'm in desperate need for https://github.com/Azure/azure-iot-sdk-csharp/pull/1002 which has not been merged yet."

But, according to the answer I got on the azure iot hub forum from _Alberto Vega (Azure) Microsoft employee_

> I have reached out internally and the team is still debating about including that PR you are referencing to. They mentioned though that they have been pointing customers to CancellationToken since 1.19 please see the Pull Request 1027 (it has also documentation additions) so you should:
> 
>     Not expect cancellation to happen in under a minute for any operation.
>     Use CancellationToken to cancel operations.
>
> Please open an issue on the SDK repo if you have any further questions.

So I created this issue. We're running around in circles here ;-)

**Comment by prmathur-microsoft** [comment] 2019-09-16 20:28
You are right. We are circling around :)
Lets continue the conversation here on github.
I'm very much interested in pulling this PR. However the only reason we are holding that PR is we want to make sure it works for the following scenarios as it would be breaking change if not.
1. Implicit open. i.e. any operation should be able to trigger open
2. It should pass all of the e2e which reinforces that it did not break any behavior.
3. As we were communicating since a while, we recently had a major fix being checked into master. Can you rebase this PR on top of that and verify functionality.

At the moment my team is swamped and we don't have time to look at above three. If you can take care of the three things above then I would be happy to help you with merging this PR.

**Comment by mfalkvidd** [comment] 2019-09-18 08:24
I'm not sure I'll manage, since I don't have insight in the original PR, but I'll try.

Some questions:
1. I guess I should fork this repo, create my own branch, fetch debugerr's branch rebase and push to my branch? Can I then amend PR 1002, or do I need to create a new PR?
2. How do I run the tests?
3. When opening the SDK, Visual Studio code analysis has a lot of complaints. My guess is that Microsoft is using a different ruleset internally. Is this ruleset available somewhere? I looked in CONTRIBUTING.md but didn't find any info.
4. The code style in this repo is quite different from Visual Studio's default formatting. Is the style guide available somewhere? I wouldn't want to mess up your style, or cause an unnecessary large diff. I looked in CONTRIBUTING.md but didn't find any info.

**Comment by prmathur-microsoft** [comment] 2019-09-18 17:59
Answers inline - 
I guess I should fork this repo, create my own branch, fetch debugerr's branch rebase and push to my branch? Can I then amend PR 1002, or do I need to create a new PR?
How do I run the tests?
_[PM] I am unable to rebase this PR on top of master because of merge conflicts. So if you are not the original author then I believe what you mentioned here is the only option you have. Unless @debugerr is willing to take this forward._
When opening the SDK, Visual Studio code analysis has a lot of complaints. My guess is that Microsoft is using a different ruleset internally. Is this ruleset available somewhere? I looked in CONTRIBUTING.md but didn't find any info.
The code style in this repo is quite different from Visual Studio's default formatting. Is the style guide available somewhere? I wouldn't want to mess up your style, or cause an unnecessary large diff. I looked in CONTRIBUTING.md but didn't find any info.
_[PM] This is a good idea to publish in future. However for now you have to follow https://github.com/Azure/azure-iot-sdk-csharp/blob/master/doc/coding-style.md_

**Comment by mfalkvidd** [comment] 2019-09-18 18:23
Thank you.

https://github.com/Azure/azure-iot-sdk-csharp/blob/master/doc/coding-style.md says
> We have provided a Visual Studio 2013 vssettings file (corefx.vssettings) at the root of the corefx repository, enabling C# auto-formatting conforming to the above guidelines.
But I am unable to find any vssettings file in this repo, and I didn't find such file in https://github.com/dotnet/corefx/find/master either. Do you know where to find this file?

Also, looks like you missed the "How do I run the tests?" question.

**Comment by mfalkvidd** [comment] 2019-09-24 20:13
@prmathur-microsoft based on the comments from @davilu in https://github.com/Azure/azure-iot-sdk-csharp/pull/1002 that PR does not seem to be a solution. We seem to be back to the orginal question:
> Is IoT Hub the wrong service for devices using LoRaWAN, Sigfox and NB-IoT? If not, how should c2d messages be handled? If we shouldn't use IoT Hub, can we get a recommendation of what else should be used?

**Comment by bikamani** [comment] 2019-09-25 21:51
@mfalkvidd We are currently working on a different approach to fix this issue on AMQP. The idea is to modify ReceiveAsync(TimeSpan timeout) implementation to honor the timeout for the public API by tracking the time for each of the operation that happens before ReceiveMessageAsync call. That should resolve the issue you are facing.

**Comment by bikamani** [comment] 2019-11-22 18:24
@mfalkvidd We have released Device client v1.21.2 which has fixes around receiveAsync on AMQP. Can you verify if the issue is resolved?

**Comment by bikamani** [comment] 2019-12-03 00:04
Have not heard back and as the issue is addressed in latest release, closing it. Please reopen if there are more questions.

**Comment by az-iot-builder-01** [comment] 2019-12-03 00:05
@mfalkvidd, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-03 00:04 UTC
Labels: customer-input-needed
