### ISSUE TITLE
Reconnect issues using Mqtt/Amqp

### ISSUE THREAD

**Issue by Mikkelcv** [Azure/azure-iot-sdk-csharp#635] opened 2018-09-27 10:29 UTC
I am using the examples from:
https://github.com/Azure-Samples/azure-iot-samples-csharp

Specific: "back-end-application" and "simulated-device-2" in Quickstarts

I start the 2 applications and see that the method on the device is called. Then pull the network on the machine with "simulated-device-2" running and after a while reconnect and use "back-end-application" again and then I see the following:

**DirectMethod** invocation is restored when I use _Mqtt_ however if the transporttype is the default _Amqp_ then I am no longer able to execute DirectMethods after the reconnect of the network.

I then modified the code to use **Cloud2Device** messages then I see the following:
Both for Mqtt and Amqp the DeviceClient is not able to reconnect, it does not receive anything.

From this:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-reliability-features-in-sdks
in the Retry section, there I understand that I do not need to do anything to be able to reconnect.

I see in most of the example that Mqtt is used. Is there a reason why the default Amqp is not chosen?

Thank you
Mikkel

**Comment by prmathur-microsoft** [comment] 2018-10-01 21:43
As the documentation mentions, reconnect should work irrespective of the transport type. This looks like a issue, we need to address. Can you please send logs around re-connection that you see ?

**Comment by Mikkelcv** [comment] 2018-10-02 14:28
Hi,

Is there any specific log you are thinking of?

I did some more testing of DirectMethod using amqp and mqtt and looks like I can get both to fail and also recover.
I am now using SetConnectionStatusChangesHandler and printing what it receives.

I am calling the method and then wait 3 seconds before calling it again. The payload is an integer which I increase by one every time.

I pull the network cable and reinsert it after I have seen the client fail to deliver for at least 5 tries. 

On the Simulated device I see patterns like this:

> IoT Hub Quickstarts #2 - Simulated device. Ctrl-C to exit.
> 
> choose 0: Mqtt, 1:Amqp
> 0
> [02.10.2018 13:01:48] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 1 times)
> [02.10.2018 13:02:00] - Value received 0
> [02.10.2018 13:02:03] - Value received 1
> [02.10.2018 13:02:06] - Value received 2
> [02.10.2018 13:02:09] - Value received 3
> [02.10.2018 13:02:13] - Value received 4
> [02.10.2018 13:02:16] - Value received 5
> [02.10.2018 13:02:19] - Value received 6
> [02.10.2018 13:02:22] - Value received 7
> [02.10.2018 13:04:40] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 1 times)
> [02.10.2018 13:04:42] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 2 times)
> [02.10.2018 13:04:42] - Value received 45
> [02.10.2018 13:04:45] - Value received 46
> [02.10.2018 13:04:48] - Value received 47
> [02.10.2018 13:04:51] - Value received 48
> [02.10.2018 13:05:10] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 2 times)
> [02.10.2018 13:05:11] - IoT Device connection status changed to Disabled for reason Client_Close (Connected 2 times)

Once I receive Client_Close then the connection is never recovered. I have waited 10+ minutes each time, since I have seen that sometime it recovers after 3 minutes.

But if you see in this example then the Client_Close comes after _19 seconds,_ that is fast. In the below example it is 4 minutes.

(Connected X times; is how many times I get a Connection_OK)

In the next you can see a long session with Amqp where the connection was recovered multiple times but suddenly it is no longer working and goes also to "Client_Close":

Does it help in any way? are we expected to do anything for this event?

> IoT Hub Quickstarts #2 - Simulated device. Ctrl-C to exit.
> 
> choose 0: Mqtt, 1:Amqp
> 1
> [02.10.2018 13:10:49] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 1 times)
> [02.10.2018 13:10:52] - Value received 0
> [02.10.2018 13:10:56] - Value received 1
> [02.10.2018 13:10:59] - Value received 2
> [02.10.2018 13:11:02] - Value received 3
> [02.10.2018 13:11:23] - Value received 4
> [02.10.2018 13:11:26] - Value received 5
> [02.10.2018 13:11:29] - Value received 6
> [02.10.2018 13:11:32] - Value received 7
> [02.10.2018 13:11:36] - Value received 8
> [02.10.2018 13:15:27] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 1 times)
> [02.10.2018 13:15:28] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 2 times)
> [02.10.2018 13:15:31] - Value received 76
> [02.10.2018 13:15:34] - Value received 77
> [02.10.2018 13:15:38] - Value received 78
> [02.10.2018 13:15:41] - Value received 79
> [02.10.2018 13:15:44] - Value received 80
> [02.10.2018 13:15:47] - Value received 81
> [02.10.2018 13:15:50] - Value received 82
> [02.10.2018 13:15:53] - Value received 83
> [02.10.2018 13:19:45] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 2 times)
> [02.10.2018 13:19:46] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 3 times)
> [02.10.2018 13:19:46] - Value received 150
> [02.10.2018 13:19:50] - Value received 151
> [02.10.2018 13:19:53] - Value received 152
> [02.10.2018 13:19:56] - Value received 153
> [02.10.2018 13:19:59] - Value received 154
> [02.10.2018 13:23:51] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 3 times)
> [02.10.2018 13:23:51] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 4 times)
> [02.10.2018 13:23:52] - Value received 221
> [02.10.2018 13:23:55] - Value received 222
> [02.10.2018 13:23:58] - Value received 223
> [02.10.2018 13:24:01] - Value received 224
> [02.10.2018 13:24:04] - Value received 225
> [02.10.2018 13:24:08] - Value received 226
> [02.10.2018 13:24:11] - Value received 227
> [02.10.2018 13:24:14] - Value received 228
> [02.10.2018 13:24:17] - Value received 229
> [02.10.2018 13:24:20] - Value received 230
> [02.10.2018 13:24:23] - Value received 231
> [02.10.2018 13:24:27] - Value received 232
> [02.10.2018 13:24:30] - Value received 233
> [02.10.2018 13:24:33] - Value received 234
> [02.10.2018 13:24:36] - Value received 235
> [02.10.2018 13:24:39] - Value received 236
> [02.10.2018 13:28:31] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 4 times)
> [02.10.2018 13:28:32] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 5 times)
> [02.10.2018 13:28:34] - Value received 304
> [02.10.2018 13:28:38] - Value received 305
> [02.10.2018 13:28:41] - Value received 306
> [02.10.2018 13:28:44] - Value received 307
> [02.10.2018 13:28:47] - Value received 308
> [02.10.2018 13:32:38] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 5 times)
> [02.10.2018 13:32:39] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 6 times)
> [02.10.2018 13:32:42] - Value received 376
> [02.10.2018 13:32:45] - Value received 377
> [02.10.2018 13:32:49] - Value received 378
> [02.10.2018 13:32:52] - Value received 379
> [02.10.2018 13:32:55] - Value received 380
> [02.10.2018 13:32:58] - Value received 381
> [02.10.2018 13:36:49] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 6 times)
> [02.10.2018 13:36:50] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 7 times)
> [02.10.2018 13:36:53] - Value received 448
> [02.10.2018 13:36:56] - Value received 449
> [02.10.2018 13:36:59] - Value received 450
> [02.10.2018 13:37:02] - Value received 451
> [02.10.2018 13:37:06] - Value received 452
> [02.10.2018 13:37:09] - Value received 453
> [02.10.2018 13:37:12] - Value received 454
> [02.10.2018 13:37:15] - Value received 455
> [02.10.2018 13:37:18] - Value received 456
> [02.10.2018 13:37:21] - Value received 457
> [02.10.2018 13:37:25] - Value received 458
> [02.10.2018 13:37:28] - Value received 459
> [02.10.2018 13:37:31] - Value received 460
> [02.10.2018 13:37:34] - Value received 461
> [02.10.2018 13:37:38] - Value received 462
> [02.10.2018 13:37:41] - Value received 463
> [02.10.2018 13:37:44] - Value received 464
> [02.10.2018 13:37:47] - Value received 465
> [02.10.2018 13:41:39] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 7 times)
> [02.10.2018 13:41:40] - IoT Device connection status changed to Connected for reason Connection_Ok (Connected 8 times)
> [02.10.2018 13:41:43] - Value received 533
> [02.10.2018 13:41:46] - Value received 534
> [02.10.2018 13:41:49] - Value received 535
> [02.10.2018 13:41:52] - Value received 536
> [02.10.2018 13:41:55] - Value received 537
> [02.10.2018 13:41:59] - Value received 538
> [02.10.2018 13:42:02] - Value received 539
> [02.10.2018 13:42:05] - Value received 540
> [02.10.2018 13:42:08] - Value received 541
> [02.10.2018 13:42:11] - Value received 542
> [02.10.2018 13:42:14] - Value received 543
> [02.10.2018 13:42:18] - Value received 544
> [02.10.2018 13:42:21] - Value received 545
> [02.10.2018 13:42:24] - Value received 546
> [02.10.2018 13:42:27] - Value received 547
> [02.10.2018 13:42:30] - Value received 548
> [02.10.2018 13:42:33] - Value received 549
> [02.10.2018 13:42:37] - Value received 550
> [02.10.2018 13:42:40] - Value received 551
> [02.10.2018 13:42:43] - Value received 552
> [02.10.2018 13:42:46] - Value received 553
> [02.10.2018 13:42:49] - Value received 554
> [02.10.2018 13:42:52] - Value received 555
> [02.10.2018 13:42:56] - Value received 556
> [02.10.2018 13:42:59] - Value received 557
> [02.10.2018 13:43:12] - Value received 558
> [02.10.2018 13:47:01] - IoT Device connection status changed to Disconnected_Retrying for reason No_Network (Connected 8 times)
> [02.10.2018 13:47:01] - IoT Device connection status changed to Disabled for reason Client_Close (Connected 8 times)

**Comment by prmathur-microsoft** [comment] 2018-10-09 23:36
Thanks for the logs. We will look at this and get back to you soon.

**Comment by CIPop** [comment] 2018-10-15 17:56
@Mikkelcv we're aware of this and I've been enhancing our logging and tests for a while to figure out all of these issues (at this time, I believe a series of design issues are causing multiple problems for reconnect).

Closing this as a duplicate of MQTT #558 and AMQP #571.

**Comment by az-iot-builder-01** [comment] 2018-10-15 17:56
@prmathur-microsoft, @Mikkelcv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by CIPop** 2018-10-15 17:56 UTC
Labels: investigation-required

**Comment by Mikkelcv** [comment] 2018-10-16 07:08
thank you, will take a look at that
