### ISSUE TITLE
Can't send events through SSL intercept proxy

### ISSUE THREAD

**Issue by damonbarry** [Azure/azure-iot-sdk-csharp#1393] opened 2020-06-08 20:36 UTC
- Ubuntu 18.04 amd64
- netcoreapp3.1
- Microsoft.Azure.Devices.Client 1.25.0

## Description

Using the _Docker container_ instructions in [this blog article](https://scubarda.com/2020/03/23/configure-squid-proxy-for-ssl-tls-inspection-https-interception/), I set up an SSL intercept proxy (squid with ssl bump feature enabled). I extracted the public cert from the provided pfx file and installed it system-wide using these steps:

```
sudo cp conf/certs/CyberSaiyan-mitm.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates
```

With the proxy running, I verified several scenarios through the proxy, including:
- Docker can pull images ([setup instructions](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy))
- IoT Edge daemon can talk to IoT Hub using HTTP ([setup instructions](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#iot-edge-daemon))
- A .NET Core app can make a simple HTTP request (when run directly on the host, and when run inside a docker container)
- An app using the C SDK can send events to IoT Hub using AMQP/WebSocket directly from the host, or in a container (I installed the static dev libraries via apt-get, version `0.2.0.0-19bionic`)

But the following scenarios _don't_ work:
- A .NET Core app using the C# SDK to send events to IoT Hub using AMQP/WebSocket or MQTT/WebSocket directly from the host, or in a container
- Edge Agent connecting to IoT Hub (via C# SDK) using AMQP/WebSocket (I didn't try MQTT)

The common thread in the not-working scenarios seems to be the C# SDK, as far as I can tell.

## Output

The .NET Core app gives the following output when it tries to send events:

```
Sending events as dlbedge58

Unhandled exception. Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '400' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketAsync(Uri websocketUri, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketTransportAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at send_events.Program.Main(String[] args) in /home/AzureUser/sdk-issue/send-events/Program.cs:line 77
   at send_events.Program.<Main>(String[] args)
```

I'm attaching the C# and C SDK apps [here](https://github.com/Azure/azure-iot-sdk-csharp/files/4748468/source-code.tar.gz)

This came from my investigation of Azure/iotedge#2973.

**Comment by CalleDanell** [comment] 2020-06-26 13:37
We are currently experiencing the same issue. Do you have any updates since we would like to deploy to customer using SSL interception in the near future? Thanks

**Comment by kiranpradeep** [comment] 2020-08-24 02:49
@damonbarry I am surprised that c-sdk worked for you. I had faced the exact same issue with c-sdk in that HTTP works (and the whole world except IoTHub), but not AMQP-WS/MQTT-WS. Please find this issue on c-sdk [[link](https://github.com/Azure/azure-iot-sdk-c/issues/1088#issuecomment-534603626)]. On Ubuntu Linux 18.04, using Fiddler or Charles proxies, I was able to consistently reproduce the issue until 1/Oct/2019. I did not pursue thereafter as I felt (could be wrong) the engineer wanted to close the ticket.

I am not telling that is IoTHub service side is the sole culprit, I am just suspicious that it is doing some thing unusual to other Azure services.

**Comment by damonbarry** [comment] 2020-08-26 17:43
@kiranpradeep My source code and repro steps are included in this issue. You could try my code/steps to see if it works for you too. I probably used a newer version of the C SDK than you used a year ago...maybe there has been a bug fix in the last year?

**Comment by kiranpradeep** [comment] 2020-08-27 03:21
@damonbarry The attached C sample _appears_ incorrect. It does not set the `HTTP_PROXY_OPTIONS` without which program will not direct the traffic via http proxy (http might still go via proxy depending on env, but not amqpws and mqttws). Kindly correct me if wrong.

Also, I did not see the option `OPTION_TRUSTED_CERT`, but that is ok, as I assume, you have manually added the proxyCA to system root certificate store.

**Comment by damonbarry** [comment] 2020-08-27 18:54
@kiranpradeep I think you're right...I tried again and my key vault client **IS** going through the proxy to grab the device connection string, but the C SDK is not. If I add `HTTP_PROXY_OPTIONS` to my sample, then the C SDK **does** hit the proxy, but I get a bunch of errors in the SDK output. So it looks like the C# SDK isn't the only one that struggles with SSL intercept proxies (as your referenced GitHub issue indicates).

**Comment by kiranpradeep** [comment] 2020-08-28 10:08
@damonbarry As the SDKs still works over some SSL intercepting proxies (e.g. works over Fiddler on Windows), it _appears_ more like some specific functionality (cipher suite, renegotiation etc) which is mandated by IoT Hub is missing in the SSL intercepting proxy. 

Hopefully after this feature is officially supported by iotedge, MS docs will specify the exhaustive list of [features](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-tls-support#recommended-ciphers) to be supported by SSL interceptors if any.

**Comment by abhipsaMisra** [comment] 2020-12-18 19:32
My apologies for the delay in responding to this. Based on the above thread and the ones on the C-sdk and iot-edge repos, it looks like while using certain SSL proxy clients with SSL decryption enabled, on Linux, the .NET sdk throws an authentication error.
The .NET sdk currently uses [ClientWebSocketOptions.Proxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.proxy?view=netstandard-2.1#System_Net_WebSockets_ClientWebSocketOptions_Proxy) to send the `IWebProxy` information for outgoing requests.

Is there something specific required to enable SSL interception for websockets? For the other Azure resources that you are able to successfully connect to, do you use .NET websocket clients to make those requests?

**Comment by damonbarry** [comment] 2021-01-04 21:48
> Is there something specific required to enable SSL interception for websockets? For the other Azure resources that you are able to successfully connect to, do you use .NET websocket clients to make those requests?

@abhipsaMisra I'm not sure what's required to make an SSL intercept proxy work through websockets. I believe all the successful cases I observed were just plain HTTPS.

**Comment by jamdavi** [comment] 2021-01-22 22:42
Spoke with @damonbarry offline and explained that Squid Proxy [doesn't support the native WebSockets protocol](https://wiki.squid-cache.org/SquidFaq/InterceptionProxy?highlight=%28websocket%29). There are scattered articles that talk about setting up splice and peek but the results are less than encouraging and require a lot of additional configuration which adds some fragility to the scenario.

Upon reading other threads that link to this one it seems that issues arising after introducing an intercepting proxy are pretty common and it's hard to pin down what exactly the environment is. The issues could present themselves whether it be a paid proxy or open source software and the configuration isn't correct, or if WebSockets aren't' supported. 

In the end we should validate that, if there is a proxy, the customer has ensured it's configured correctly. There is no way to test and validate all of these scenarios because they become complex very fast.

I am going to close this issue for now as the problem isn't specifically with the C# SDK, but instead an environment issue dealing with proxies.

**Closed by jamdavi** 2021-01-22 22:42 UTC
Labels: investigation-required
