### ISSUE TITLE
Registry Manager methods return different values for ConnectedState on the same device.

### ISSUE THREAD

**Issue by mjmostachetti** [Azure/azure-iot-sdk-csharp#510] opened 2018-06-12 21:38 UTC
- Running IoT Core ARM 

## Description of the issue:
Registry manager methods(createquery vs gettwinasync) return different values for the connectionstate of the devices. Create query returns updated device twin informatoin, except for the connection state, but get-twin-async returns the most up-to-date information for everything(reported properties, last updated, etc). 

## Code sample exhibiting the issue:
This code(createquery method) returns an incorrect property value for connectionState. It should be false but returns true.
```
var getAllDevicesQuery = registryManager?.CreateQuery("Select * From devices");
            var devices = await getAllDevicesQuery.GetNextAsTwinAsync();
            return devices;
```

This code(gettwinasync method) returns the correct property value for connectionState. 

```
var device = await registryManager?.GetTwinAsync(deviceId);
            return device;
```

Has anyone else experienced this? I'm using version 1.6.1 of .Net Azure.Devices SDK.

**Comment by CIPop** [comment] 2018-06-13 22:47
Thanks for reporting @mjmostachetti!

I was able to repro but only for a few seconds on my IoT Hub before the two results got back in sync. I believe this is by design (within some time) as the service is caching the query results. 

@simonporter  @ChrisGMsft to confirm

**Comment by mjmostachetti** [comment] 2018-06-14 20:21
Thanks for checking it out. Interesting. Yeah, I wouldn't mind if the two results were out of sync for a few seconds, but my createquery results seem to be frozen in their current state - almost a week now it seems.

**Comment by CIPop** [comment] 2018-06-15 18:28
> my createquery results seem to be frozen in their current state - almost a week now it seems.

That does sound like an issue on the service side. We need more information that can't be shared on GitHub: closing here.
Please open an SR ticket within your Azure Subscription. Instructions are available here: https://github.com/azure/azure-iot-sdk-csharp#need-support

**Closed by CIPop** 2018-06-15 18:28 UTC
Labels: area-service, question
