### ISSUE TITLE
JSON deserialization logic should ignore extra contents

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-sdk-csharp#341] opened 2018-01-18 14:51 UTC
This issue is derived from https://github.com/Azure/azure-iot-sdk-csharp/issues/213#issuecomment-358553689 to prevent future degradation of JSON related operations like device twin.

- **OS and version used:** ANY

- **SDK version used:** future

# Description of the issue:

We should ignore extra contents of JSON deserialization (currently, with setting `CheckAdditionalContent = false` in JSON.NET) to prevent future issues like #213. It will prevent JSON deserialization error even when the team add new or debugging feature to the JSON (for example, `capabilities` property in #213 ) and SDK users do not use latest SDK (they normaly use LTS release).

# Code sample exhibiting the issue:
(none)

# Console log of the issue:
(none)

**Comment by CIPop** [comment] 2018-01-18 22:56
That's a very good point @yfakariya ! Thanks for opening this issue.

@yzhong94 @tameraw given the user scenario described above, this would need to be implemented on all languages and added to the LTS branch to ensure new JSon formats don't break old SDKs.
/cc @pierreca @prmathur-microsoft @jspaith

**Comment by vinagesh** [comment] 2020-07-01 21:28
I cannot reproduce this issue locally with the given SDK version and steps suggested in the original bug. This issue will be closed in 10 days if there is no further issues. Please reopen another bug if such a problem occurs again.

**Comment by vinagesh** [comment] 2020-07-13 17:11
Closing issue as there has been no response since 10 days. Please open this issue if something like this reproduces.

**Comment by az-iot-builder-01** [comment] 2020-07-13 17:11
@CIPop, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by vinagesh** 2020-07-13 17:11 UTC
Labels: IoTSDK, bug, help wanted
