### ISSUE TITLE
ETag in ProvisioningServiceClient

### ISSUE THREAD

**Issue by VladislavDubrovenski** [Azure/azure-iot-sdk-csharp#3076] opened 2023-01-17 19:55 UTC
I am trying to update IndividualEnrollment and EnrollmentGroup that were created prior. I use 2.0.0-preview002

When I don't provide etag, I get an exception that it already exists. 

When I get the IndividualEnrollment with GetAsync, and then use its ETag to update the enrollment, I get "ETag is invalid". 

The only way I got it to work is by using ETag.All for the ETag when updating. 

Is that the intended behavior?

**Comment by patilsnr** [comment] 2023-01-17 23:16
Good afternoon @VladislavDubrovenski -- this is not the intended behavior and will label this as a bug. If you have any code snippets that demonstrate this behavior, they would be helpful on our end. Thank you!

**Comment by VladislavDubrovenski** [comment] 2023-01-18 01:03
Hi @patilsnr, sure!

The following throws conflict if enrollment already exists and I don't specify ETag when creating enrollment: 
```cs
var enrollmentResult = await _provisioningServiceClient.IndividualEnrollments.CreateOrUpdateAsync(enrollment);
```
The following throws "ETag is invalid" when I do GetAsync prior: 

```cs
var currentEnrollment = await _provisioningServiceClient.IndividualEnrollments.GetAsync(device.DeviceId);
enrollment.ETag = currentEnrollment.ETag;
var enrollmentResult = await _provisioningServiceClient.IndividualEnrollments.CreateOrUpdateAsync(enrollment);
```

And my workaround that I currently use: 
```cs
 try
{
    var currentEnrollment = await _provisioningServiceClient.IndividualEnrollments.GetAsync(device.DeviceId);
    enrollment.ETag = Azure.ETag.All; //if exists, set etag to all.
}
catch (ProvisioningServiceException e)
{
    if (e.StatusCode != HttpStatusCode.NotFound)
    {
        throw new ProvisioningServiceException(e);
    }
}
// Create or update individual enrollment
var enrollmentResult = await _provisioningServiceClient.IndividualEnrollments.CreateOrUpdateAsync(enrollment);
```

Thanks!

**Comment by patilsnr** [comment] 2023-01-18 21:55
Hi @VladislavDubrovenski -- thank you for the snippet! We have been able to reproduce the issue and are currently working on a fix. I'll update you on this thread when we get that in. Cheers!

**Comment by patilsnr** [comment] 2023-02-14 22:09
Hi again @VladislavDubrovenski -- would you be able to clarify which kind of attestation you're using to create enrollments? It would be `X509Attestation`, `SymmetricKeyAttestation`, or `TpmAttestation`. Thanks!

**Comment by VladislavDubrovenski** [comment] 2023-02-14 22:22
Hello. I use SymmetricKeyAttestation and TpmAttestation.

**Comment by patilsnr** [comment] 2023-02-15 18:40
Good morning @VladislavDubrovenski,

The initial error you've been encountering where `"ETag is invalid"` has been patched and will be included in the next release of the provisioning service client NuGet package. In order to access these changes now, please pull the latest version of the `previews/v2` branch on GitHub.

The secondary error message from trying to call `CreateOrUpdateAsync` on an enrollment that already exists is intended behavior on the service side to make sure all enrollments stay up to date. The best practice here is to call `GetAsync` before calling `CreateOrUpdateAsync` again. This will ensure the correct ETag is being used.

Thanks for bringing this up!

**Closed by patilsnr** 2023-02-15 18:40 UTC
Labels: bug, question, IoTSDK
