### ISSUE TITLE
Method UploadToBlobAsync on DeviceClient throws exception if DeviceId contain special characters

### ISSUE THREAD

**Issue by bartoszbr** [Azure/azure-iot-sdk-csharp#18] opened 2017-01-02 16:06 UTC
According to documentation: https://docs.microsoft.com/pl-pl/azure/iot-hub/iot-hub-devguide#device-identity-registry
DeviceId should be case-sensitive string (up to 128 characters long) of ASCII 7-bit alphanumeric characters +  special characters {'-', ':', '.', '+', '%', '_', '#', '*', '?', '!', '(', ')', ',', '=', '@', ';', '$', '''}
I tried to send file using UploadToBlobAsync method on DeviceClient object  where DeviceID contain '#' or '?' character and I received exception.

Exception message:
> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass42.<PutBlobImpl>b__41(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 2339
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<UploadToBlobAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SimulatedDevice.SimulatedDeviceForm.<sendFileButton_Click>d__11.MoveNext() in C:\[myPathToProject].cs:line 116
Request Information
RequestID:d0792532-0001-00b6-8010-6520a4000000
RequestDate:Mon, 02 Jan 2017 15:54:15 GMT
StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ErrorCode:AuthenticationFailed

**Comment by anhashia** [comment] 2017-01-07 03:11
Investigating !

**Comment by olivierbloch** [comment] 2017-01-13 04:33
Hi @bartoszbr 
Can you please confirm that you were successful using a device ID that doesn't contain any special character? I am asking because this shouldn't be a problem.
Another thing: are you using the received URI immediately? By default the TTL for the storage URI SAS is 1hour.
Can you share the piece of code you are using?

**Comment by bartoszbr** [comment] 2017-01-13 12:11
Yes I can send files to another devices where DeviceId doesn't have any special character. I checked it also on another Azure account with another subscription ane there is the same.
In every cases I use standard, default Azure storage - I just connected it with my IoT Hub.

Initialization of DeviceClient object:
`deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(deviceName, deviceKey));`

Method to handle Click event and call UploadToBlobAsync:
`  private async void sendFileButton_Click(object sender, EventArgs e)
        {
            if (ControlsHelper.IsComboBoxSelected(deviceIdComboBox, "Device ID") == false)
                return;

            var openFileDialog = new OpenFileDialog();
            var result = openFileDialog.ShowDialog();

            if (result != DialogResult.OK)
                return;

            using (var fileStream = openFileDialog.OpenFile())
            {
                var watch = System.Diagnostics.Stopwatch.StartNew();
                try
                {
                    await deviceClient.UploadToBlobAsync(openFileDialog.SafeFileName, fileStream);
                }
                catch (Exception ex)
                {
                    LogError("Exception occurred during sending file", ex);
                    watch.Stop();
                    return;
                }

                watch.Stop();
                var text = $"DeviceID: {deviceIdComboBox.SelectedItem} File {openFileDialog.SafeFileName} was sent in {watch.ElapsedMilliseconds}ms";
                LogInformation(text, sentMessagesRrichTextBox);
            }
        }`

**Comment by anhashia** [comment] 2017-01-14 01:21
Hi @bartoszbr 
I was able to locally reproduce the issue using # symbol in device ID . The issue is specific to C# client SDK and doesn't happen with C Azure IoT SDK.

The issue happens when following call is made
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Transport/HttpTransportHandler.cs#L230
When CloudBlockBlob object is created it omits special character # in StorageURI along with string after it. That is why UploadFromStreamAsync call fails.

Further investigation is going on to resolve this.

**Comment by anhashia** [comment] 2017-01-17 21:35
Hi @bartoszbr 
**Fix** for this issue has been merged https://github.com/Azure/azure-iot-sdk-csharp/commit/2366f032697127571220a3ebd236c59ae590a7bb

**Comment by tameraw** [comment] 2017-01-30 19:06
This is now in the latest release. Closing.

**Closed by tameraw** 2017-01-30 19:06 UTC
Labels: bug, CSS, fix checked in
