### ISSUE TITLE
 TwinCollection, parameter in constructor

### ISSUE THREAD

**Issue by stefan2410** [Azure/azure-iot-sdk-csharp#269] opened 2017-12-05 17:54 UTC
In Azure.Device.Client v.1.6.preview-001  in the TwinCollection's constructor I could pass a json string as parameter. In the last update  v.1.6.0.0  the constructor has not parameters. Existing code is broken. Is this by design?

**Comment by CIPop** [comment] 2017-12-07 21:01
@stefan2410  `v1.6.0-preview-001` is the modules preview release from https://github.com/Azure/azure-iot-sdk-csharp/tree/modules-preview and may contain new APIs. 

That said, v1.6.0 is not the release of this preview but the release of the Provisioning Device Client.

Note that public APIs present within -preview releases are subject to change.

/cc @tameraw @varunpuranik @damonbarry @yzhong94

**Comment by CIPop** [comment] 2017-12-07 21:02
Closing as by design: the new preview API has not yet been released.

**Closed by CIPop** 2017-12-07 21:02 UTC

**Comment by stefan2410** [comment] 2017-12-08 03:15
Then something in Nuget is wrong. 

Version | Downloads | Last updated

1.6.0 (current version) | 267 | 3 days ago
1.6.0-preview-001 | 1,550 | 24 days ago
1.5.2 | 7,114 | a month ago

Really I did not understand a bit  of your answer.

**Comment by damonbarry** [comment] 2017-12-08 22:49
@stefan2410 If a package is published with version 1.6.0-preview-001, and then a package comes along with version 1.6.0, it's very normal to assume that the latter package is the stable version of the former, and in fact that's usually the case.

But in this case, things happened a little differently. Some new functionality (specifically, support for "modules" needed by [Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/)) was released in a _preview_ package, which necessitated (1) a +1 minor bump of the then-current stable package and (2) a preview flag. Later, some unrelated changes for device provisioning were released in a _stable_ package, which also necessitated a minor bump. This means that the 1.6.0 preview package is not a really a preview of the 1.6.0 package. It's a preview of what was _forecast_ to be the 1.6.0 package, but the forecast was wrong.

The next preview package for the module features will be a minor bump of the now-current stable package, i.e., 1.7.0-preview-001.

Obviously this breaks assumptions, but I don't think it breaks the [semver](https://semver.org/) rules. There are no guarantees in a preview release, so it's as though the preview changes were rolled back for the stable release, and they'll be reintroduced for the next preview release.

**Comment by stefan2410** [comment] 2017-12-08 23:09
@damonbarry  thanks for the explanation.
We need the new functionality and this is the reason that we use the preview release. Of course, I know that changes happen in preview features, but as I understand this is not the case and  I should not change  our code. Simply I should re-install the 1.6.0-preview-001 and wait for the 1.7.0-preview-001.
The problem with Nuget probably  creates confusion, because it proposes updates to the stable version, as you can see my screen-shots in my other question
https://github.com/Azure/azure-iot-sdk-csharp/issues/278
