### ISSUE TITLE
Disconnect renders DeviceClient useless - The semaphore has been disposed.

### ISSUE THREAD

**Issue by domdeger** [Azure/azure-iot-sdk-csharp#1137] opened 2019-11-22 13:28 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp2.2 
- **Device:** Laptop, Raspberry PI3 
- **SDK version used:** Microsoft.Azure.Devices.Client v1.21.2 

## Description of the issue:
A device client which has been connected to an IoT-Hub and used to transfer telemetry does not recover from longer connection loss. So if I start the linked code with available network connection everything works fine. Telemetry arrives at the hub and method triggers are received.

But if you shutdown the network connection for approximatly three to five minutes the DeviceClient starts throwing System.ObjectDisposedExceptions with attached Stacktrace which does not seem to be expected behaviour.

Furthermore it persists after restoring the network connection.

## Code sample exhibiting the issue:
See https://gist.github.com/domdeger/0f192e46c3e40e3161fc195c827d3e4a

## Console log of the issue:
`   
The semaphore has been disposed.
at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)`

**Comment by domdeger** [comment] 2019-11-22 14:26
As I found out recently this issue seems to be related with AMQP. Switching the client to MQTT seems to resolve the issue. But for some use cases MQTT may not be feasible.

**Comment by davilu** [comment] 2019-11-22 19:23
@domdeger Thanks for reporting this issue. The `SemaphoreSlim` you're referring will be disposed only when device client `CloseAsync` or `Dispose` get called. Could you please capture ETL log and check if there is any `dispose` event? To capture the log, please refer to https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by davilu** [comment] 2019-11-22 23:08
@domdeger  I found the cause and will fixed in coming release.

**Comment by davilu** [comment] 2019-11-24 21:29
@domdeger It was fixed in PR above. Please have a try. Thanks for reporting the issue.

**Comment by davilu** [comment] 2019-12-18 05:04
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment] 2019-12-18 05:04
@domdeger, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-18 05:04 UTC
Labels: bug, fix-checked-in

**Comment by RoyMalka** [comment] 2020-03-22 15:57
Happen to me on version 1.29.0-preview-004, any news when it should be fix ?

**Comment by zammitt** [comment] 2020-03-30 17:00
This happened to me on 1.29.0-preview-004 as well.  

```
System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass28_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass20_0.<<EnableStreamsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableStreamsAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.EnableStreamAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
```

**Comment by cjenp** [comment] 2020-07-17 11:04
Happened to me on 1.21.3 and 1.25. Switching to TransportType.Mqtt resolves the issue but we would like to use Ampq.

**Comment by abhipsaMisra** [comment] 2020-07-17 16:23
Would you mind trying out the latest packages, and see if you still see this error:
preview: Microsoft.Azure.Devices.Client.1.29.1-preview-002
GA: Microsoft.Azure.Devices.Client v1.27.0

**Comment by cjenp** [comment] 2020-07-20 11:32
I tried both of them today and had the same problem. We settled on using mqtt until this gets fixed. If I find some spare time, I will try to provide a sample that reproduces this bug.

**Comment by abhipsaMisra** [comment] 2020-07-30 23:45
From the exception stack trace, the exception is from `SemaphoreSlim _lock` in `AmqpConnectionHolder` which will be disposed when `DeviceClient` function `CloseAsync` or `Dispose ` is called. Please share sample code with us.
