### ISSUE TITLE
net451 SDK does not support unix:// scheme for workload url

### ISSUE THREAD

**Issue by andrewhickman** [Azure/azure-iot-sdk-csharp#1016] opened 2019-07-26 15:44 UTC
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64, 
- **Application's .NET Target Framework :** net472 
- **Device:** Azure VM
- **SDK version used:** 1.29.0-preview-002 (also tested with 1.20.3

## Code sample exhibiting the issue:
I have a minimal repository to reproduce this issue [here](https://github.com/andrewhickman/azure-iot-sdk-csharp-issue-1016-repro). The initial commit reproduces the issue and the next commit fixes it by using the netstandard2.0 package.

## Description of the issue:
When using the SDK from .NET Framework with a default IoT Edge configuration, I get the following error on calling `await ModuleClient.CreateFromEnvironmentAsync(TransportType.Mqtt_Tcp_Only)`:
```
Unhandled Exception: System.InvalidOperationException: ProviderUri scheme is not supported
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpClientHelper.GetHttpClient(Uri providerUri)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.<GetTrustBundleAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.<CreateInternalClientFromEnvironmentAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SampleModule.Program.<Main>d__0.MoveNext() in C:\app\SampleModule\Program.cs:line 11
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SampleModule.Program.<Main>(String[] args)
```
If I manually swap out the DLL for the netstandard2.0 version of the SDK it works as expected.

The problem seems to happen when processing the default `workload_uri` value of `unix:///C:/ProgramData/iotedge/workload/sock`, at this [line](https://github.com/Azure/azure-iot-sdk-csharp/blob/b0c096c0dd624ef0f2af91cb738cfd9cadbdf92d/iothub/device/src/HsmAuthentication/HttpClientHelper.cs#L29). 

To me this difference in behaviour between the two packages was quite surprising, especially since it is not easy to force use of the netstandard package. (The least hacky way I found was to insert another netstandard project into the dependency chain between the net472 application and the SDK, but that came with issues like [this](https://stackoverflow.com/questions/56697901/why-is-this-nuget-dependency-missing-when-compiling-net-framework-project-depen?noredirect=1&lq=1))

**Comment by prmathur-microsoft** [comment] 2019-07-26 22:13
Thanks for filing this issue. We will fix this.

**Comment by bikamani** [comment] 2019-07-29 23:36
Hi @andrewhickman ,

Thanks for filing GitHub issue. Which dll version of SDK were you using before 2.0? Can you tell exact process of what you mean by "manually change swap out the DLL for the netstandard2.0 version of the SDK" ?

Thanks,
Binal

**Comment by andrewhickman** [comment] 2019-07-30 08:58
Initially I was using the `net451` package (version 1.29.0-preview-002). 

To swap for the `netstandard2.0` package I just manually copied it into the build output, (see this commit)[https://github.com/andrewhickman/azure-iot-sdk-csharp-issue-1016-repro/commit/126ab74be2e8971b120fa4cd49fbfc6ffbb386f0]

**Comment by bikamani** [comment] 2019-07-30 21:51
Thanks for the information. How are you creating your application/project - command line/any tools? Also let us know what document/process are you following for modules, edge configuration?

**Comment by andrewhickman** [comment] 2019-07-31 08:44
I created the solution with the [Azure IoT Edge vscode plugin](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-edge) with the 'New IoT Edge Solution' command. I replaced the default csharp module with a basic .NET Framework module based on [this template](https://github.com/microsoft/dotnet-framework-docker/tree/c65bd3054a3bfb0ee098b6dbd82194d806d65d85/samples/dotnetapp).

To deploy I am also just using the commands from the extension
- Generate IoT Edge Deployment Manifest
- Create IoT Edge Device
- Create Deployment for Single device

The module configuration is just what you see in the repo
- https://github.com/andrewhickman/azure-iot-sdk-csharp-issue-1016-repro/blob/master/deployment.template.json
- https://github.com/andrewhickman/azure-iot-sdk-csharp-issue-1016-repro/blob/126ab74be2e8971b120fa4cd49fbfc6ffbb386f0/modules/SampleModule/module.json

**Comment by bikamani** [comment] 2019-07-31 17:58
@andrewhickman Thank you! 

We are looking further into this and will update once we know the root cause.

**Comment by bikamani** [comment] 2019-08-02 21:21
@andrewhickman What is the requirement of doing this? - "I replaced the default csharp module with a basic .NET Framework module based on this template." Trying to understand to help better.

**Comment by andrewhickman** [comment] 2019-08-02 21:45
The default module is .net core but we need to use some .net framework libraries

**Comment by bikamani** [comment] 2019-08-02 22:05
@andrewhickman Thanks for quick response. .NET framework project is pointing to net451 SDK dll as you mentioned which is appropriate but .NET framework 451 does not have Unix socket support on Windows. This is the reason swapping with SDK .NET standard 2.0 version dll worked. Unfortunately, for edge modules .NET core 2.1/.NET standard 2.0 is a requirement.

**Comment by andrewhickman** [comment] 2019-08-02 22:32
Is there any reason the unix sockets implementation will not work on .net framework? I would expect changing the `#if NETSTANDARD1_3 || NETSTANDARD2_0` lines to include .net framework to work since the netstandard dll works ok from a .net framework application.

**Comment by bikamani** [comment] 2019-08-02 22:40
@andrewhickman Good question, this is .NET Framework support question. If you refer the link: https://github.com/dotnet/standard/blob/master/docs/versions.md, net451 targets .NET standard version 1.2 and not 1.3/2.0 (which has unix socket support for windows).

**Comment by andrewhickman** [comment] 2019-08-02 23:14
Ah, so the netstandard version worked because my project is using .NET framework 4.7.2 which *does* support netstandard2.0.

Would it be possible to publish another package targeting net46 or later? Then it would be able to use the netstandard 1.3/2.0 features. Hopefully my 4.7.2 project would then pull in that package by default...

**Comment by bikamani** [comment] 2019-08-02 23:29
@andrewhickman 

Here is the link for reference to understand precedence: http://nugettoolsdev.azurewebsites.net/4.9.0-rtm.5658/framework-precedence?framework=net47&exludedIdentifiers=

Our team will look into for adding support for this, we do not know the ETA at this point though. I will mark this issue as an enhancement and keep it open.

**Comment by abhipsaMisra** [comment] 2020-04-25 05:55
@andrewhickman After looking at similar issues that customers were facing with .net fm targeting applications defaulting to using the .net451 dll, we decided to add explicit support for .net472, and deprecate the .net standard 1.3 dll. As a result, we now publish 3 variants of the sdk for windows - .net451, .net472 and .net standard 2.0. Your .netfm application should now target the highest available compatible dll (.net472, in our case), which is .net standard 2.0 compliant, and you should be able to use unix sheme for your http provider uri.

I am closing this with the above resolution, feel free to re-open this and let us know if you still an issue.

**Comment by az-iot-builder-01** [comment] 2020-04-25 05:55
@prmathur-microsoft, @andrewhickman, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by abhipsaMisra** 2020-04-25 05:55 UTC
Labels: IoTSDK, enhancement
