### ISSUE TITLE
Missing methods in 1.17.0-preview-007

### ISSUE THREAD

**Issue by Hammatt** [Azure/azure-iot-sdk-csharp#498] opened 2018-06-05 04:05 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Pro x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp2.0
- **Device:** <DEVICETYPE> Surface Pro
- **SDK version used:** <VERSION> Microsoft.Azure.Devices.Client 1.17.0-preview-007

# Description of the issue:

I was going through updating my nuget packages, for this package it was from 1.17.0-preview-003 to 1.17.0-preview-007 and found that `DeviceClient.SetInputMessageHandlerAsync` is gone, and `DeviceClient.SendEventAsync\2` is also gone, leaving only the method for sending messages up to the cloud and not between modules.

I have found that downgrading to 1.17.0-preview-006 brings these methods back

# Code sample exhibiting the issue:

```C#
await deviceClient.SetInputMessageHandlerAsync(inInputName, inMessageHandler, inUserContext);
```
or
```C#
await deviceClient.SendEventAsync(inOutputName, inMessage);
```

# Console log of the issue:

![image](https://user-images.githubusercontent.com/4745771/40954494-ef578f80-68d8-11e8-9ec9-c2a9979b7947.png)

**Comment by zolvarga** [comment] 2018-06-05 17:26
@Hammatt 

The API you are trying to call on the DeviceClient has been moved. We decided to have DeviceClient and ModuleClient functionality separated. This design will eliminate confusions around the DeviceClient and ModuleClient functionalities.
If you want to work with as a ModuleClient please use the ModuleClient object from now on. All the APIs you used before for ModuleClient are there.

Best Regards,
Zoltan

**Comment by zolvarga** [comment] 2018-06-05 17:27
Closed as by design and the question has been answered.

**Closed by zolvarga** 2018-06-05 17:27 UTC
