### ISSUE TITLE
Device ConnectionState does not get set when using UWP versions of nuget packages

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#24] opened 2017-01-10 22:09 UTC
When using the .Net version of the nuget packages Microsoft.Azure.Devices and Microsoft.Azure.Devices.Client, the code below sets the ConnectionState property correctly. However, when you use the exact same code from a UWP project with the respective nuget packages, the property never gets set. 

`
		public static void TestConnectionState()
		{
			var maxSeconds		= 30;
			var deviceManager	= RegistryManager.CreateFromConnectionString(hubOwnerConnectionString);
			var deviceClient	= DeviceClient.CreateFromConnectionString(deviceConnectionString);
			var message			= new Microsoft.Azure.Devices.Client.Message();

			deviceManager.OpenAsync().Wait();
			var device = deviceManager.GetDeviceAsync(deviceId).Result;
			if (device?.ConnectionState != DeviceConnectionState.Disconnected)
				throw new Exception();

			deviceClient.OpenAsync().Wait();
			deviceClient.SendEventAsync(message).Wait();

			int counter = 0;
			do
			{
				Task.Delay(1000).Wait();
				device = deviceManager.GetDeviceAsync(deviceId).Result;
			} while (++counter < maxSeconds && device.ConnectionState != DeviceConnectionState.Connected);

			if (device.ConnectionState != DeviceConnectionState.Connected)
				throw new TimeoutException();
			else
				Debug.WriteLine($"It took about {counter} seconds for the state to change.");

			try
			{
				deviceClient.CloseAsync().Wait();
			}
			catch (AggregateException ex)
			{
				//why isn't this universally implemented???
				if (! (ex.InnerException is NotImplementedException))
					throw;
			}
		}
`

**Comment by arturl** [comment] 2017-01-12 18:34
I'll take a look

**Comment by olivierbloch** [comment] 2017-01-17 21:38
Hi @v-tbert 
You are actually seeing the expected behavior.
First, as mentioned in the [documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-heartbeat), the "connectionState" value should NOT be used in production, but only in debug and development. The reason for this is because the value is not updated for all protocols (it will never be set to true when using HTTP for example), and the meaning of this flag is more "the device was seen at least once in the last x minutes" (X being the TCP idle time for Azure load balancer) rather than an actual indicator of whether or not the device is connected.
We know that this can be confusing and I am about to send out a proposal to the team to have a proper device heartbeat mechanism implemented that would be protocol agnostic.

Now that said, when you use the UWP NuGet package, the device client is created using HTTP by default (as AMQP support for UWP is only arriving now) while when using the package in a .Net app the default protocol used is AMQP. The connectionState is indeed never set when connecting a device running a UWP app.
We should definitively document this and also set the default protocol to the same when possible to ensure the behavior is the same.
I will close this issue as it is NOT a bug in the clients, but a limitation of the service.

**Closed by olivierbloch** 2017-01-17 21:38 UTC
Labels: bug, CSS
