### ISSUE TITLE
Microsoft.Azure.Devices.Client incorrectly determines .NET Standard support

### ISSUE THREAD

**Issue by terrajobst** [Azure/azure-iot-sdk-csharp#1592] opened 2020-10-02 01:53 UTC
This issue was [reported by a customer](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/comment-page-3/#comment-7383).

1. Use .NET 5 preview.
2. Install `Microsoft.Azure.Devices.Client`

### Expectation

Stuff works.

### Actuality

The customer gets an exception:

```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at Microsoft.Azure.Devices.Client.Common.ReadOnlyMergeDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair>.get_Count()
```

It seems the root cause is a fragile check in the MSBuild targets:

```XML
  <PropertyGroup>
    <SupportsNetStandard20AndAbove Condition="'$(TargetFramework)' == 'netstandard2.1' Or '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net472'">true</SupportsNetStandard20AndAbove>
  </PropertyGroup>
```

What are you trying to achieve by this method?

**Comment by azabbasi** [comment] 2020-10-02 22:46
We are working on the fix. Will update the issue once the fix is released with a new version.

**Comment by abhipsaMisra** [comment] 2020-10-02 23:30
Duplicate of #1562 , the fix will apply to both.

**Comment by az-iot-builder-01** [comment] 2020-10-03 17:55
@terrajobst, @azabbasi, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by azabbasi** [comment] 2020-10-03 17:57
Fix has been checked in. We will update the issue when a release is published.

**Comment by terrajobst** [comment] 2020-10-06 15:35
@azabbasi 

> Fix has been checked in. We will update the issue when a release is published.

Thanks for reopening this to keep me posted. I have posed a question here: https://github.com/Azure/azure-iot-sdk-csharp/issues/1562#issuecomment-704353797

**Comment by azabbasi** [comment] 2020-10-12 23:36
@terrajobst Azure IoT SDK team has released a new version of the SDK that include fixes for this issue. 
https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-10-8

Please confirm and we will close the Issue afterwards.

**Comment by abhipsaMisra** [comment] 2020-10-30 05:49
Closing this since this has now been released.

**Closed by abhipsaMisra** 2020-10-30 05:49 UTC
Labels: IoTSDK, bug, fix-checked-in
