### ISSUE TITLE
Default retry mechanism throws exception when network comes back

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1083] opened 2019-10-12 18:45 UTC
Not setting up any retry parameters, the default is that it keeps retrying, and when the network comes back, it continues its work. This is what happens when the network is down for a short time (less than a minute). If the network is down for an extended time (e.g. 5-10 minutes), then an exception will be thrown when the network comes alive. This is quite consistent, easy to reproduce. I am using Azure.Devices.Client 1.21.1. The test code is with mqtt, but the behavior seems protocol independent. 
I tested this behavior with the following code:

        static ModuleClient moduleClient;

        static async Task Boot()
        {
            try
            {
                moduleClient = ModuleClient.CreateFromConnectionString("HostName=xxx.azure-devices.net;DeviceId=viktestdev;ModuleId=$edgeAgent;SharedAccessKey=xxx", TransportType.Mqtt_Tcp_Only);
                await moduleClient.OpenAsync();

                var messages = new Message[] { new Message(new byte[] { 0x02, 0x03, 0x04 }),
                                               new Message(new byte[] { 0x02, 0x03, 0x04 }),
                                               new Message(new byte[] { 0x02, 0x03, 0x04 }),
                                               new Message(new byte[] { 0x02, 0x03, 0x04 }),
                                               new Message(new byte[] { 0x02, 0x03, 0x04 }) };

                Console.WriteLine("kill the net");
                Console.ReadLine();

                for (var i = 0; i < 10; i++)
                {
                    await Task.Delay(5000);
                    Console.WriteLine("sent");
                    await moduleClient.SendEventBatchAsync(messages);
                }                
            }
            catch (Exception ex)
            {
                Console.WriteLine("went bad: " + ex.Message);
            }
        }

The code has a "kill the net" message, when I turn off the Wi-fi. Then I wait some minutes (e.g 5), and turn back the Wifi. In the next few seconds an exception is thrown:

![image](https://user-images.githubusercontent.com/51135538/66706197-b5e6a100-ece4-11e9-8e94-5cd729a281e3.png)

This happens with other calls, too (eg twin update). The call stack:
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendEventAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.InternalClient.<SendEventBatchAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModuleClientTest.Program.<Boot>d__1.MoveNext() in D:\Dev\ModuleClientTest\ModuleClientTest\Program.cs:line 41

Inner exception call stack:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<SendEventAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__23`1.MoveNext()

**Comment by timtay-microsoft** [comment] 2019-11-05 22:28
There is a concept of device operation timeout that the client object maintains which sets a default timeout for all operations when no cancellation token is provided. In your case, since you aren't changing the device operation timeout, it defaults to 4 minutes. This timeout applies regardless of protocol.

Your call to ```SendEventBatchAsync(...)``` will fail since your network is down, and the SDK's retry policy will reattempt to send the batch until you hit this device operation timeout. Once you hit this timeout, the SDK will throw the OperationCanceledException that you are seeing. This is expected behavior.

There are two ways to change how the SDK handles retry logic timeouts:


You can configure the device operation timeout to be longer
```
client.OperationTimeoutInMilliseconds = 5 * 60 * 1000; // 5 minutes
```

You can pass your own cancellation token into the method so that the device operation timeout won't apply.
```
await moduleClient.SendEventBatchAsync(messages, someCancellationToken);
```

**Comment by vipeller** [comment] 2019-11-06 00:38
@timtay-microsoft I think this is something different. I know that the SDK has the concept of 'operation timeout'. But also I remember that there has been a discussion about this behavior changed, and from a certain version the 'operation timeout' is ignored and the SDK keep trying to execute the given operation. See this issue:

https://github.com/Azure/azure-iot-sdk-csharp/issues/1079

I think you are explaining the first case in the diagram below. But what happens is the second case:

![image](https://user-images.githubusercontent.com/51135538/68258011-2635c900-ffea-11e9-85f4-26d0945bf5a8.png)

I would be ok if the SDK came back with an exception after timeout. But if the network is down for 2 days, then the exception will be thrown after to days, when the network comes back, not e.g. 4 minutes which is the timeout. I think David Lu looked at the code already and may give some hints about the nature of this problem

**Comment by timtay-microsoft** [comment] 2019-11-13 20:24
I see. I would also expect the exception to be thrown when the operation timeout expires, not when the connection is re-established. We'll spend some time investigating this

**Comment by vipeller** [comment] 2019-11-13 20:27
@timtay-microsoft sure. Talk to David, he might have more context, also maybe it's been fixed (but not released yet)

**Comment by davilu** [comment] 2019-12-18 05:09
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment] 2019-12-18 05:09
@davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-18 05:09 UTC
Labels: fix-checked-in, investigation-required
