### ISSUE TITLE
[module preview] Cannot connect to edgehub on host with FQDN: MQTT should iterate through all DNS records

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-csharp#495] opened 2018-05-29 07:22 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10, Docker 18.03.1-ce-win65 linux container mode
- **SDK version used:** <VERSION> 
1.6.0-preview-001

# Description of the issue:

I am trying to run an edge module in local machine (without docker). The steps are as follows
1. Start edgeHub container with all credential, network and volume. (Port is exposed correctly)
2. Open the csharp module in VSCode, and inject the connection, certificate value as environment variable
3. Run the csharp module, it cannot connect the edgehub. (The gatewayhost is the FQDN of the current machine)

However, if I run the csharp module on another machine and connect the same edgehub again. Connection could be success.

Tried to investigate, it seems the issue is caused by 
https://github.com/Azure/azure-iot-sdk-csharp/blob/b72c486cfc142b04bde16e1deb153704d055dfaf/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L513

The code only get the first IPAddress resolved by dns. However, in the above scenario, the first IP could not connect, while other entry could work.

**Comment by zolvarga** [comment] 2018-05-29 18:07
@adashen 

Could you please provide what you run please?

Best Regards,
Zoltan

**Comment by adashen** [comment] 2018-06-05 06:04
The code I run could be found at 
https://github.com/Azure/dotnet-template-azure-iot-edge-module/blob/v1.4.0/content/dotnet-template-azure-iot-edge-module/CSharp/Program.cs#L88 

The point here is, the code is in native process, not in docker container. And edgeHub is started in the container. I tried to get the module credential (connection string) for the module, and send it to the native dotnet core process to connect to edgeHub

**Comment by varunpuranik** [comment] 2018-06-11 17:13
Yes, this is a Edge tooling scenario when you are trying to develop Edge modules. At that time, the module won't be run inside a container for ease of development and debugging. So yes, as such this is a valid scenario.

**Comment by yzhong94** [comment] 2018-06-20 00:32
@CIPop @zolvarga any update on this issue?

**Comment by CIPop** [comment] 2018-06-20 16:46
After reading more carefully, this is a duplicate of https://github.com/Azure/azure-iot-sdk-csharp/issues/352. Closing 352 as a duplicate to this one since it now has more impact.

**Comment by CIPop** [comment] 2018-06-20 16:47
@varunpuranik, any idea why this would happen:

> the first IP could not connect, while other entry could work.

**Comment by adashen** [comment] 2018-06-21 01:43
Docker only expose the 8883 port to the host ipv4 ips. And the first ip is an ipv6 one. And it could not be connected

**Comment by CIPop** [comment] 2018-06-21 18:41
Fixed by #530 .

**Closed by CIPop** 2018-06-21 18:41 UTC
Labels: bug
