### ISSUE TITLE
Websockets tests was Ignored on IoTHub Service Client

### ISSUE THREAD

**Issue by mamokarz** [Azure/azure-iot-sdk-csharp#318] opened 2018-01-03 18:09 UTC
Most of the Web socket tests for the IoTHub Service Client are masked to be Ignored. It must be fixed and re-enabled.

**Comment by CIPop** [comment] 2018-01-09 02:57
@mamokarz please add (at least a few) test names. 

I've tried to keep most of the tests disabled tracked with GitHub issues.  Are these already tracked with a TODO?

**Comment by timtay-microsoft** [comment] 2020-02-07 23:56
Closing this as it is a duplicate of #581

**Comment by az-iot-builder-01** [comment] 2020-02-07 23:56
@mamokarz, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-02-07 23:56 UTC
Labels: test bug
