### ISSUE TITLE
[Bug Report] : Edge module is unable to send the updated sas token to edge hub

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-iot-sdk-csharp#1810] opened 2021-03-03 22:26 UTC
# Context

- **OS, version, SKU and CPU architecture used:** <VERSION> (Windows Server 2019)
- **Application's .NET Target Framework :** <NETVERSION>   .NET Core 3.1
- **Device:** <DEVICETYPE> (Windows Sever 2019 Azure VM)
- **SDK version used:** IoT device C# SDK **1.35.0** for module creation for IoT Edge

## Description of the issue
**Reproduction steps**

1.) Create custom module
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module-windows?view=iotedge-2018-06
Use AMQP protocol to connect custom module to edgeHub module
2.) Keep the module running

**Actual result**
Module disconnect from edgeHub after 1 hour as the module doesn't send SAS token refresh. This happens for both AMQP and MQTT protocol. This seems specific to Windows Server 2019 and doesn't happen on Ubuntu 18.04.

**Expected result**
On AMQP protocol, SAS token refresh should happen on the fly and the module **shouldn't** disconnect

**Comment by abhipsaMisra** [comment] 2021-03-04 16:52
From analysis of the logs, we can see that the client sdk does generate the updated sas token as expected, but fails to send it across to edge hub. There is a socket exception that occurs, which I'm seeing only on windows based edge devices.

**Comment by abhipsaMisra** [comment] 2021-03-09 17:43
The socket exception that was occurring on Windows based edge devices has been root caused to the custom implementation of Unix sockets that we had taken a dependency on. The .NET framework provides native support for Unix sockets from ns2.1 onwards, and updating the reference to System.Net.Sockets.UnixDomainSocketEndPoint for frameworks > ns2.1 solves this issue.
This issue is being addressed in #1816

**Comment by abhipsaMisra** [comment] 2021-03-18 15:51
The issue of an edge module not sending an updated sas token cannot be replicated and the previous SocketException has now been resolved.

**Comment by abhipsaMisra** [comment] 2021-03-25 00:10
The fix for unix sockets has now been released, closing this issue: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-03-18

**Closed by abhipsaMisra** 2021-03-25 00:10 UTC
Labels: IoTSDK, bug, fix-checked-in
