### ISSUE TITLE
ModuleClient.SendEventAsync fails with timeout when edgeHub is restarted

### ISSUE THREAD

**Issue by dylanbronson** [Azure/azure-iot-sdk-csharp#1242] opened 2020-02-18 20:56 UTC
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows 10 Pro (amd64)
- **Application's .NET Target Framework :** <NETVERSION> 2.1
- **Device:** <DEVICETYPE> Azure VM
- **SDK version used:** <VERSION> Microsoft.Azure.Devices.Client 1.22.0 and 1.21.3

## Description of the issue:
ModuleClient.SendEventAsync fails with a timeout when edgeHub is restarted.

Steps to repro: 
1. Set up IoTEdge on Windows
2. Send messages through ModuleClient.SendEventAsync from module to IotHub (through edgeHub) and see messages go through successfully (using AMQP).
3. Restart edgeHub

At this point, the module sending messages will hang and then timeout after ~4 minutes. 

## Code sample exhibiting the issue:
We are using this module with latest edge runtime (latest edgeAgent and edgeHub): https://github.com/Azure/iotedge/blob/master/test/modules/load-gen/Program.cs

## Console log of the issue:
[2020-02-18 20:34:55.109 DBG] Allocated new list & buffer [1185] of size 1024
[2020-02-18 20:34:55.151 INF] Sent message successfully: sequenceNumber=1185
[2020-02-18 20:34:55.177 DBG] Allocated new list & buffer [1186] of size 1024
[2020-02-18 20:38:55.198 ERR] [SendEventAsync] Sequence number 1186, BatchId: 0785bfae-72dc-4f7f-9bab-5e38553fe31c;
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at LoadGen.Program.SendEventAsync(ModuleClient client, Guid batchId, String trackingId, Int64 messageId) in C:\agent\_work\6\s\test\modules\load-gen\Program.cs:line 117
   at LoadGen.Program.Main() in C:\agent\_work\6\s\test\modules\load-gen\Program.cs:line 51
[2020-02-18 20:38:55.212 DBG] Allocated new list & buffer [1187] of size 1024
[2020-02-18 20:42:55.231 ERR] [SendEventAsync] Sequence number 1186, BatchId: 0785bfae-72dc-4f7f-9bab-5e38553fe31c;
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at LoadGen.Program.SendEventAsync(ModuleClient client, Guid batchId, String trackingId, Int64 messageId) in C:\agent\_work\6\s\test\modules\load-gen\Program.cs:line 117
   at LoadGen.Program.Main() in C:\agent\_work\6\s\test\modules\load-gen\Program.cs:line 51
[2020-02-18 20:42:55.232 DBG] Allocated new list & buffer [1188] of size 1024
[2020-02-18 20:42:57.504 INF] Sent message successfully: sequenceNumber=1186
[2020-02-18 20:42:57.536 DBG] Allocated new list & buffer [1189] of size 1024
[2020-02-18 20:42:57.564 INF] Sent message successfully: sequenceNumber=1187
[2020-02-18 20:42:57.652 DBG] Allocated new list & buffer [1190] of size 1024

**Comment by davilu** [comment] 2020-02-25 18:00
@dylanbronson  Seems it is caused by DNS caching with IP changes after edge hub restart. I think this issue could be closed.

**Comment by prmathur-microsoft** [comment] 2020-03-16 20:28
As per the comment above I will close this issue. Please feel free to reopen if you have nay further questions.

**Comment by az-iot-builder-01** [comment] 2020-03-16 20:28
@dylanbronson, @davilu, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-03-16 20:28 UTC
