### ISSUE TITLE
setting properties to null in the device twin results in inconsistent representation

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-csharp#86] opened 2017-04-13 23:04 UTC
When we set the value of a property in the device twin to null, it seems that its presence keeps getting toggled on and off every time we set it to null.

For example, in device explorer, and starting from a clean device twin, if we:

| Step #	| Send	| Resulted document	| Notification sent to client|
|-----|------|------|-----|
|1	|“a” : “1”	|“a” : “1”	| Yes (a, null) |
|2	|“a” : null	|&lt;nothing&gt;	| Yes (a, null)
|3	|“a” : null	|“a” : null	| Yes (a, null)
|4	|“a” : null	|&lt;nothing&gt;	| Yes (a, null)
|5	|“a” : null	|“a” : null	| Yes (a, null)

I expect that setting a value to null will always yield the same result.

**Comment by olivierbloch** [comment] 2017-06-05 15:58
@gmileka 
a fix has been deployed to the service. could you please retry and let us know if the issue is gone for you?
Thanks

**Comment by tameraw** [comment] 2017-06-05 16:41
@gmileka - Fix has been deployed.

**Closed by tameraw** 2017-06-05 16:41 UTC
Labels: bug, service
