### ISSUE TITLE
Xamarin Android does not support AMQP due to system.configuration not supported

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-iot-sdk-csharp#918] opened 2019-04-23 10:58 UTC
Just updated to the latest 1.20.0 version and noticed that it fails to create an AMQP connection.

This main exception is `The type initializer for 'Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector' threw an exception.System.TypeInitializationException: The type initializer for 'Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.PlatformNotSupportedException: Operation is not supported on this platform.`

Here's a subset of the call stack
```
at System.Configuration.ConfigurationManager.get_AppSettings () [0x00000] in <0e721f564ffa49e6b1d97ad7b9fda1f2>:0 
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.InitializeDisableServerCertificateValidation () [0x00000] in <c2e05c18251a439ba1de56793ae3a08e>:0 
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector..cctor () [0x0000d] in <c2e05c18251a439ba1de56793ae3a08e>:0 
```

I even tried to create a netstandard 1.3 library that has the IOT code in, but I think the way Xamarin is building causes the netstandard 2.0 version of the library to be used.

**Comment by nrandell** [comment] 2019-04-23 11:01
I've just reverted back to 1.19.0 and the code is working fine.

**Comment by kartben** [comment] 2019-05-14 23:38
I can confirm this also impact people targetting UWP on Win10 IoT

**Comment by omiimo** [comment] 2019-05-21 06:20
Facing the same issue in Xamarin. 
I am using Device Client SDK 1.20.1.

**Comment by CIPop** [comment] 2019-06-25 21:12
Thanks for reporting @nrandell!

Duplicate of #949

**Comment by az-iot-builder-01** [comment] 2019-06-25 21:12
@nrandell, @kartben, @omiimo, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-06-25 21:12 UTC
