### ISSUE TITLE
Exception with RegistryManager on Linux

### ISSUE THREAD

**Issue by StephaneAskardjian** [Azure/azure-iot-sdk-csharp#725] opened 2018-12-04 17:05 UTC
Hello,

We have a component that should be used on Linux and Windows.
Everything works fine on Windows but on Linux, we have an exception when we use RegistryManager with the exact same code.

Initialisation is fine but when we call a method, like GetDeviceAsync, we have something like this : 

System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: Failed to allocate SSL/TLS context, OpenSSL error - .
Arborescence des appels de procédure :
    at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)

OS is Ubuntu 16.04.5 x64 (the same as the Microsoft-hosted agent on VSTS)
OpenSSL version is 1.0.2g-1ubuntu4.13
Framework is .NET Core 2.1.500
Nuget is Microsoft.Azure.Devices 1.17.1

Thanks.

**Comment by CIPop** [comment] 2018-12-05 22:30
@karelz @davidsh FYI- the error appears to be .NET Core related based only on the stack.

@StephaneAskardjian there isn't sufficient information:

Please follow the guide here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs and also add the following providers : 
*Microsoft-System-Net-Http {bdd9a83e-1929-5482-0d73-2fe5e1c0e16d}: HTTP-related traces.
*Microsoft-System-Net-Http-WinHttpHandler {b71555b1-9566-5ce3-27f5-98405bbfde9d}: WinHttpHandler-related traces.
*Microsoft-System-Net-NameResolution {5f302add-3825-520e-8fa0-627b206e2e7e}: DNS-related traces.
*Microsoft-System-Net-Primitives {a9f9e4e1-0cf5-5005-b530-3d37959d5e84}: Traces related to core networking-related types.
*Microsoft-System-Net-Requests {3763dc7e-7046-5576-9041-5616e21cc2cf}: WebRequest-related traces.
*Microsoft-System-Net-Sockets {e03c0352-f9c9-56ff-0ea7-b94ba8cabc6b}: Sockets-related traces.
*Microsoft-System-Net-Security {066c0e27-a02d-5a98-9a4d-078cc3b1a896}: Security-related traces.

If there is any private information please open a Support Request to send us the data.

**Comment by StephaneAskardjian** [comment] 2018-12-10 15:42
Sorry for the late reply
Here is the traces.
[Traces.trace.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/2663758/Traces.trace.zip)

**Comment by StephaneAskardjian** [comment] 2019-01-11 15:46
Hello,

Someone could have more info on this issue ?

Thanks.

**Comment by davidsh** [comment] 2019-01-12 04:11
@bartonjs 
Have you seen this type of exception before from OpenSsl ?

>Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: Failed to allocate SSL/TLS context, OpenSSL error

**Comment by bartonjs** [comment] 2019-01-12 06:47
@davidsh I have not.  Perhaps low memory?

**Comment by StephaneAskardjian** [comment] 2019-01-15 13:59
Not a low memory issue on my side.

**Comment by prmathur-microsoft** [comment] 2019-01-16 00:18
@jenoola  - Could you please analyse logs to find a root cause of this issue?

**Comment by jenoola** [comment] 2019-01-22 18:58
@StephaneAskardjian I don't see the actual log that lists the exception (or maybe I don't have an app fpr opening it). Could you point me to the exact file in your zip?

**Comment by jenoola** [comment] 2019-01-30 22:08
@StephaneAskardjian as you were asked earlier, we need logs to be captured according to this guide https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by ewertons** [comment] 2019-07-22 22:20
Hi @StephaneAskardjian ,
this thread suggests this issue is related to .NET Core: https://github.com/dotnet/corefx/issues/35956
For which the .NET Core team provided a fix that was merged just 7 days ago, on 07/17/2019 (https://github.com/dotnet/corefx/pull/39297).
As of now, the last release from .NET core was on 07/09/2019 (https://github.com/dotnet/corefx/releases). Based on the average frequency they release, this fix should be out within 2 or 3 weeks (this is not confirmed, this is just based on an estimation of their release cadence).

**Comment by bikamani** [comment] 2019-08-23 22:52
I see the dotnet issue has been resolved on the link posted by @ewertons .

@StephaneAskardjian Has this been tried with latest release of .NET core?

**Comment by bikamani** [comment] 2019-08-30 20:10
Closing the issue. If you still see are seeing this exception with new release of .NET core, feel free to reopen it.

**Comment by az-iot-builder-01** [comment] 2019-08-30 20:10
@CIPop, @StephaneAskardjian, @davidsh, @bartonjs, @prmathur-microsoft, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-08-30 20:10 UTC
Labels: dependency-issue
