### ISSUE TITLE
Disconnected - Bad Credential - MQTT transport

### ISSUE THREAD

**Issue by davidmaiden** [Azure/azure-iot-sdk-csharp#1135] opened 2019-11-21 12:26 UTC
We are using Microsoft.Azure.Devices.Client in our code and recently upgraded the nuget package from 1.20.1 to 1.21.1 for our latest release and some very unexpected stuff has started happening.

When a Disconnected event is raised, the Device Client seems to be reporting a reason of Bad_Credentials which has never happened before unless the device was disabled at IoT Hub.

When our application detects a Disconnected event that isn’t Bad_Credentials, we dispose of the Device Client, recreate it and re-connect (OpenAsync). If Bad_Credential is detected in the reason we take another course of action in the code (since we assume that the device has been disabled at IoT Hub). This has been working for 700+ devices live in the field for 9 months now until upgrading to 1.21.1 of the Nuget package.

I can see from cloning the git repo that this reason is reported in RetryDelegatingHandler.cs in HandleConnectionStatusExceptions method in the Microsoft.Azure.Devices.Client.Transport namespace in response to an UnauthorizedException however it doesn’t look as if this has been changed recently (that would affect this anyway). There do seem to be several changes made in the base class for the RetryDelegatingHandler – MqttTransportHandler that may affect this.

Is this an intended action for the latest release or has been introduced by accident?

**Comment by davilu** [comment] 2019-11-21 19:29
@davidmaiden Could you please try with latest version 1.21.2? Meanwhile there is no change for AMQP exception mapping since 1.20.1. The only place it will give Bad_Credentials is device got kicked off by server and reconnect with a connect ACK failure.

**Comment by timtay-microsoft** [comment] 2019-11-21 23:11
> When a Disconnected event is raised, the Device Client seems to be reporting a reason of Bad_Credentials which has never happened before unless the device was disabled at IoT Hub.

What was the reason the SDK reported for you when you used 1.20.1?

**Comment by davidmaiden** [comment] 2019-11-22 09:51
> > When a Disconnected event is raised, the Device Client seems to be reporting a reason of Bad_Credentials which has never happened before unless the device was disabled at IoT Hub.
> 
> What was the reason the SDK reported for you when you used 1.20.1?

We aren't monitoring for anything other than Bad_Credential as that was indicating "disabled at hub" and thus a particular action, any other Disconnected event we are just tearing down and disposing DeviceClient and re-instantiating the connection.

Currently, (temporarily to get users working) we are now re-instatiating the connection for Bad_Credential too - this then reconnects ok with the same connection string so clearly not a bad credential in the first place.

**Comment by davidmaiden** [comment] 2019-11-22 10:01
> @davidmaiden Could you please try with latest version 1.21.2? Meanwhile there is no change for AMQP exception mapping since 1.20.1. The only place it will give Bad_Credentials is device got kicked off by server and reconnect with a connect ACK failure.

We will try 1.21.2 but just want to make the point that we are not using AMQP - we are using MQTT.

**Comment by davilu** [comment] 2019-11-22 19:27
@davidmaiden  If you still see the issue with 1.21.2, please open an ICM. We will need your hub and device info for server side support.

**Comment by davidmaiden** [comment] 2019-11-26 12:06
> @davidmaiden If you still see the issue with 1.21.2, please open an ICM. We will need your hub and device info for server side support.

I can confirm the issue is still happening with 1.21.2

**Comment by davilu** [comment] 2019-12-09 18:51
@davidmaiden Thanks for your understanding. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue.

**Comment by kartben** [comment] 2019-12-19 13:01
@davidmaiden sorry for asking something obvious here, but can you confirm that 1.21.1 still works as expected for you? Just want to make sure that the issue is indeed on the SDK side, and not IoT Hub actually rejecting the connections for some reason (ex. due to expired tokens)

**Comment by davidmaiden** [comment] 2019-12-19 15:50
> @davidmaiden sorry for asking something obvious here, but can you confirm that 1.21.1 still works as expected for you? Just want to make sure that the issue is indeed on the SDK side, and not IoT Hub actually rejecting the connections for some reason (ex. due to expired tokens)

No, it doesn't work as I expected in 1.21.1 or 1.21.2. 
The last known (by ourselves at least) version it was working as I expected was 1.20.1

**Comment by kartben** [comment] 2019-12-19 15:59
Just to clarify, since you say "the last know version it *was* working":
can you confirm that if you switch back to 1.20.1 SDK *today* it works as
expected?
To put it differently, I would like to make sure the issue is with the SDK,
and not "it worked x months ago ...when btw we were using a different
version of the SDK"

Thanks!

**Comment by davidmaiden** [comment] 2019-12-19 16:23
As per the initial report I raised on here, I can only say that everything was working as we expected (Bad_Credential only being raised when disabled at IoT Hub), we sent out a release with an updated package (1.21.1) and almost immediately we had unexpected behaviour among several of our users that had upgraded their app. It may not be with the SDK but I suspect it would be more than coincidental that something else went awry at exactly the same time as we send a release out. 
We removed the adverse functionality and just reported the Bad_Credentials event to App Center so we could monitor. We also upgraded the app again to 1.21.2 as suggested, and the event was still being raised regularly. App Center is telling us that this has been reported 182.5K times in the last 30 days by 202 users. 
Unfortunately, we are not in a position to downgrade back to 1.20.1 and release this to the user-base for mainly political reasons.

**Comment by timtay-microsoft** [comment] 2020-04-14 20:00
Closing this issue as the user needs to create an ICM in order to debug this further since we need hub and device identifiers that can't be shared here

**Comment by az-iot-builder-01** [comment] 2020-04-14 20:00
@davilu, @davidmaiden, @kartben, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-04-14 20:00 UTC
Labels: IoTSDK, customer-input-needed

**Comment by meladon1337** [comment] 2021-03-31 11:40
@davidmaiden Could you narrow down the problem?
