### ISSUE TITLE
Add feature to the registry manager

### ISSUE THREAD

**Issue by JakkeFiejest** [Azure/azure-iot-sdk-csharp#460] opened 2018-04-20 14:29 UTC
Hi everybody.
We are currently working on a project using IOT-hub, where devices need to be able to self register.
However, these devices can be behind a proxy server and there is currently no way to force using the a proxy server in the registry manager.
Would it be possible to add this feature?

If it is needed, I want to add it myself to the codebase.

**Comment by zolvarga** [comment] 2018-04-24 19:00
@JakkeFiejest 

We are not supporting the proxy scenario but you can set up a proxy on Windows and Linux but we have not tested it. We don't have a plan to add this feature in the near future.

Best Regards,
Zoltan

**Comment by JakkeFiejest** [comment] 2018-04-25 14:30
@zolvarga ,
The problem is that our system needs to support a different proxy per application that is running on it.
(It is a Point Of Sale application, which is mostly running in propriety networks, and external breakouts are done via those proxies)
The fact that this is unsupported in iot-hub, makes the protocol useless for us, and I can guess for a lot of other developers as well.
PS, Adding the support is not that difficult, If that is the real reason why you refuse to support it

**Comment by zolvarga** [comment] 2018-05-23 17:53
@JakkeFiejest 

Please feel free to create a PR with the suggested solution

Best Regards,
Zoltan

**Comment by CIPop** [comment] 2018-06-15 18:42
> If it is needed, I want to add it myself to the codebase.

@JakkeFiejest Thanks for your interest in enhancing our SDKs! While I am not yet able to actually assign the issue to you, please feel free to start working on the design. (I'll check to see how we can make the assignments in the future.) 
I'll add more details to that issue.

Closed as duplicate of #477

**Closed by CIPop** 2018-06-15 18:42 UTC
Labels: enhancement
