### ISSUE TITLE
AMQP ReceiveMessageCallback not fired after some time

### ISSUE THREAD

**Issue by dkattan** [Azure/azure-iot-sdk-csharp#1909] opened 2021-04-24 11:06 UTC
# Context
- Windows 10 x64
- netcoreapp3.1 and netcoreapp5
- SDK Devices.Client 1.21-1.35 (Have not yet tested with 1.36)

## Description of the issue
In our code we use both DirectMethods and C2D Messages. We use C2D Messages to initiate operations that exceed the 300 second timeout of DirectMethods.

We recently switched from MQTT to AMQP as a workaround for the 65 minute reconnect issue that was causing unnecessary lifecycle events to be fired into our backend application.

After this switch to AMQP we noticed that after around 24 hours, the DeviceClient stops responding to C2D messages.

I believe the problem is that my callback is hanging perpetually and the DeviceClient is not releasing the ReceiveMessageSemaphore until after the user supplied callback is completed.

This was discussed in a recent Pull Request #1823 but it appears the decision was made to not change the existing functionality.

Of course this could be my fault for allowing my callback to block forever, but I believe the SDK should not await the user supplied callback in the first place.

**Comment by abhipsaMisra** [comment] 2021-04-26 17:07
You are correct, we do have some inconsistency where some library callbacks are currently awaiting on the user-supplied callback to complete. There is no requirement for the client library to do this, so we will fix this at our end.

**Comment by dkattan** [comment] 2021-04-28 09:04
I did further testing and determined that my initial assertion was likely incorrect. I initiated a long running operation, followed by a short running operation and found that even with the long running operation blocking the user supplied callback, the short running operations continued to work as expected.

I discovered that the DeviceClient.ReceiveMessageAsync(CancellationToken cancellationToken) overload ignores the cancellation token.

I am creating a new issue for this as it is easily reproduceable and outside the scope of this issue.

**Comment by bikamani** [comment] 2021-05-04 16:44
@dkattan to understand correctly, do you still see the same issue of device client not responding to C2D messages after around 24 hours? Does it happen only with DeviceClient.ReceiveMessage(CancellationToken cancellationToken) method?

**Comment by dkattan** [comment] 2021-05-04 17:35
> @dkattan to understand correctly, do you still see the same issue of device client not responding to C2D messages after around 24 hours? Does it happen only with DeviceClient.ReceiveMessage(CancellationToken cancellationToken) method?

The problem was occurring when I called DeviceClient.ReceiveMessage() with no parameters. In an effort to resolve it I attempted to use the overload with the CancellationToken, which is how I discovered it didn't work.

I just changed it to use a TimeSpan of 1 second so I have a polling loop to manually check the cancellation token. I just released the code with this change so I don't have any data to know if it has resolved the initial issue yet. I should know in a few days.

**Comment by bikamani** [comment] 2021-05-05 00:41
@dkattan Thanks for responding super quickly. What does your application code look like with no parameters/ with timespan where you're seeing the issue? So that I could repro the issue.

**Comment by dkattan** [comment] 2021-05-05 01:25
I’m not expecting this to be easy to reproduce given that you essentially have to wait some unspecified time period between 24-200 hours before it happens. 

The code below exhibited the issue:
```
while (!cancellationToken.IsCancellationRequested)
            {
                Message receivedMessage = null;
                try
                {
                    
                    receivedMessage = await DeviceClient.ReceiveAsync();
                    if (receivedMessage == null) continue;
                    // get event object
                    var evt = JsonConvert.DeserializeObject<Event<JObject>>(Encoding.ASCII.GetString(receivedMessage.GetBytes()));
                    if (evt == null)
                    {
                        _logger.LogError("Received an event that failed to deserialize to Event<JObject>");
                        continue;
                    }
                    // immediately acknowledge the message
                    await DeviceClient.CompleteAsync(receivedMessage);

// Business Logic to handle message

catch (Exception ex)
                {
                    if (receivedMessage != null)
                        await DeviceClient.CompleteAsync(receivedMessage);
                    _logger.LogError(ex, "Unhandled exception while receiving a cloud to device event");
                }
            }

}

```

**Comment by bikamani** [comment] 2021-06-14 16:42
@dkattan Apologize for delay on this. To update, I am yet to investigate this issue while working on other priorities. In your response previously, you mentioned you are now using TimeSpan of 1 second - did you mean to change your application code to instead use - "ReceiveAsync(TimeSpan timeout)"? 

I am curious to know what are the results?

**Comment by vinagesh** [comment] 2021-07-01 22:15
Based on the code snippet above, you seem to be using the polling way to receive messages - DeviceClient.ReceiveAsync(). This is not related to the ReceiveMessageSemaphore. 

I wanted to understand if you are trying to use both DeviceClient.ReceiveAsync() and DeviceClient.SetReceiveMessageHandlerAsync(). I think our documentation does not explicitly call this out but once you set the handler, you will no longer receive any messages through DeviceClient.ReceiveAsync(). 

I do agree that it is not a good practice for the SDK to await any user callbacks and we will fix that. However, that does not seem to be the root cause for  you not receiving the callback and I want to understand more about your use case to figure out why you don't get it after 24 hours. And the semaphore is currently being released before we await the callback so even if you have a forever blocking callback, your next message should be received without issues.

**Comment by dkattan** [comment] 2021-07-02 13:14
> Based on the code snippet above, you seem to be using the polling way to receive messages - DeviceClient.ReceiveAsync(). This is not related to the ReceiveMessageSemaphore.
> 
> I wanted to understand if you are trying to use both DeviceClient.ReceiveAsync() and DeviceClient.SetReceiveMessageHandlerAsync(). I think our documentation does not explicitly call this out but once you set the handler, you will no longer receive any messages through DeviceClient.ReceiveAsync().
> 
> I do agree that it is not a good practice for the SDK to await any user callbacks and we will fix that. However, that does not seem to be the root cause for you not receiving the callback and I want to understand more about your use case to figure out why you don't get it after 24 hours. And the semaphore is currently being released before we await the callback so even if you have a forever blocking callback, your next message should be received without issues.

I just checked and we don’t appear to use DeviceClient.SetReceiveMessageHandlerAsync(), but perhaps that would be a better solution as we are using DeviceClient.SetMethodHandlerAsync for DirectMethods and that has proven to be reliable.

Currently we are polling using DeviceClient.RecieveMessageAsync(TimeSpan.FromSeconds(1));

I think this is working as I haven’t seen this problem surface since making that change. 

I prefer not to poll and have it be event driven, and now that I’m aware of DeviceClient.SetReceiveMessageHandlerAsync() I think that is likely the way we should have implemented it in the beginning rather than calling DeviceClient.ReceiveMessageAsync() with no timeout.

**Comment by vinagesh** [comment] 2021-07-02 17:08
Sounds good! That is definitely a better approach rather than polling. Is there anything else you need help with? Let me know if all of the issues are resolved or not to close this.

**Comment by dkattan** [comment] 2021-07-02 21:07
I think we can close this issue. The information here should be enough to help anyone experiencing similar issues.

Darren Kattan
Vice President

    
    
IMMENSE NETWORKS
10988 N. Harrells Ferry Rd., Suite 7
Baton Rouge, LA 70816
P: 225-754-9005
F: 866-850-7519
Web: www.immense.net

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2021-07-06 17:51 UTC
Labels: IoTSDK, bug
