### ISSUE TITLE
Devices Client library causes .NET Native runtime failure when targetting Windows IoT Core 16299 for ARM

### ISSUE THREAD

**Issue by bderuijsscher** [Azure/azure-iot-sdk-csharp#400] opened 2018-03-13 10:53 UTC
It seems like an incompatibility issue with .Net standard 2.0. The error generated runtime is:

"The Program [XXX] has exited with code -1073741511 (0xc0000139) Entry Point Not Found"

Steps to reproduce:

- Create a new blank ARM project targetting Windows (IoT Core) 16299 for ARM. Set both minimum and target version to 16299, it will use .NET Standard 2.0
- Include the Microsoft.Devices.Client Nuget package
- Build a release version, make sure to compile using .Net Native and attempt to run the project on an ARM based target devices (i.e. Raspberry PI 3)

Please refer to [this](https://github.com/dotnet/corert/issues/5524#issuecomment-372437971) issue I have reported on the .net core github, however I am unsure where the solution should be sought.

**Comment by CIPop** [comment] 2018-03-13 20:57
Duplicate of #315. Fix will come up in the next release (on which I'm working on today).

**Closed by CIPop** 2018-03-13 20:57 UTC
Labels: bug

**Comment by bderuijsscher** [comment] 2018-03-14 09:47
Thanks for the notification, I can confirm that the newest 1.7.0 release of has solved the problem! Thanks again.
