### ISSUE TITLE
Publish CancellationToken for Async methods

### ISSUE THREAD

**Issue by Stromberg** [Azure/azure-iot-sdk-csharp#295] opened 2017-12-15 13:13 UTC
The OperationTimeoutInMilliseconds on DeviceClient is good as it hinders methods from hanging forever but it is also quite limited in comparison to what is flexibility possible with CancellationTokens with possibilities for distributed cancellation etc.

I propose following the guidelines for async task APIs and allow for the provision of a CancellationToken.

Example: 

OpenAsync(CancellationToken token = CancellationToken.None);

**Comment by CIPop** [comment] 2017-12-19 20:44
Completely agree!

@yzhong94 @tameraw @jasmineymlo

**Comment by CIPop** [comment] 2017-12-19 20:51
This is not very simple to implement as I've found while investigating #85. While it appears that the tokens are flowing down our transport pipeline I've seen the following issues:
1. The transport layer for MQTT doesn't properly handle cancellations today. For safety, we're allowing the transport to run in the background, after the application received the completion based on OperationTimeoutInMilliseconds until it "naturally" times out based on MQTT transport handler rules.

2. I believe that the AMQP library doesn't support CancellationTokens, instead allowing only for operation timers. Cooperative cancellation will mean that the application will not gain control until one of these operations complete according to these timers.

This is related to #290 and since it requires substantial implementation changes could be bundled with #246.

**Comment by CIPop** [comment] 2018-02-09 00:10
Closing this one as duplicate of #114

**Closed by CIPop** 2018-02-09 00:10 UTC
Labels: enhancement, help wanted
